### PR TITLE
Fix exception when checking for engine update

### LINKED ISSUE #4196: Error while checking for engine updates
### Engine version
1.9.0.0.12461

### My Operating System
Windows 7 64bit

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Start TripleA, see:

traerror

### Do you have the exact error text? Please copy/paste if so

```
Okt 20, 2018 9:37:59 AM games.strategy.engine.auto.update.EngineVersionCheck checkForLatestEngineVersionOut
SCHWERWIEGEND: Error while checking for engine updates
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at games.strategy.triplea.settings.GameSetting.value(GameSetting.java:47)
	at games.strategy.engine.auto.update.EngineVersionCheck.isEngineUpdateCheckRequired(EngineVersionCheck.java:59)
	at games.strategy.engine.auto.update.EngineVersionCheck.isEngineUpdateCheckRequired(EngineVersionCheck.java:44)
	at games.strategy.engine.auto.update.EngineVersionCheck.checkForLatestEngineVersionOut(EngineVersionCheck.java:25)
	at games.strategy.engine.auto.update.UpdateChecks.checkForUpdates(UpdateChecks.java:26)
	at java.lang.Thread.run(Unknown Source)

Okt 20, 2018 9:37:59 AM games.strategy.engine.framework.GameRunner lambda$start$0
SCHWERWIEGEND: No value present
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at games.strategy.triplea.settings.GameSetting.value(GameSetting.java:47)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:28)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:16)
	at games.strategy.engine.auto.update.UpdateChecks.checkForUpdates(UpdateChecks.java:28)
	at java.lang.Thread.run(Unknown Source)
```

### Any additional information that may help
I have never experienced this before.
Not sure whether this might be relevant: I have updated Java 8 from update 181 to 191 before.
(Clean install).

I have never been aware of an automatic engine update check before. Maybe because I update manually on a daily base. Is there an option to disable that?

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Fixes #4196.

`ClientSetting#lastCheckForEngineUpdate` has no default value, and thus the caller must check for the presence of the setting value before using it.  The one usage in `EngineVersionCheck` is the sole usage of `lastCheckForEngineUpdate`, so no other call sites require a similar update.

## Functional Changes

* Check for the presence of a value in the `lastCheckForEngineUpdate` client setting before attempting to use it.

## Manual Testing Performed

* Manually set `firstTimeThisVersion` to `false` and cleared the value for `lastCheckForEngineUpdate` to force the code to read `lastCheckForEngineUpdate` when it has no value.  Verified no exception occurred and the update check was run.

## Additional Review Notes

* I plan on searching for other calls to `GameSetting#value()` for client settings that do not have a default value to prevent similar exceptions from occurring.  This will be addressed in a follow-up PR.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java [hunk 1]
```diff
@@ -55,18 +55,16 @@ static boolean isEngineUpdateCheckRequired(
...
-    final boolean firstRun = firstRunSetting.value();
-    final String encodedUpdateCheckDate = updateCheckDateSetting.value();
-    if (!firstRun && !encodedUpdateCheckDate.trim().isEmpty()) {
-      final LocalDate updateCheckDate = parseUpdateCheckDate(encodedUpdateCheckDate);
-      if (updateCheckDate.isAfter(now.minusDays(2))) {
-        return false;
-      }
+    final boolean updateCheckRequired = firstRunSetting.value()
+        || updateCheckDateSetting.getValue()
+            .map(encodedUpdateCheckDate -> !parseUpdateCheckDate(encodedUpdateCheckDate).isAfter(now.minusDays(2)))
```
Comment (ssoloff) [inline game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java]: The negation smell here is due to `LocalDate` not offering an `isBeforeOrEqual()` method.

Comment (ssoloff) [reply game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java]: Yup, I did consider that, but the lambda expression changed to a very busy lambda block:

```java
|| updateCheckDateSetting.getValue()
    .map(encodedUpdateCheckDate -> {
      final LocalDate updateCheckDate = parseUpdateCheckDate(encodedUpdateCheckDate);
      final LocalDate targetDate = now.minusDays(2);
      return updateCheckDate.isBefore(targetDate) || updateCheckDate.isEqual(targetDate);
    })
    .orElse(true);
```

Which I then extracted to a method:

```java
|| updateCheckDateSetting.getValue()
    .map(encodedUpdateCheckDate -> isBeforeOrEqual(parseUpdateCheckDate(encodedUpdateCheckDate), now.minusDays(2)))
    .orElse(true);
```

Where `isBeforeOrEqual()` is

```java
private static boolean isBeforeOrEqual(final LocalDate date, final LocalDate otherDate) {
  return date.isBefore(otherDate) || date.isEqual(otherDate);
}
```

At the end of that exercise, I figured the negation smell was better than the verbosity.  But I'm happy to change to one of those two alternatives if you find them preferable.

Comment (RoiEXLab) [reply game-core/src/main/java/games/strategy/engine/auto/update/EngineVersionCheck.java]: I'm OK with a negated statement ^^
And creating a helper method just for an or expression isn't worth it IMO.
