### PR TITLE
Fix race condition between creating and referencing main frame

### LINKED ISSUE #4003: NPE when hosting lobby game
### Engine version

1.9.0.0.11892

### My Operating System

Linux localhost.localdomain 4.17.19-200.fc28.x86_64 <span>#</span>1 SMP Fri Aug 24 15:47:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

1. Connect to lobby.
1. Click **Host Game**.
1. Wait for new TripleA process to start.
1. After a brief delay, the new process will switch from the main menu to the server configuration screen.

### Do you have the exact error text? Please copy/paste if so

At step (4), the following exceptions are reported in the console:

```
Sep 09, 2018 12:06:02 AM games.strategy.engine.framework.GameRunner lambda$0
SEVERE: null
java.lang.NullPointerException
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.lambda$0(SetupPanelModel.java:62)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Sep 09, 2018 12:06:02 AM games.strategy.engine.framework.GameRunner lambda$0
SEVERE: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
	at com.google.common.escape.ArrayBasedCharEscaper.escape(ArrayBasedCharEscaper.java:106)
	at games.strategy.debug.TextUtils.textToHtml(TextUtils.java:10)
	at games.strategy.debug.ErrorMessage.lambda$2(ErrorMessage.java:99)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Instead of this error, what should have happened?

No exceptions in the console.

### Any additional information that may help

* The errors do not appear to prevent starting the host.
* The second exception is unrelated.  It's simply due to incorrect handling in `ErrorMessage#show()` when a `null` error message is received.  (**EDIT:** See #4004.)

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Fixes #4003.

The root cause of the NPE in `SetupPanelModel#showServer()` is due to a race condition between the creation of the main frame window in `GameRunner#main()` and referencing it in `GameRunner#showMainFrame()`.

## Functional Changes

* Ensure `GameRunner#showMainFrame()` is not called until `GameRunner#mainFrame` has been initialized.

## Manual Testing Performed

Reproduced the scenario described in #4003 and verified no exceptions were raised.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/engine/framework/GameRunner.java [hunk 1]
```diff
@@ -148,9 +148,9 @@ public static void main(final String[] args) {
       SwingUtilities.invokeLater(() -> {
         mainFrame = newMainFrame();
         setupPanelModel.showSelectType();
+        new Thread(GameRunner::showMainFrame).start();
```
Comment (ssoloff) [inline game-core/src/main/java/games/strategy/engine/framework/GameRunner.java]: Really, dude?  Really?
