### PR TITLE
Fix exception when formatting bot start time

### LINKED ISSUE #3740: New Release is unusable for Lobby
.11122

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

image

### Instead of this error, what should have happened?

Not this. ;)

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Fixes #3740.

`Instant` doesn't support the `SHORT` time format because it doesn't provide a time zone.  Need to convert `Instant` to `LocalDateTime` before formatting.

## Functional Changes

None.

## Manual Testing Performed

Connected to lobby hosting one bot as a moderator.  No exception raised and bot start time was displayed correctly.

## Additional Review notes

Please review with whitespace changes ignored due to indentation changes in the test code.

### CODE REVIEW

File: game-core/src/test/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModelTest.java [hunk 1]
```diff
@@ -25,88 +28,98 @@
...
-    Mockito.verify(mockLobbyController, Mockito.times(1)).listGames();
-
-    MessageContext.setSenderNodeForThread(serverNode);
-    Mockito.when(mockMessenger.getServerNode()).thenReturn(serverNode);
-    TestUtil.waitForSwingThreads();
-    assertThat("games are loaded on init", testObj.getRowCount(), is(1));
+public final class LobbyGameTableModelTest {
+  @ExtendWith(MockitoExtension.class)
+  @Nested
+  final class RemoveAndUpdateGameTest {
```
Comment (ssoloff) [inline game-core/src/test/java/games/strategy/engine/lobby/client/ui/LobbyGameTableModelTest.java]: Had to break this up into separate fixtures to avoid a Mockito strictness warning due to the fixture-level mocks not being used by the new `formatBotStartTime()` test.
