### PR TITLE
Do not propagate lobby server SQLExceptions to client

### LINKED ISSUE #4141: Database error raised during lobby operation causes client to disconnect
### Engine version

1.9.0.0.12287

### Description

**TL;DR:** If a database error occurs on the lobby server, the exception serialized over RMI cannot be deserialized on the client side.  This causes the client to disconnect from the lobby.  The root cause is due to #3877 when the Postgres dependency was moved to the `lobby` project.  Thus, it isn't available to `game-headed`, and instances of `PSQLException` cannot be deserialized by the lobby client.

<hr>

@Cernelius originally reported this issue on the forum:

> I was about the give a 2 weeks ban, right clicking, for both name and mac, to &lt;redacted&gt; when I got disconnected from the lobby.
> So, I rejoined the lobby and gave the same ban and, again, I was disconnected. The error message was:
> "Connection to Server Lost. Please close this instance and reconnect to the lobby."
> This is the same thing that happened the first time I tried, as well.
> I think this is a serious bug here.

A stack trace was provided:

<details>
<summary>Full log</summary>

```
ott 03, 2018 10:24:42 PM games.strategy.net.nio.Decoder loop
GRAVE: error reading object
java.io.IOException: java.lang.ClassNotFoundException: org.postgresql.util.PSQLException
at games.strategy.net.nio.Decoder.lambda$loop$0(Decoder.java:71)
at games.strategy.io.IoUtils.readFromMemory(IoUtils.java:60)
at games.strategy.net.nio.Decoder.loop(Decoder.java:67)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PSQLException
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at java.io.ObjectInputStream.resolveClass(Unknown Source)
at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
at java.io.ObjectInputStream.readClassDesc(Unknown Source)
at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
at java.io.ObjectInputStream.readObject0(Unknown Source)
at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
at java.io.ObjectInputStream.defaultReadObject(Unknown Source)
at java.lang.Throwable.readObject(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
at java.io.ObjectInputStream.readSerialData(Unknown Source)
at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
at java.io.ObjectInputStream.readObject0(Unknown Source)
at java.io.ObjectInputStream.readObject(Unknown Source)
at games.strategy.engine.message.RemoteMethodCallResults.readExternal(RemoteMethodCallResults.java:56)
at games.strategy.engine.message.unifiedmessenger.InvocationResults.readExternal(InvocationResults.java:46)
at games.strategy.net.nio.Decoder.readMessageHeader(Decoder.java:149)
at games.strategy.net.nio.Decoder.lambda$loop$0(Decoder.java:69)
... 3 more

ott 03, 2018 10:24:42 PM games.strategy.engine.framework.GameRunner lambda$start$0
GRAVE: Exception on remote
java.lang.RuntimeException: Exception on remote
at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:54)
at com.sun.proxy.$Proxy2.banUsername(Unknown Source)
at games.strategy.engine.lobby.client.ui.LobbyFrame.lambda$createAdminActions$2(LobbyFrame.java:142)
at games.strategy.engine.lobby.client.ui.TimespanDialog.lambda$runAction$4(TimespanDialog.java:213)
at java.util.Optional.ifPresent(Unknown Source)
at games.strategy.engine.lobby.client.ui.TimespanDialog.runAction(TimespanDialog.java:211)
at games.strategy.engine.lobby.client.ui.TimespanDialog.prompt(TimespanDialog.java:206)
at games.strategy.engine.lobby.client.ui.LobbyFrame.lambda$createAdminActions$3(LobbyFrame.java:137)
at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:65)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.AbstractButton.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: java.lang.ClassNotFoundException: org.postgresql.util.PSQLException
at games.strategy.net.nio.Decoder.lambda$loop$0(Decoder.java:71)
at games.strategy.io.IoUtils.readFromMemory(IoUtils.java:60)
at games.strategy.net.nio.Decoder.loop(Decoder.java:67)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PSQLException
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at java.io.ObjectInputStream.resolveClass(Unknown Source)
at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
at java.io.ObjectInputStream.readClassDesc(Unknown Source)
at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
at java.io.ObjectInputStream.readObject0(Unknown Source)
at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
at java.io.ObjectInputStream.defaultReadObject(Unknown Source)
at java.lang.Throwable.readObject(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at java.io.ObjectStreamClass.invokeReadObject(Unknown Source)
at java.io.ObjectInputStream.readSerialData(Unknown Source)
at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
at java.io.ObjectInputStream.readObject0(Unknown Source)
at java.io.ObjectInputStream.readObject(Unknown Source)
at games.strategy.engine.message.RemoteMethodCallResults.readExternal(RemoteMethodCallResults.java:56)
at games.strategy.engine.message.unifiedmessenger.InvocationResults.readExternal(InvocationResults.java:46)
at games.strategy.net.nio.Decoder.readMessageHeader(Decoder.java:149)
at games.strategy.net.nio.Decoder.lambda$loop$0(Decoder.java:69)
... 3 more
```
</details>

I wasn't able to reproduce @Cernelius's original error, but I was able to manually trigger a database error and observed the exact same symptom reported above.  (@Cernelius, any additional information you can provide beyond your forum post to help us reproduce the actual database error would be appreciated.)

I verified that if I moved the Postgres dependency back to the `game-core` project, the `PSQLException` is deserialized correctly, and the user is not disconnected, but rather is simply presented with our standard error dialog.

I tried to see if there was a better way to communicate errors over RMI.  For example, by simply sending a string representation of the error, possibly including the stack trace, instead of serializing the actual exception.  However, it would require breaking compatibility with the lobby, which I'm not sure we've committed to yet.

Another possibility is to never re-throw instances of `SQLException` up the call stack, either standalone or as the cause of another exception.  That would ensure we never try to send the `PSQLException`s over the wire.  The benefit of this solution is that it should only require deploying a new lobby; an updated client would not be required.

If we go with simply moving the dependency back to `game-core`, note that this is going to require pushing a hotfix for the current stable.  Since we've already broke compatibility on `master`, we'll have to deal with publishing releases from a secondary branch sooner rather than later.

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Fixes #4141.

When a Postgres database error occurs, the Postgres driver throws a custom subclass of `SQLException`.  This subclass is defined in the Postgres JDBC driver library, and thus is not available to clients because they do not declare this dependency.  When a client attempts to deserialize such an exception, it triggers a `ClassNotFoundException`.  This not only hides the original exception from the client, but it has the side effect of disconnecting the client (most likely a mod) from the server.

This PR fixes the issue by ensuring the custom subclass is never serialized across the wire to the client to avoid the `ClassNotFoundException`.  An alternative fix would have been to make the client depend on the Postgres JDBC driver library, but bringing in an almost 1 MiB jar just for this case didn't seem productive. 

## Functional Changes

* `SQLException`s raised within the lobby server are no longer propagated to the client.
    * The `SQLException` message is preserved in the unchecked exception ultimately sent to the client.
    * The original `SQLException` is sent to the server log for reference during troubleshooting.

## Manual Testing Performed

* Manually triggered an exception to occur when banning a username where the username exceeds the maximum length of the corresponding database column (by essentially reverting #4153).
    * Verified the client was notified of the error, but the client did not disconnect from the server.
    * Verified the error reported in the client's Error Console contained the message from the `SQLException` but the `SQLException` itself did not appear in the stack trace.
    * Verified the server log contained the stack trace for the `SQLException`.

### CODE REVIEW

File: lobby/src/main/java/org/triplea/lobby/server/db/AbstractController.java [hunk 1]
```diff
@@ -20,4 +24,9 @@
   final Connection newDatabaseConnection() throws SQLException {
     return database.newConnection();
   }
+
+  static RuntimeException newDatabaseException(final String message, final SQLException e) {
```
Comment (ron-murhammer) [inline lobby/src/main/java/org/triplea/lobby/server/db/AbstractController.java]: Something about "new" feels a bit weird and makes me think its actually a constructor. Might be better to use "create".
