### PR TITLE
DB enhancements

### LINKED ISSUE #2347: Lobby login fails
### My Operating System:
Win 7.64
### TripleA version:
1.9.0.0.6538

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Login with my **new account** fails:

lobby

Though my user name exists:

lobby2

Please indicate how I can provide more information, as there is no error log and no console message.

### PR DESCRIPTION
**Pull request by RoiEXLab**
Resolves #2347/The rest of it
The main focus of this PR is to allow for backwards compatibility between the two password systems. This backwards compatibility should be completely removed in the next incompatible lobby update.
The biggest part however does some general cleanup + enhances the code overall/makes it more resistent to failures by moving some of the logic to the DB itself (such as default values).
I will add some comments to explain some of the changes I made.
When updating the lobby with this patch, the database is going to need to be altered quite a lot, to match the stricter requirements.

I tested logins manually, created the account with the latest stable, logged in twice on a local lobby (which works great now that derby is no longer required :D) , and was able to login with the stable release once again.
First creating an account with my branch and then logging in with the latest stable works too.

### CODE REVIEW

File: config/lobby/db/001_create_tables [hunk 1]
```diff
@@ -1,94 +1,58 @@
-create table bad_words (
-    word character varying(40) not null
+CREATE TABLE ta_users (
+    username character varying(40) NOT NULL PRIMARY KEY,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: I moved the PRIMARY KEY constraints to the columns themeselves

File: config/lobby/db/001_create_tables [hunk 2]
```diff
@@ -1,94 +1,58 @@
...
+    password character(34),
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: I lowered the char amount to 34 (and used fixed char types), because the MD5Crypt hashes always have that length.

File: config/lobby/db/001_create_tables [hunk 3]
```diff
@@ -1,94 +1,58 @@
...
+    bcrypt_password character(60),
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: The BCrypt hashes have always the same length, therefore they don't need to vary in length

File: config/lobby/db/001_create_tables [hunk 4]
```diff
@@ -1,94 +1,58 @@
...
+    CHECK (password IS NOT NULL OR bcrypt_password IS NOT NULL),
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: We can't always require both passwords, this ensures at least one password is given

File: config/lobby/db/001_create_tables [hunk 5]
```diff
@@ -1,94 +1,58 @@
...
+    email character varying(254) NOT NULL,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: I increased the value to match the maximum email length.
More information here: https://stackoverflow.com/a/574698

File: config/lobby/db/001_create_tables [hunk 6]
```diff
@@ -1,94 +1,58 @@
...
+    joined timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: We don't need to set this timestamp manually in the java code,
also I changed the type to timestamp with time zone, because in case the lobby server moves to a different time zone, the timestamps would still be correct.
More information here: https://stackoverflow.com/a/14070771

File: config/lobby/db/001_create_tables [hunk 7]
```diff
@@ -1,94 +1,58 @@
...
+    lastlogin timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
+    admin integer NOT NULL DEFAULT 0
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: Left this the same for now, but I'd suggest using either a boolean type (if we only need to roles), or enums (if we want to add new roles in the future) in the future.

File: config/lobby/db/001_create_tables [hunk 8]
```diff
@@ -1,94 +1,58 @@
...
 
-
-alter table bad_words owner to postgres;
-
-
-create table banned_ips (
-    ip character varying(40) not null,
-    ban_till timestamp without time zone
+CREATE TABLE bad_words (
+    word character varying(40) NOT NULL PRIMARY KEY
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: I think a Database is overkill for a single collection like this.
In theory this table shouldn't be even changed that often, so IMO a space separated file would be sufficient, we could simply update it here on GitHub

File: config/lobby/db/001_create_tables [hunk 9]
```diff
@@ -1,94 +1,58 @@
...
+ALTER TABLE banned_macs owner TO postgres;
 
 
-alter table banned_usernames owner to postgres;
-
-create table muted_ips (
-    ip character varying(40) not null,
-    mute_till timestamp without time zone
+CREATE TABLE banned_usernames (
+    username character varying(40) NOT NULL PRIMARY KEY REFERENCES ta_users ON DELETE CASCADE ON UPDATE CASCADE,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: I added a reference, so in case a username is changed/removed while it's banned somehow, the entry is being updated/removed along with it.
I don't understand why a seperate table was even created for this.
banned_usernames and ta_users have a 1:1 relation, which means they should be merged permanently.

Also banned_* and muted_* could be merged to a single table with 3 columns each

File: src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java [hunk 10]
```diff
@@ -6,27 +6,19 @@
...
  * Utilitiy class to create/read/delete bad words (there is no update).
  */
 public class BadWordController {
-  private static final Logger logger = Logger.getLogger(BadWordController.class.getName());
-
   public void addBadWord(final String word) {
     try (final Connection con = Database.getPostgresConnection();
-        final PreparedStatement ps = con.prepareStatement("insert into bad_words (word) values (?)")) {
+        final PreparedStatement ps =
+            con.prepareStatement("insert into bad_words (word) values (?) on conflict do nothing")) {
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java]: Currently if a bad word already exists, postgres or any other DB would throw an exception with code 30000 (not sure if the error codes are even universal), this is bad practise since we can just use built in features of postgres.
If a word is already present, we don't need to do anything.

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java [hunk 11]
```diff
@@ -36,21 +36,15 @@ public void addBannedMac(final String mac, final Instant banTill) {
     }
     Timestamp banTillTs = null;
     if (banTill != null) {
-      banTillTs = new Timestamp(banTill.toEpochMilli());
+      banTillTs = Timestamp.from(banTill);
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: This way of getting the java.sql.Timestamp from an Instant is actually more accurate than the other way (nano precision), and as far as I can tell it is not affected by the Year-2038-Problem.

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java [hunk 12]
```diff
@@ -36,21 +36,15 @@ public void addBannedMac(final String mac, final Instant banTill) {
...
     }
     try (final Connection con = Database.getPostgresConnection();
-        final PreparedStatement ps = con.prepareStatement("insert into banned_macs (mac, ban_till) values (?, ?)")) {
+        final PreparedStatement ps = con.prepareStatement("insert into banned_macs (mac, ban_till) values (?, ?) on conflict do update")) {
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: In this case we don't want to do nothing (what is the original behaviour), but update the entry instead.
At least this is what the javadocs claim this method does.

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 13]
```diff
@@ -60,37 +71,42 @@ public boolean doesUserExist(final String userName) {
 
   @Override
   public void updateUser(final DBUser user, final HashedPassword hashedPassword) {
+    updateUser(user, hashedPassword, hashedPassword.isBcrypted() ? "bcrypt_password" : "password");
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: Part of the core change

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 14]
```diff
@@ -60,37 +71,42 @@ public boolean doesUserExist(final String userName) {
...
-      throw new IllegalStateException(
-          "Error updating name:" + user.getName() + " email: " + user.getEmail() + " pwd: " + hashedPassword.mask(), e);
+      throw new IllegalStateException(String.format("Error updating name: %s email: %s pwd: %s",
+          user.getName(), user.getEmail(), hashedPassword.mask()), e);
     }
   }
 
   @Override
   public void createUser(final DBUser user, final HashedPassword hashedPassword) {
+    createUser(user, hashedPassword, hashedPassword.isBcrypted() ? "bcrypt_password" : "password");
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: Part of the core change

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 15]
```diff
@@ -60,37 +71,42 @@ public boolean doesUserExist(final String userName) {
...
         final PreparedStatement ps = con.prepareStatement(
-            "insert into ta_users (username, password, email, joined, lastLogin, admin) values (?, ?, ?, ?, ?, ?)")) {
+            "insert into ta_users (username, " + passwordColumn + ", email, admin) values (?, ?, ?, ?)")) {
       ps.setString(1, user.getName());
       ps.setString(2, hashedPassword.value);
       ps.setString(3, user.getEmail());
-      ps.setTimestamp(4, new Timestamp(System.currentTimeMillis()));
-      ps.setTimestamp(5, new Timestamp(System.currentTimeMillis()));
-      ps.setInt(6, user.isAdmin() ? 1 : 0);
+      ps.setInt(4, user.isAdmin() ? 1 : 0);
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: My original intent was to remove this call, but apparently it was used by tests only.
I kept it because we really should implement a way to change privileges from inside the engine.

File: src/main/java/games/strategy/engine/lobby/server/login/LobbyLoginValidator.java [hunk 16]
```diff
@@ -177,9 +177,16 @@ private String validatePassword(final Map<String, String> propertiesSentToClient
       }
 
       return RsaAuthenticator.decryptPasswordForAction(key.get(), propertiesReadFromClient, pass -> {
+        final String legacyHashedPassword = propertiesReadFromClient.get(HASHED_PASSWORD_KEY);
         if (hashedPassword.isBcrypted()) {
-          return userDao.login(clientName, new HashedPassword(pass)) ? null : errorMessage;
-        } else if (userDao.login(clientName, new HashedPassword(propertiesReadFromClient.get(HASHED_PASSWORD_KEY)))) {
+          if (userDao.login(clientName, new HashedPassword(pass))) {
+            if (legacyHashedPassword != null) {
+              userDao.updateUser(userDao.getUserByName(clientName), new HashedPassword(legacyHashedPassword));
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/login/LobbyLoginValidator.java]: Part of the core change

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 17]
```diff
@@ -29,19 +30,30 @@ public UserController() {
...
+   * @return null if the user does not exist or the user has no legacy password stored.
+   */
+  @Override
+  public HashedPassword getMd5Password(final String username) {
+    return getPasswordFromColumn(username, "password");
+  }
+
+  private HashedPassword getPasswordFromColumn(final String username, final String column) {
+    try (final Connection con = connectionSupplier.get();
+        final PreparedStatement ps = con.prepareStatement("select " + column + " from ta_users where username=?")) {
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: In case anyone wonders: No, this can't be abused by SQLInjection attacks.

File: config/lobby/db/001_create_tables (hunk 1 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: No objection, though please stick to all lower case if you would.

File: config/lobby/db/001_create_tables (hunk 2 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: This is now an existing table, it needs to be done with an alter statement. I'm really not clear on why we can shorten to 34 though, wasn't 40 the existing, can we not have passwords that length existing?

File: config/lobby/db/001_create_tables (hunk 5 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Please update to an alter statement. This seems like a good catch. Would you have any objection to adding a quick integration test to demonstrate this problem and fix?

File: config/lobby/db/001_create_tables (hunk 6 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Sounds okay. While on the topic, can we force all timestamps to be UTC somehow? I was looking at the DB rows the other day and had no clue which timezone, it looked like EST.

File: config/lobby/db/001_create_tables (hunk 7 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Pls avoid enumerated types in DB. They are awful in mysql, I don't know if postgres has the same issues but I can't imagine it being much better. A second table and foreign key constraint is the classic way to do that. In this case a boolean value column seems the most straight forward.

File: config/lobby/db/001_create_tables (hunk 8 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: The benefit of live updates is pretty significant. A file you would need to re-read each time. The file requires direct server access and a file to be modified, previously it was all set up so moderators could use the a GUI to update DB values. 

I personally would like us to stick to exactly one configuration file for now if we can get away with it.

On the other hand, we are missing the data for this table and need some insert statements.

File: config/lobby/db/001_create_tables (hunk 2 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: TBH we need column comments, that should be standard as part of our table schema. Your comments @RoiEXLab  are very useful, but we need that info beyond review. So we could update this file with things like:
`password character(34) comment 'stores md5 encrypted password, length is always 34'`

Would you mind making that update @RoiEXLab ?

File: config/lobby/db/001_create_tables (hunk 3 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Have you considered making that a constraint? I'm not sure if `character` handles empty as null, I don't think it does, so empty character or lengths up to 59 would violate that assumption.

File: config/lobby/db/001_create_tables (hunk 5 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Please update to be an alter statement so this can be applied to the live schema.

File: config/lobby/db/001_create_tables (hunk 6 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: It does not seem like we should even be doing this, can we force the timestamp to default to UTC? I really do not want any signficant timezones in our data. I'm picturing a case where a linode is migrated by linode from east to west coast, suddenly now we have to do timezone translation in queries (what a nightmare for what should have been very simple tasks like, "how many people joined in the last week"

File: config/lobby/db/001_create_tables (hunk 1 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: I personally like having keywords in CAPS and everything else lowercase, because it makes it easy to differenciate between keywords and names, no problem, I can change that.

File: config/lobby/db/001_create_tables (hunk 7 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Agree a boolean type would be better here

File: config/lobby/db/001_create_tables (hunk 1 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: Also it's the default SQL style, so I just stick to it.

File: config/lobby/db/001_create_tables (hunk 9 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: the username field in ta_users is presumably mutable, there is no relationship between the two at all. If we ban a name, then a user deletes and recreates their account, we want to keep the username banned. Seems like this would delete the entry with ta_users and so a banned username could be defeated by recreating an account.


I think in general we should avoid cascade deletes/updates. Fundamentally I think the real problem is that there is no id column for users.

File: config/lobby/db/001_create_tables [hunk 18]
```diff
@@ -1,94 +1,58 @@
...
 
 
-alter table muted_ips owner to postgres;
-
-create table muted_macs (
-    mac character varying(40) not null,
-    mute_till timestamp without time zone
+CREATE TABLE muted_ips (
+    ip character varying(40) NOT NULL PRIMARY KEY,
+    mute_till timestamp with time zone
```
Comment (DanVanAtta) [inline config/lobby/db/001_create_tables]: Keeping with the theme of skipping time zone complexity altogether:
1. can we default time zone to UTC and skip any mention of time zone in the code?
2. instead maybe use an epoch milli time stamp stored as a number?

I think for now it may be better to keep this branch focused on the bcrypt password updates and let's tackle time zone updates on their own.

File: config/lobby/db/001_create_tables (hunk 2 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: The passwords are not stored in plain text, they are hashed with the md5crypt algorithm which all have the exact length of 34 (I checked with `SELECT max(char_length(password)), min(char_length(password))` before you altered the table to allow up to 60 chars), I plan to move all of the bcrypted passwords to the new row before applying this change, I'm probably going to create a list or SQL statements which modify the DB before updating the lobby.

File: config/lobby/db/001_create_tables [hunk 19]
```diff
@@ -1,94 +1,58 @@
...
-
-create table ta_users (
-    username character varying(40) not null,
-    password character varying(60) not null,
-    email character varying(40) not null,
-    joined timestamp without time zone not null,
-    lastlogin timestamp without time zone not null,
-    admin integer not null
+CREATE TABLE muted_usernames (
+    username character varying(40) NOT NULL PRIMARY KEY REFERENCES ta_users ON DELETE CASCADE ON UPDATE CASCADE,
```
Comment (DanVanAtta) [inline config/lobby/db/001_create_tables]: recommend we skip updates to any non-critical tables. The cascade delete I am not convinced is wise. In general cascade deletes are really good to avoid so you can stay much more explicit about what is happening and not have DB 'side effects' to consider.

File: src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java [hunk 20]
```diff
@@ -164,7 +164,8 @@ public void notifyFailedLogin(final String message) {
               final Map<String, String> props = new HashMap<>();
               props.put(LobbyLoginValidator.REGISTER_NEW_USER_KEY, Boolean.TRUE.toString());
               props.put(LobbyLoginValidator.EMAIL_KEY, createAccount.getEmail());
-              // TODO: Don't send the md5-hashed password once the lobby is updated
+              // TODO: Don't send the md5-hashed password once the lobby removes the support, kept for
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/engine/lobby/client/login/LobbyLogin.java]: Recommend you make this TODO stronger. First suggestion is to indicate the conditions when we can remove this code, when will we no longer need the backward compatibility. From this context the answer is actually not obvious, from the PR and branch we know it is when we have clients sending bcrypted passwords, but from this code snippet you would not that.

Even better than that, I would recommend using a code branch with flag to allow us to work on this TODO with compile time checks. to do that you would create a file like `PasswordHashMigration`, with a single public static flag: `if(PasswordHashMigration.enableBackwardCompatibility)`. This way you can add all of the TODO commentary in one place to describe when the password migration can be updated to no longer support legacy. Also when we remove the backward compatibiliyt, we simply delete the flag and file and then fix any compilation errors. You could get the same type of location flagging by adding in a project key to the TODO comments, though the compile time version is a stronger and more automated version of that.

File: src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java (hunk 10 above)
Comment (DanVanAtta) [reply src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java]: Noting the 'if' statement in the exception below, this is a good update to get rid of that. We do lose the context of why the conflict would be okay, would you mind adding a quick comment?

NB: I think this entire class is dead code. I suspect we will use SQL directly to do these inserts and not do it via Java code.

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java (hunk 11 above)
Comment (DanVanAtta) [reply src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: The syntax seems simpler to me :+1:

File: config/lobby/db/001_create_tables (hunk 5 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: Having this file full of alter statements wouldn't work, not to mention that CREATE TABLE throws an exception if the table already exists.
This file is only being used by travis AFAIK, so this wouldn't affect the lobby at all.
This reminds me of what the NodeBB guys do: They have a folder called upgrades, which has subfolders with the version numbers.
Whenever you run `./nodebb upgrade` all the scripts that were added since the last execution of this command are run. (They update DB schemes etc.)
Adding integrationTests would be no problem.

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java (hunk 17 above)
Comment (DanVanAtta) [reply src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: Variable arg column is a bit of a wtf. Just write two SQL statements directly and it stays pretty simple. It also conveys that one case we are doing login, the other case for some reason we insist on getting the legacy password. DRY in this case I think is harmful.

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 21]
```diff
@@ -60,37 +72,42 @@ public boolean doesUserExist(final String userName) {
...
+    updateUser(user, hashedPassword, hashedPassword.isBcrypted() ? "bcrypt_password" : "password");
+  }
+
+  private void updateUser(final DBUser user, final HashedPassword hashedPassword, final String column) {
     Preconditions.checkArgument(user.isValid(), user.getValidationErrorMessage());
 
     try (final Connection con = connectionSupplier.get();
         final PreparedStatement ps =
-            con.prepareStatement("update ta_users set password = ?,  email = ?, admin = ? where username = ?")) {
+            con.prepareStatement("update ta_users set " + column + " = ?,  email = ? where username = ?")) {
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: The variable column names are really hard to reason about. I don't see immediately the intent or why, we could use some comments in-code to convey that. Review commentary can be a smell, much of the time that kind of context should be checked in, either in-context with a comment or a design doc.

I suspect this is a good time to step back a bit. Do we really need to support the ability to update either password column? If we are forcing client changes, we would likely spin up a new lobby for those clients to connect to, in that case any lobby code could assume an updated client. That's also an interesting new headache as we now have two instances hitting the same DB, but at least in both cases the code paths are more well known (in the sense that you know legacy always uses md5 and bcrypt will always go through the new code path).

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java (hunk 14 above)
Comment (DanVanAtta) [reply src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: The changes are unrelated enough, different branches I think would have been better. 
- A couple of blockers are going to hold everything up, you may see some merge conflicts as a result of things dragging out
- It's hard to review this many independent changes. I have to figure out which updates are to support other changes and which ones are introducing new concepts.

File: config/lobby/db/001_create_tables (hunk 6 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: The DB should currently store all timestamps with the timezone that is configured to be used by postgres, by default the timezone the server is in.
I know it's possible to retrieve the values as UTC using SQL syntax, but I'm not sure if it works for insert statements as well.
Shouldn't matter too much as long as we don't end up with a completely wrong time at the end...

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java (hunk 15 above)
Comment (DanVanAtta) [reply src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: If this is used by tests only, should we even keep it at all?

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 22]
```diff
@@ -124,18 +141,16 @@ public boolean login(final String userName, final HashedPassword hashedPassword)
         }
       }
       // update last login time
-      try (
-          final PreparedStatement ps = con.prepareStatement("update ta_users set lastLogin = ? where username = ?")) {
-        ps.setTimestamp(1, new Timestamp(System.currentTimeMillis()));
+      try (final PreparedStatement ps = con.prepareStatement("update ta_users set lastLogin=? where username=?")) {
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: formatting nit, space between the '?' and '=' was chomped

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 23]
```diff
@@ -124,18 +141,16 @@ public boolean login(final String userName, final HashedPassword hashedPassword)
...
         ps.setString(2, userName);
         ps.execute();
         con.commit();
         return true;
       }
     } catch (final SQLException sqle) {
       throw new IllegalStateException(
-          "Error validating password name:" + userName + " : " + " pwd:" + hashedPassword.mask(),
-          sqle);
+          String.format("Error validating password name: '%s' pwd: %s", userName, hashedPassword.mask()), sqle);
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: while this is being updated, dumping even the hashed password is not good practice. Would you mind removing the password from the error message?

File: src/main/java/games/strategy/engine/lobby/server/db/UserDao.java [hunk 24]
```diff
@@ -4,15 +4,17 @@
 
 public interface UserDao {
 
-  HashedPassword getPassword(String userName);
+  HashedPassword getPassword(String username);
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/engine/lobby/server/db/UserDao.java]: Looks like we have almost 50/50 `username` vs `userName`

```
dan@dan-desk:~/work/triplea$ find . -type f -name "*java" | xargs grep -o "username" | wc -l
162
dan@dan-desk:~/work/triplea$ find . -type f -name "*java" | xargs grep -o "userName" | wc -l
163
```

This update would tip the balance towards `username`. I think the existing camel case was actually more 'correct'. User name is two words, an adjective plus a noun. Username is not a word. So the camel case of two words would be `userName`

File: src/main/java/games/strategy/engine/lobby/server/db/UserDao.java [hunk 25]
```diff
@@ -4,15 +4,17 @@
...
 
-  boolean doesUserExist(String userName);
+  HashedPassword getMd5Password(String username);
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/engine/lobby/server/db/UserDao.java]: Where is getMd5Password used?

File: config/lobby/db/001_create_tables (hunk 7 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: Ok, converting this to a boolean in this PR, I noticed the value us being retrieved as boolean anyways.
Would you mind telling me what is wrong with enum types in mysql?
It has probably been a year since I last used them.
Looking at the mysql documentation it seems they are pretty similar with the exception that in psql enum types need to be defined in a seperate statement before using them.

**Comment by DanVanAtta** [comment]
Summarizing my suggested action items:
- break up this PR to 3 or 4, this way the non-controversial and good cleanups and simplifications can all be merged quickly
- recommend first present a migration plan/doc with a clear plan of how the transition from md5 to bcrypt will go

File: config/lobby/db/001_create_tables (hunk 1 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: > Also it's the default SQL style, so I just stick to it.

The help docs all use it, but in those cases the keywords are the important things. It turns out that the keywords are some of the least important things in a sql statement. If you format it well, then it is the table, column and where condition clauses that are the most important. `WHERE` is magnitudes less important than anything that comes after it.

File: config/lobby/db/001_create_tables (hunk 5 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: > This file is only being used by travis AFAIK, so this wouldn't affect the lobby at all.

Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: > This file is only being used by travis AFAIK, so this wouldn't affect the lobby at all.

The command travis uses is intended to be what we run to update production. If travis does not mirror prod in this way, it is pointless and bad to have travis doing its own thing. It tests nothing, adds false confidence, and is a waste of time to be maintaining.

> This reminds me of what the NodeBB guys do: They have a folder called upgrades, which has subfolders with the version numbers.
Whenever you run ./nodebb upgrade all the scripts that were added since the last execution of this command are run. (They update DB schemes etc.)

That is basically the idea. For now I was thinking our scripts would be idempotent. I had previously brought up using liquibase to do this for us but was asked to keep it simple in terms of tech stack. Hence numbered files with idempotent commands.

File: config/lobby/db/001_create_tables (hunk 6 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: It's more to maintain and wonder about.  WE should be using the `now()` function for this, so the timezone would always be server. Can we not do something to avoid thinking about timezones at all, force postgres to just use UTC always?

File: config/lobby/db/001_create_tables (hunk 7 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: > Would you mind telling me what is wrong with enum types in mysql?

I'm not the best to describe why. My former boss who did mysql for decades hated them with a passion. I think because the encoding is not just a simple string, so you have massive backward compatibility issues introduced. Most of the time the data structure should just be captured with a constraint check or a second table. So part of the problem is that there are other better solutions for an 'enum' type without the problems.

Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: IMO, put that update in its own branch.

File: config/lobby/db/001_create_tables (hunk 5 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: `CREATE TABLE` > ` CREATE TABLE  if not exists`.

Considering that, it seems we should only run incrementals. Meaning add these statements to a '002' file.

File: config/lobby/db/001_create_tables (hunk 3 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: Good Point. It just learned that the char datatype doesn't enforce a specific length, but just fills the unused chars (probably with NULLS),

File: config/lobby/db/001_create_tables (hunk 5 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: Good idea!

File: config/lobby/db/001_create_tables (hunk 6 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: On postgres NOW() is a synonym for CURRENT_TIMESTAMP
As I said, we definetely can always retrieve it as UTC value, we don't need to care about how it's stored inside the DB, postgres converts everything for us once I modify the queries.

File: config/lobby/db/001_create_tables (hunk 7 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: Was a 2 line change... I think I'm going to revert the password changes and submit a follow-up PR for them and keep everything else in here

File: config/lobby/db/001_create_tables (hunk 9 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: I thought about the ID problem, but I didn't want to increase the scope of this PR that much.
I'd suggest  assigning a pseudo-random id instead of a simple increasing one, in case we want to create an API some time in the future.
```
CREATE SEQUENCE sequence_name;
CREATE TABLE ta_users (
    id bigint NOT NULL DEFAULT pseudo_encrypt(nextval('sequence_name')),
    ...
);
```
> If we ban a name, then a user deletes and recreates their account, we want to keep the username banned. Seems like this would delete the entry with ta_users and so a banned username could be defeated by recreating an account.

AFAIK there is no way to delete your own account and even if there was a way, how would we know that the new account isn't someone who did randomly pick the same name as someone else?
The updating cascade however seems pretty useful to me. If a user renames his account, the ban is instantly applied to the new username instead.

**Comment by RoiEXLab** [comment]
Ok @DanVanAtta Stopping for today.
Summing up my steps for tomorrow:
 - Split the PR at least into 2 or 3 PRs (Formatting, password, general DB improvements/refactoring + migration scripts)
 - Make the scheme file all lowercase again
 - Add lots of comments + documentation + future plans
 - read the conversation again in case I missed something...

Please feel free to tell me, if you dislike some of the changes I'm planning to make

File: config/lobby/db/001_create_tables (hunk 6 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Sounds good, as long as there is no question about everything being UTC : )

File: config/lobby/db/001_create_tables (hunk 7 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: Thanks, there is quite a bit going on. We need to be sure there is very thorough testing, splitting things up will help ensure everything gets its due course.

File: config/lobby/db/001_create_tables (hunk 9 above)
Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: I suggest punting on this, we really don't need to solve this exact problem now, it's not related to passwords, and there is a direction we want to go with DB to support game challenges and some player tracking. Right before that, dropping parts and/or simplifying the schema would be a good stepping stone. 

In the meantime this quite a lot to take in with the context of bcrypt hashing. 

> The updating cascade however seems pretty useful to me. If a user renames his account, the ban is instantly applied to the new username instead.

That is not the intent of the feature, that really changes things. The idea is so that offensive user names would be blocked, it's not meant to track specific user accounts. It's trivial to create new user accounts.

**Comment by DanVanAtta** [comment]
Thanks for bearing with me, that is a pretty good list. For the bcrypt password stuff I think most important is to review the migration plan, we need to keep it simple IMO and we have some options in how we release lobby and client updates.

We are missing some DB infrastructure pieces, and I was a bit confused on it initially. The 001 file we should not modify, a new 002 file is what we would run next. We don't need liquibase or other tool to do that, so we can proceed there.

The other key to all this is testing. I would expect most of the interesting paths to be covered with automated tests. Beyond that, each update presented here needs a lot of testing (which includes some manual testing while developing)

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff I will fix the issues in the next hour or so, there's no need to review until then.

**Comment by RoiEXLab** [comment]
@ssoloff I will add al the alter commands to a 002 file, any suggestions on how to integrate this file into our workflow?

File: config/lobby/db/001_create_tables [hunk 26]
```diff
@@ -1,94 +1,56 @@
...
 );
-
-
 alter table banned_macs owner to postgres;
 
 
 create table banned_usernames (
-    username character varying(40) not null,
-    ban_till timestamp without time zone
+    username character varying(40) not null primary key references ta_users on delete cascade on update cascade,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: @DanVanAtta If this table is for banning usernames, not related to users, the timestamp would be redundant.
The reference ensures a ban is kept even when renaming

File: config/lobby/db/001_create_tables [hunk 27]
```diff
@@ -1,94 +1,42 @@
...
 );
-
-
 alter table banned_macs owner to postgres;
 
 
 create table banned_usernames (
-    username character varying(40) not null,
-    ban_till timestamp without time zone
+    username character varying(40) not null primary key, -- references ta_users on delete cascade on update cascade,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: @DanVanAtta Nevermind. The code does allow this described behaviour, moving into a comment

File: src/main/java/games/strategy/engine/lobby/server/db/UserDao.java (hunk 24 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/UserDao.java]: I disagree. While 'User' and 'Name' can indeed be written separately, they do not make sense in this order.
'HashedPassword' however would make sense written separately IMO, but that's just me

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java (hunk 23 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: We are not printing the hashed password, we are just printing *********** in the length of the hashed password (this helped me fixing some integTests)

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java (hunk 22 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: This way the line was <=120 chars long

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff 
This PR now focuses on structural changes of the DB, no functional changes.
Reviews are now welcome, preferably from the start, as a lot of content was moved to the other PRs

File: config/lobby/db/001_create_tables [hunk 28]
```diff
@@ -1,94 +1,42 @@
-create table bad_words (
-    word character varying(40) not null
+create table ta_users (
+    username character varying(40) not null primary key,
+    password character varying(60) not null,
+    email character varying(254) not null,
```
Comment (RoiEXLab) [inline config/lobby/db/001_create_tables]: Future notice:
I really think emails should be unique.

File: config/lobby/db/001_create_tables [hunk 29]
```diff
@@ -1,94 +1,42 @@
-create table bad_words (
-    word character varying(40) not null
+create table ta_users (
```
Comment (ssoloff) [inline config/lobby/db/001_create_tables]: I'm still pretty sure we shouldn't be modifying this file _at all_ (other than perhaps adding comments).  Ideally, this file represents the current state of the production database (and, if that's not the case, we either have to modify this file to match production or manually modify production to match this file, as @DanVanAtta did with the `password` column type change a few days ago).  This file will never be applied to the production database again, so the changes here will not be picked up.

Any changes from this PR should be completely captured in the `002_*` file below.

File: config/lobby/db/002_update_tables [hunk 30]
```diff
@@ -0,0 +1,25 @@
+alter table ta_users alter column email type varchar(254);
```
Comment (ssoloff) [inline config/lobby/db/002_update_tables]: ##### File name

Is there a short phrase that describes the changes encapsulated in this PR?  "Update tables" is kind of generic.  If we stuck with that, I could see every script from now on being called `003_update_tables`, `004_update_tables`, etc. :smile:

For example, if this PR was focused on just increasing the `email` column length, it could be `002_increase_email_length`.  Obviously, there's a lot of changes going on in this PR, so I don't really have any good suggestions right now.  Referencing the PR number is a possibility, but that seems like punting.  However, it has the advantage that a large number of changes can be captured in a short bit of text, although it forces the dev to have to lookup the PR to know what the gist of the changes are.

##### Transaction

All of this code should be run within a transaction.

The first line in the file should be [`BEGIN;`](https://www.postgresql.org/docs/9.5/static/sql-begin.html) or [`START TRANSACTION;`](https://www.postgresql.org/docs/9.5/static/sql-start-transaction.html) I'm not sure which is idiomatic Postgres, but it looks like `BEGIN` is a Postgres extension, while `START TRANSACTION` is standard SQL, so the latter may be preferable.

The last line in the file should be [`COMMIT;`](https://www.postgresql.org/docs/9.5/static/sql-commit.html).

Also, we should ensure that any error in between the first and last lines triggers psql to stop running further commands so we get an implicit `ROLLBACK`.  I'm not familiar with how this is done in Postgres, but in Oracle and MS-SQL, there are global variables you can check for the "error status" of the previously executed command.  I found [this post](http://blog.nordeus.com/dev-ops/psql-exit-on-first-error.htm) which may be a good starting point for us (setting a switch on the command line seems to be preferable to adding psql commands to the script).  You will probably have to force an error during your testing to ensure the script exits correctly and leaves the database unchanged.  Whatever you do here will most likely become our template for error handling in future scripts.

File: config/lobby/db/002_update_tables [hunk 31]
```diff
@@ -0,0 +1,25 @@
...
+alter table ta_users alter column joined type timestamptz;
+alter table ta_users alter column joined set default current_timestamp;
+alter table ta_users alter column lastlogin type timestamptz;
+alter table ta_users alter column lastlogin set default current_timestamp;
+alter table ta_users alter column admin type boolean using case when admin=0 then false else true end;
+alter table ta_users alter column admin set default false;
```
Comment (ssoloff) [inline config/lobby/db/002_update_tables]: I believe all the `ALTER TABLE` commands applied to a single table can be combined into a single statement by separating the actions with commas.  For example (untested):

```sql
alter table ta_users
  alter column email type varchar(254),
  alter column joined type timestamptz,
  alter column joined set default current_timestamp,
  alter column lastlogin type timestamptz,
  alter column lastlogin set default current_timestamp,
  alter column admin type boolean using case when admin=0 then false else true end,
  alter column admin set default false;
```

See the [Postgres docs](https://www.postgresql.org/docs/9.5/static/sql-altertable.html) for examples.

File: src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java [hunk 32]
```diff
@@ -6,27 +6,20 @@
...
  */
 public class BadWordController {
-  private static final Logger logger = Logger.getLogger(BadWordController.class.getName());
-
   public void addBadWord(final String word) {
     try (final Connection con = Database.getPostgresConnection();
-        final PreparedStatement ps = con.prepareStatement("insert into bad_words (word) values (?)")) {
+        // If the word already is present we don't need to add it twice.
+        final PreparedStatement ps =
+            con.prepareStatement("insert into bad_words (word) values (?) on conflict do nothing")) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java]: A couple of integration tests (one for the happy path and one for the duplicate primary key) for each of these _Table Data Gateway_ classes (e.g. `BadWordController`, `BannedMacController`, etc.) would probably be a good idea.

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 33]
```diff
@@ -64,16 +65,29 @@ public void updateUser(final DBUser user, final HashedPassword hashedPassword) {
...
       con.commit();
     } catch (final SQLException e) {
-      throw new IllegalStateException(
-          "Error updating name:" + user.getName() + " email: " + user.getEmail() + " pwd: " + hashedPassword.mask(), e);
+      throw new IllegalStateException(String.format("Error updating name: %s email: %s pwd: %s",
+          user.getName(), user.getEmail(), hashedPassword.mask()), e);
+    }
+  }
+
+  public void makeAdmin(final DBUser user, final boolean admin) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: `DBUser` already carries a role indicating if the user is an admin or not.  Couldn't we just reuse that instead of adding the extra boolean?

Also, this public method is missing a Javadoc.

**Comment by ssoloff** [comment]
@RoiEXLab 

> I will add all the alter commands to a 002 file, any suggestions on how to integrate this file into our workflow?

The Travis build and the Docker lobby-db-dev image will automatically pick up any file you add to the `config/lobby/db` folder in sorted order (the Travis script does this for sure; I haven't verified if the Docker image does this, but it's easily fixed if not).

For production, the current process seems to be to run these scripts manually until an automated solution like Liquibase is integrated.  Assuming the state of the production database currently matches the `001` file, then the `002` file simply needs to be run through psql against the `ta_users` database:

```
$ psql -h localhost -U postgres -d ta_users < 002_update_tables
```

That process is then repeated in the future for `003_*`, `004_*`, etc.

File: config/lobby/db/001_create_tables (hunk 29 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: I really hope we come up with an automated solution for this.
I'm really not happy with the way we handle changes in the database structure.
I dislike the idea of having one "original" File which is modified by subsequent scripts, this makes reverse engineering really hard, because you can't immediately spot how the database structure is in it's current state:
Is this table still being used, or is it removed in one of the scripts?
Is this datatype final, or do we change it somewhere?
Are there any further restrictions on the content of this column or are checks being removed?
Does this column even exist in the final schema?

All of this causes confusion, which is clearly not the goal here.
But I see your points, and agree that having incremental scripts makes the testing more "real" although I can assure you I tested my altering scripts multiple times against the database scheme of our production DB (a quick sql dump of the scheme makes stuff really easy).
While doing so I noticed another problem with having an original script: TripleA doesn't has the ability to IP-Ban people for a long time now, nevertheless the production postgresdb had a banned_ips and a muted_ips table, which were not used when postgres was introduced. (Tha's why I added the DROP command).

I'd suggest leaving the scripts here as-is, and do the upgrading half-manually, or if anyone wants to integrate liquibase into our workflow I can wait and modify this PR to work with it.

Comment (ssoloff) [reply config/lobby/db/001_create_tables]: > I dislike the idea of having one "original" File which is modified by subsequent scripts

Thoughtworks as a pretty good [article](https://martinfowler.com/articles/evodb.html) on the philosophy behind this technique, specifically with a [section](https://martinfowler.com/articles/evodb.html#AllDatabaseChangesAreMigrations) related to the topic of migrations.

> this makes reverse engineering really hard, because you can't immediately spot how the database structure is in it's current state

Not too hard.  You can get a snapshot of the actual schema by just applying the scripts to a pristine database and then dumping the schema of each table.  This [SO answer](https://stackoverflow.com/a/37571254/3900879) provides some inspiration for how to do that from the shell for a MySQL database.  Using the psql equivalents for `SHOW TABLES` (`\dt`) and `DESCRIBE TABLE` (`\d`) should be straightforward.

Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: > I dislike the idea of having one "original" File which is modified by subsequent scripts, this makes reverse engineering really hard, because you can't immediately spot how the database structure is in it's current state:

If you modify one file, then you also do not know it's current state. Were the modification runs? How many modifications have been run and which ones were applied? Does the file just track the DB state, if so what would keep it in sync if anything?

> I really hope we come up with an automated solution for this.

Liquibase is pretty much a tool to do this exactly :)
https://github.com/triplea-game/triplea/issues/2356

> Is this table still being used, or is it removed in one of the scripts?

Often a good question, but if you have one file, then how do you go from DB in state A to state B?  If things get very complex with the DB patches, a 'snapshot' concept can be introduced. Basically you take a snapshot of the schema and data, and re-init the DB patches from that location. So at *that* time you would for example recreate the '001' file and then blow away any other patches since they are already included.

> TripleA doesn't has the ability to IP-Ban people for a long time now, nevertheless the production postgresdb had a banned_ips and a muted_ips table

Wait, TripleA does.. As a moderator in lobby you can right click to ban by IP, right? It's not the most useful of features in its current form, but it is there to my knowledge. 

> I'd suggest leaving the scripts here as-is, and do the upgrading half-manually, or if anyone wants to integrate liquibase into our workflow I can wait and modify this PR to work with it

I would disagree here. I do not want to update the prod DB manually, and I do not want anyone else to do that either. I see no reason we can't directly fall into a best practice process here. This simply means leaving 001 unaltered. Currently 001 does reflect the live DB state, if we run integration tests in travis we are simulating production. As soon as we merge this, we no longer get those benefits.

**Comment by DanVanAtta** [comment]
> Until we have something like Liquibase, we should keep track of the latest script applied in production somehow (e.g. a text file in Git with the latest version that was applied). I

I considered this briefly. Such a file would be necessary to help automate the script runs. Really though that data should come from DB, which is where liquibase steps in. I think we will get on liquibase pretty soon.

File: config/lobby/db/001_create_tables (hunk 29 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: > Wait, TripleA does.. As a moderator in lobby you can right click to ban by IP, right? It's not the most useful of features in its current form, but it is there to my knowledge.

@DanVanAtta Not anymore it seems, I just checked. You removed the controller classes yourself in fe55b9888317175398e698a70cef9a2f15f108a3 ^^
The RMI code still exists though, removing it would introduce incopatible changes anyways

Comment (DanVanAtta) [reply config/lobby/db/001_create_tables]: heh, indeed, hurray for commit comments!  :)
The backward incompatible is not desired just yet unless we are really ready to make that leap, good consideration @RoiEXLab . 
I would leave as is for now, we need to clean stuff up pretty big time and figure out an effective way to do moderator controls.. Looks like mac banning is not effective either (if the mac is coming from the client code and not network, then it's even more trivial to hack).

File: config/lobby/db/002_update_tables (hunk 30 above)
Comment (RoiEXLab) [reply config/lobby/db/002_update_tables]: @ssoloff Keeping this filename, as this PR does a lot of "smaller improvements" and I really don't want to fiddle around with the git history, changed the filename o n the password PR though as it was just redoing the latest commit and made a lot more sense there.

Comment (RoiEXLab) [reply config/lobby/db/002_update_tables]: @ssoloff I believe the STOP_ON_ERROR setting should be applied in the travis file and the server config itself, not in the script.

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff I will add integration tests tomorrow, but probably not change any of the "main code". Feel free to review my current changes if yoou have the time.

File: config/lobby/db/002_update_tables (hunk 30 above)
Comment (ssoloff) [reply config/lobby/db/002_update_tables]: @RoiEXLab Agreed.  But we should make sure that it has the desired effect during testing instead of waiting to find out it doesn't work as we expected in production. 😄

**Comment by DanVanAtta** [comment]
@RoiEXLab pls be careful with the integration tests, they should be only for the boundary that checks that the DB controller executes the given queries as intended. Everything above that should be a unit test so you can test each module in sequence. When I mentioned missing test coverage, I actually meant 100% unit tests, I'm not terribly concerned about the integration test case here that the SQL works as expected.

File: src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java (hunk 32 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java]: @ssoloff Would work in this case, but the other classes have some logic in them wich prevents the SQL from being executed if the entry is already there,

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java [hunk 34]
```diff
@@ -34,30 +27,21 @@ public void addBannedMac(final String mac, final Instant banTill) {
     if (isMacBanned(mac).getFirst()) {
       removeBannedMac(mac);
     }
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: @ssoloff Here for example: If the MAC is already present it will be removed instead.
Possible solutions would be to either pass an Instant in the past to remove the mac, or just use Instant.MAX_VALUE instead of null for forever

Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: However this would introduce breaking changes as the parameters are sent over RMI

Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: Nevermind, there's no return statement which I originally assumed.
Writing tests reveals what methods are actually doing 😅

**Comment by RoiEXLab** [comment]
Sorry @DanVanAtta this PR almost exclusively covers DB related code, adding "normal Unit tests" is practically impossible, I will try adding unit tests for the password PR though.
Adding integration tests revealed a couple of issues with the mute code: If a player was muted forever, the code would throw a NullPointerException whenever trying to unmute them or to adjust the mute time.
Haven't tested this with the current database, but should be fixed now anyways.

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff This PR is now ready for a full review!

File: src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java (hunk 32 above)
Comment (ssoloff) [reply src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java]: Yeah, we need to consider modifying our DB integration tests to run within transactions that are rolled back at the end of each test so subsequent tests aren't affected by previous state.  They are very brittle at the moment for devs.  Every once in a while I have to blow away my DB to work around this kind of problem.  It's not too hard with a Docker container, but it still smells. :smile:

Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/BadWordController.java]: I added integration test for the other classes, once I figured I could remove the logic.
Agreed, it's really not optimal, but recreating the db is not that hard even without using docker.

File: config/lobby/db/001_create_tables [hunk 35]
```diff
@@ -1,94 +1,50 @@
 create table bad_words (
-    word character varying(40) not null
+    word character varying(40) not null primary key
```
Comment (ssoloff) [inline config/lobby/db/001_create_tables]: Shouldn't all changes to this file be reverted?

File: src/integ_test/java/games/strategy/engine/lobby/server/db/BadWordControllerTest.java [hunk 36]
```diff
@@ -10,12 +11,23 @@
...
     final BadWordController controller = new BadWordController();
     final String word = Util.createUniqueTimeStamp();
     controller.addBadWord(word);
     assertTrue(controller.list().contains(word));
     controller.removeBannedWord(word);
     assertFalse(controller.list().contains(word));
   }
+
+  @Test
+  public void testDuplicateBadWord() {
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/BadWordControllerTest.java]: :+1: Nice work on all the new integration tests.  Very readable.

File: src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java [hunk 37]
```diff
@@ -0,0 +1,72 @@
...
+  @Test
+  public void testBanMac() {
+    final Instant banUntil = Instant.now().plusSeconds(2L);
+    final String hashedMac = banMac(banUntil);
+    final Tuple<Boolean, Timestamp> macDetails = controller.isMacBanned(hashedMac);
+    assertTrue(macDetails.getFirst());
+    assertEquals(banUntil, macDetails.getSecond().toInstant());
+    while (banUntil.isAfter(Instant.now())) {
+      ThreadUtil.sleep(100);
+    }
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java]: An improvement we can look at in a future PR (or here if you're so inclined :smile:) is to avoid the dependency on wall time in these tests.  Not only do we have several tests that take 2+ seconds to run, but they still have a race condition; if the build environment were to be running dead slow for some reason, they might fail.

It looks like the problem (in this case) is that the `BannedMacController#isMacBanned()` method depends on `Instant#now()`.  We could extract a package-private overload of `isMacBanned()` that accepted an additional `Instant` parameter representing "now" so the tests could provide that value and run at full speed without having to wait for a certain amount of time to pass.  For example:

```java
public class BannedMacController {
  // . . .

  public Tuple<Boolean, Timestamp> isMacBanned(final String mac) {
    return isMacBanned(mac, Instant.now());
  }

  @VisibleForTesting
  Tuple<Boolean, Timestamp> isMacBanned(final String mac, final Instant now) {
    // same as existing implementation except that Instant.now() replaced with parameter "now"
  }
}
```

A similar change could be made for the other controllers that also depend on `Instant#now()`.

File: src/integ_test/java/games/strategy/engine/lobby/server/db/EmailLimitTest.java [hunk 38]
```diff
@@ -0,0 +1,61 @@
...
+  public void testAllowsMaximumLentgh() {
+    createAccountWithEmail(getStringWithLength(60) + "@" + getStringWithLength(193));
+  }
+
+  @Test
+  public void testAllowsMaximumLocalLength() {
+    createAccountWithEmail(getStringWithLength(64) + "@" + getStringWithLength(189));
+  }
+
+  private String getStringWithLength(final int length) {
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/EmailLimitTest.java]: Nit: This method can be `static`.

File: src/integ_test/java/games/strategy/engine/lobby/server/db/EmailLimitTest.java [hunk 39]
```diff
@@ -0,0 +1,61 @@
...
+    return Strings.padStart(Util.createUniqueTimeStamp(), length, 'a');
+  }
+
+  private void createAccountWithEmail(final String email) {
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/EmailLimitTest.java]: Nit: This method can be `static`, and there's some variables missing `final`.

File: src/main/java/games/strategy/engine/lobby/server/db/UserController.java [hunk 40]
```diff
@@ -64,16 +65,34 @@ public void updateUser(final DBUser user, final HashedPassword hashedPassword) {
...
+          user.getName(), user.getEmail(), hashedPassword.mask()), e);
+    }
+  }
+
+  /**
+   * A method similar to update user, used by tests only.
+   * Does only affect the admin state of the given user.
+   * The DB is updated with user.isAdmin()
+   */
+  public void makeAdmin(final DBUser user) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/db/UserController.java]: Since this method is only used for testing, can you please add a `@VisibleForTesting` annotation here?

File: config/lobby/db/001_create_tables (hunk 35 above)
Comment (RoiEXLab) [reply config/lobby/db/001_create_tables]: We agreed to not change the schema, which is still the same.
I just moved the altering statements into the create statements, so it's just some readability clean-up

File: src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java (hunk 37 above)
Comment (RoiEXLab) [reply src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java]: Agreed that depending on execution time is not a good idea, however I have a better idea, might adress in this PR if it works out as expected.

Comment (RoiEXLab) [reply src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java]: Didn't work out as expected...
Wil adress in a future PR

**Comment by RoiEXLab** [comment]
@ssoloff I found a good solution for the integration tests, which avoid depending on execution time, and avoid having to overload a method for testing.
I couldn't help myself, I needed to make them part of this PR, and I went even further and added a check constraint for timestamps in the SQL as well. (You can't insert timestamps in the past now.)

**Comment by RoiEXLab** [comment]
@ssoloff Do not merge this PR yet, I noticed a regression

**Comment by RoiEXLab** [comment]
@ssoloff I fixed the regression...

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java [hunk 41]
```diff
@@ -13,51 +13,36 @@
...
-      ps.setTimestamp(2, banTillTs);
-      ps.execute();
-      con.commit();
-    } catch (final SQLException sqle) {
-      if (sqle.getErrorCode() == 30000) {
-        // this is ok
-        // the mac is banned as expected
-        logger.info("Tried to create duplicate banned mac:" + mac + " error:" + sqle.getMessage());
-        return;
+    if (banTill == null || banTill.isAfter(now().plusSeconds(10L))) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: I believe this check appears in all subclasses of `TimedController`.  Would it make sense to extract it to a new method in the base class?

What's the reasoning behind the magic 10 second delay?  Is it simply to avoid modifying the database for a "short-lived" ban/mute?  Do I need to know that when writing integration tests?

File: src/main/java/games/strategy/engine/lobby/server/db/TimedController.java [hunk 42]
```diff
@@ -0,0 +1,13 @@
+package games.strategy.engine.lobby.server.db;
+
+import java.time.Instant;
+
+/**
+ * This class allows integration Tests to override the "now time".
+ * This enables us to make Tests execution-time-independent which is a good thing.
+ */
+abstract class TimedController {
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/server/db/TimedController.java]: Not suggesting you change this now, but another possibility is to use the _Strategy_ pattern instead of inheritance or additional method overloads (although a _Strategy_ would require an additional constructor):

```java
public interface Clock {
  Instant now();
}

public class SystemClock implements Clock {
  @Override
  public Instant now() {
    return Instant.now();
  }
}

public class BannedMacController {
  private final Clock clock;

  public BannedMacController() {
    this(new SystemClock());
  }

  @VisibleForTesting
  BannedMacController(final Clock clock) {
    this.clock = clock;
  }

  // . . .
}
```

Then each test fixture could pass a mock `Clock` to the controller:

```java
public class BannedMacControllerTest {
  @Mock
  private Clock clock;

  @InjectMocks
  private BannedMacController controller;

  // . . .
}
```

I can easily see `Clock` being required outside this package because we have other tests that depend on wall time.  Maybe when we hit the next such test, that will be the appropriate time to extract such an interface.

File: src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java [hunk 43]
```diff
@@ -0,0 +1,79 @@
...
+    final String username = muteUsername(null);
+    assertTrue(controller.isMacMuted(username));
+    assertEquals(Long.MAX_VALUE, controller.getMacUnmuteTime(username));
+    final Instant muteUntill = Instant.now().plusSeconds(100L);
+    controller.addMutedMac(username, muteUntill);
+    assertTrue(controller.isMacMuted(username));
+    assertEquals(muteUntill, Instant.ofEpochMilli(controller.getMacUnmuteTime(username)));
+  }
+
+  private String muteUsername(final Instant length) {
```
[the remark this answers is not in the document]
Comment (RoiEXLab) [reply src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java]: Problem then would be the uniqueness of the values.
You mentioned this earlier, the test need some sort of rollback

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java (hunk 41 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: It's thought to be some sort of a maximum execution time.
In case someone is banned 2 ms in the future, it will be the past until the statement is executed, and therefore the DB will raise an error.
The engine doesn't allow for such short-lived bans, so this is just to be sure we don't run into any issues.

Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: Extracting it to another method would probably not be very useful. 
The check is a one-liner, so we won't improve readability by a lot...

File: src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java (hunk 43 above)
[the remark this answers is not in the document]
Comment (ssoloff) [reply src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java]: In this case, `hashedMac` is an instance field.  Since JUnit creates a new instance of the test class for each test method, the field initializer will run once per test method and generate a unique value per test method.  That should be equivalent to what you had before, right?  Unless there was a case I didn't see where one of the helper methods was called multiple times in a single test method.

[the remark this answers is not in the document]
Comment (RoiEXLab) [reply src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java]: Of course! 
Should've thought about that, I did rely on that when mocking the controller already ^^

File: src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java (hunk 41 above)
Comment (ssoloff) [reply src/main/java/games/strategy/engine/lobby/server/db/BannedMacController.java]: > In case someone is banned 2 ms in the future, it will be the past until the statement is executed, and therefore the DB will raise an error.

Yeah, probably a minor issue, but those checks in the schema might end up being an over-constraint.  And the use of the Postgres `now()` function is another dependency on wall time.  Not sure how sensitive they'll be to system clock drift between different machines (e.g. when testing on Windows, my Postgres DB runs in a VM separate from where my client and lobby run).

**Comment by RoiEXLab** [comment]
@ssoloff Updated!

File: src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java [hunk 44]
```diff
@@ -0,0 +1,82 @@
...
+    assertNull(macDetails.getSecond());
+  }
+
+  @Test
+  public void testBanMacUpdate() {
+    banMacForSeconds(Long.MAX_VALUE);
+    final Tuple<Boolean, Timestamp> macDetails = controller.isMacBanned(hashedMac);
+    assertTrue(macDetails.getFirst());
+    assertNull(macDetails.getSecond());
+    final Instant banUntill = Instant.now().plusSeconds(100L);
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/BannedMacControllerTest.java]: `Untill` -> `Until`

File: src/integ_test/java/games/strategy/engine/lobby/server/db/BannedUsernameControllerTest.java [hunk 45]
```diff
@@ -0,0 +1,81 @@
...
+    assertNull(usernameDetails.getSecond());
+  }
+
+  @Test
+  public void testBanUsernameUpdate() {
+    banUsername(Long.MAX_VALUE);
+    final Tuple<Boolean, Timestamp> usernameDetails = controller.isUsernameBanned(username);
+    assertTrue(usernameDetails.getFirst());
+    assertNull(usernameDetails.getSecond());
+    final Instant banUntill = Instant.now().plusSeconds(100L);
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/BannedUsernameControllerTest.java]: `Untill` -> `Until`

File: src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java [hunk 46]
```diff
@@ -0,0 +1,68 @@
...
+    muteMac(-10L);
+    assertFalse(controller.isMacMuted(hashedMac));
+  }
+
+  @Test
+  public void testMuteMacUpdate() {
+    muteMac(Long.MAX_VALUE);
+    assertTrue(controller.isMacMuted(hashedMac));
+    assertEquals(Long.MAX_VALUE, controller.getMacUnmuteTime(hashedMac));
+    final Instant muteUntill = Instant.now().plusSeconds(100L);
```
Comment (ssoloff) [inline src/integ_test/java/games/strategy/engine/lobby/server/db/MutedMacControllerTest.java]: `Untill` -> `Until`

**Comment by RoiEXLab** [comment]
@DanVanAtta I'm going to self merge in 24 hours unless you have any objections until then, so I can continue to work on #2358

**Comment by RoiEXLab** [comment]
@DanVanAtta Merging now as discussed earlier.

**Comment by DanVanAtta** [comment]
> Sorry @DanVanAtta this PR almost exclusively covers DB related code, adding "normal Unit tests" is practically impossible, I will try adding unit tests for the password PR though.

Integration tests should exist ideally at the boundary of a system where we interface between DB and code. So any integration tests really should just to be sure that a given statement is executed and has expected results. Any logic built on top of that should mock the DB layer and can be unit tested. Check out this video for a really good talk on that technique and how to avoid the integration test trap: https://www.youtube.com/watch?v=VDfX44fZoMc

**Comment by ssoloff** [comment]
@RoiEXLab While reading the Postgres docs, I learned that `timestamp` columns support the concept of [infinity](https://www.postgresql.org/docs/9.5/static/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE).  Using `infinity` instead of `NULL` would allow us to simplify some of the code in the ban/mute controllers related to "forever" bans/mutes.

Just something to keep in mind the next time we're doing feature work in this area.
