### PR TITLE
Fix this thing aka RouteDrawer again...

### LINKED ISSUE #1056: Arrow drawing bug- unnecessary horizontal line being drawn
I installed “triplea_windows-x64_1.9.0.0.2728.exe”.

I don’t have any other versions installed at the moment, so this version is where can see the bug, but I don’t know if it is an older bug. It is also present and can be reproduced in the tutorial map.

The short version:
If a units moves from one place to another, generating an arrorw, and both ends of the arrow can be displayed inside the viewable area, then everything is OK.

But if one of the ends of the arrow is outside the viewable area in the west/left direction, then the end of the arrow in that direction is moved to a far-right/far-east destination.

It seems that it does not matter if it is the pointy or round end of the arrow that gets hidden from view, the error is the same.

I made a screen recording of the bug to supplement these pictures. (8 MB, MP4)
Showing is so much easier then telling :-)
https://dl.dropboxusercontent.com/u/91867373/ArrowBug.mp4

Before the left side of arrow is hidden, all is good:
bug1
After hiding the left side, the arrow bug is seen:
bug2a

### PR DESCRIPTION
**Pull request by RoiEXLab**
Hopefully forever!
@DanVanAtta I was too lazy to undo all the changes, so I created a fix!
I removed a couple of usages of the normalizePoint method!
The only possible downside of this could be, that maybe when scrolling to far away from a route (when watching history the route may become invisible if this ever happens we need to simply increase the mirroring radius from 2 -> 9 screens to 3 -> 16 screens which means less performance for the user)

Based on pre #1199 

If you didn't guess already this fixes #1056

---
This change is [Reviewable](https://reviewable.io/reviews/triplea-game/triplea/1231)

### CODE REVIEW

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 1]
```diff
@@ -190,6 +244,7 @@ private int getAlternativePointArrayCount() {
         result.add(new Line2D.Double(points[0], points[1]));
       }
     }
+    result.forEach(e -> e = null);
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: Why are all elements being set to null.

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 2]
```diff
@@ -101,21 +160,20 @@ public static Point getPoint(Point2D point) {
...
+          alternativePoints.get(index + 1)[counter] = new Point(point.x, point.y + mapHeight);
         }
         if (isInfiniteX && isInfiniteY) {
-          alternativePoints.get(4)[counter] = new Point(normalizedPoint.x - mapWidth, normalizedPoint.y - mapHeight);
-          alternativePoints.get(5)[counter] = new Point(normalizedPoint.x - mapWidth, normalizedPoint.y + mapHeight);
-          alternativePoints.get(6)[counter] = new Point(normalizedPoint.x + mapWidth, normalizedPoint.y - mapHeight);
-          alternativePoints.get(7)[counter] = new Point(normalizedPoint.x + mapWidth, normalizedPoint.y + mapHeight);
+          alternativePoints.get(4)[counter] = new Point(point.x - mapWidth, point.y - mapHeight);
+          alternativePoints.get(5)[counter] = new Point(point.x - mapWidth, point.y + mapHeight);
+          alternativePoints.get(6)[counter] = new Point(point.x + mapWidth, point.y - mapHeight);
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: What do the indexes represent, how do we know we'll have 6, and what do they represent (please update the code to answer this)

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 1 above)
Comment (RoiEXLab) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: woooops forgot this

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 3]
```diff
@@ -22,60 +22,115 @@
...
-      for (Point p : points) {
-        if ((p.x - minX) > mapPanel.getWidth()) {
-          p.x -= this.gameMapWidth;
+  /**
+   * Algorithm for finding the shortest path for the given Route
+   * 
+   * @param route The joints on the Map
+   * @return A Point array which goes through Map Borders if necessary
+   */
+  public Point[] getTranslatedRoute(Point... route) {
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: Please add a real test for this.. 

The reason I wanted a roll back is so we could be unblocked. I'm not inclined to allow these changes to go through with the best effort rubber stamp that was applied time.

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 4]
```diff
@@ -22,60 +22,115 @@
...
+    List<Point2D> result = new ArrayList<>();
+    result.add(point);
+    if (isInfiniteX && isInfiniteY) {
+      result.addAll(Arrays.asList(
+          new Point2D.Double(point.getX() - mapWidth, point.getY() - mapHeight),
+          new Point2D.Double(point.getX() - mapWidth, point.getY() + mapHeight),
+          new Point2D.Double(point.getX() + mapWidth, point.getY() - mapHeight),
+          new Point2D.Double(point.getX() + mapWidth, point.getY() + mapHeight)));
+    }
+    if (isInfiniteX) {
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: If both isInfiniteX and isInfiniteY are true, this if statement will also be executed. Given the points are added, they look redundant, yet are different. What is the purpose of these points that are being added, and how are we computing the indexes?  It's not clear the reasoning behind these values.

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 5]
```diff
@@ -22,60 +22,115 @@
...
-      if (p.x < minX) {
-        minX = p.x;
+  /**
+   * Returns the Closest Point out of the given Pool
+   * 
+   * @param source the reference Point
+   * @param pool Point2D List with all possible options
+   * @return the closest point in the Pool to the source
+   */
+  private Point getClosestPoint(Point source, List<Point2D> pool) {
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: Please add a test for this function. Suggestions for test:
- I would extract this to it's own class, then initialize it as a class member in the constructor. Then you can test it very cleanly, and mock the functionality out so you could then test the rest of the logic easily. I strongly recommend that approach so you can take advantages of mocks.
- Otherwise, increasing the method scope so this method can be called from test .

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 3 above)
Comment (RoiEXLab) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: We want to release 1.9 right? Since everything is working fine now, could we just release 1.9 and create the test cases afterwards? I'll promise you, that I will add test case right after I finished migrating to javafx!

**Comment by RoiEXLab** [comment]
@DanVanAtta It's very hard to explain here how my system works.
Basically we are calculating the shortest route - independent of mapBorders. After that we are cloning this route between 0 to 2 to 8 times (Thats the reason for the weird values) with a map length offset so that we are seeing the same route drawn 1 map length in NW N NE W C E SW S SE if those regions are available (on a only x infinite map we only need W C E).

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 5 above)
Comment (RoiEXLab) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: IMO the method is good enough to test without further decomposing.
`assertEquals(new Point(1,1), getClosestPoint(new Point(0,0), Arrays.asList(new Point(1,1), new Point(2,2), new Point(-2, -2), new Point(2,0))));`
should be enough

**Comment by RoiEXLab** [comment]
@DanVanAtta I understand your good intentions, but my time is limited, and therefore it might take a day or two until I added tests etc.
If thats not fast enough you have 2 options:
Either you merge this without further work and I'll promise you that I'm going to add the tests right after JavFX,
or you use the new github PR feature and implement those tests/documentation on your own.
Don't get me wrong, but I'm currently just happy, that this fix was that easy...

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 4 above)
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: Okay, please note that in the code as a comment so we have that context there. (I prefer when code is self documenting through method and variable names, but the point is to get the contextual information of why this is being done captured in the code one way or another.) I recently had to look at a git history, back track changes to their commit dates, look for PRs on those dates to then find review discussion that actually told me why some code was the way it was.  You can probably guess that was an enjoyable and efficient process ;)

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 5 above)
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: Technically I was recommending extraction, regardless.. Sure, those look like reasonable enough test cases.  I will admit that it does always seem fishy when a method has to be elevated in scope to test it. If also the logic performed in the method is also not terribly important to mock, then yeah, not extracting it is fine  : )

**Comment by DanVanAtta** [comment]
Gave the route drawer a good testing on WaW, and on HexGlobe (has both X + Y wrap) - looked good :+1:

**Comment by DanVanAtta** [comment]
I might be able to give you a hand with retrofitting some unit tests.

In hindsight, making sure everything is pretty solid, tested, and potentially shipped sooner, is paramount. I don't think the mass regression test has been that successful. .. With that said, yeah. Let's get 1.9 out.. @RoiEXLab , I 'll hold you to your word to revisit the route drawer!

**Comment by RoiEXLab** [comment]
@DanVanAtta Thanks! I wont let you down!
