### PR TITLE
Preserve map order when making copy

### LINKED ISSUE #4065: Bot Player Ordering on Setup Screen Incorrect
image

Local game:
image

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Fixes #4065.

h/t @ron-murhammer for finding the root cause.  The fix is to specify the type of map to be created when making the copy.

## Functional Changes

Order is preserved when copying the `playerNamesAndAlliancesInTurnOrder` map.

## Manual Testing Performed

Verified the player order for Classic was correct in a bot game.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/engine/framework/message/PlayerListing.java [hunk 1]
```diff
@@ -81,7 +82,13 @@ public PlayerListing(
             .orElse(Collections.emptyMap())
             .entrySet()
             .stream()
-            .collect(Collectors.toMap(Entry::getKey, e -> Sets.newHashSet(e.getValue())));
+            .collect(Collectors.toMap(
+                Entry::getKey,
+                e -> Sets.newHashSet(e.getValue()),
+                (u, v) -> {
+                  throw new IllegalStateException(String.format("Duplicate key %s", u));
+                },
```
Comment (ssoloff) [inline game-core/src/main/java/games/strategy/engine/framework/message/PlayerListing.java]: This was ripped off from `Collectors#throwingMerger()`.  Too bad it isn't public. :disappointed:
