### PR TITLE
Fix Weird async issues

### LINKED ISSUE #3468: Infinite loading game bar when leaving a remote game
Noticed this while testing the other chat issues.
Steps to reproduce:
Join a bot
Start the game
Press X to close the window or press File > Leave Game
Get a loading dialog that won't close what so ever.

If you press File > Exit Game everything works fine.

### PR DESCRIPTION
**Pull request by RoiEXLab**
Suppose to fix #3468 and a couple of other issues related to asynchronous execution.
Issue 1 gets "fixed" (not 100% sure, but pretty confident), by clearing a System property that launches the game directly when laucnhing, but continues to do so when leaving the game normally.
This caused a background runner to be invoked inside a background runner which likely caused the deadlock (weirdly enough it didn't happen to me)

Issue 2 was an issue that occured, because the code was now correct.
The ClientModel#createClientMessenger function queued the update playerlist trigger in the EDT which was previously executed after the creation of the ClientSetupPanel, because EVERYTHING was done on the EDT which caused it to freeze for short time periods.
When changing everything to async execution, the instantiation of ClientSetupPanel was now after the event was triggered, so the panel didn't show the selected players, until the map was re-selected.

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab I'm a little concerned that these stability issues keep coming up based on moving things off the EDT. I'd like to push out another release but until things are a bit more stable, I hesitate to do so. Any thoughts?

**Comment by RoiEXLab** [comment]
@ron-murhammer Agreed. However when reviewing this PR you'll notice that I try to reduce asynchronous operations when possible.
This PR should hopefully fix the current stability issues we're having to push out a new stable

File: game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java [hunk 1]
```diff
@@ -614,7 +614,7 @@ public void leaveGame() {
       ((ClientGame) game).shutDown();
       // an ugly hack, we need a better
       // way to get the main frame
-      GameRunner.clientLeftGame();
+      new Thread(GameRunner::clientLeftGame).start();
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/triplea/ui/TripleAFrame.java]: This is probably the only exception where things are made more asynchronous than before.
However this makes closing the window smooth, because previously we randomly waited for 100ms on the EDT so everything froze for this interval

File: game-core/src/main/java/games/strategy/engine/framework/GameRunner.java [hunk 2]
```diff
@@ -301,8 +300,10 @@ public static void showMainFrame() {
 
       if (System.getProperty(TRIPLEA_SERVER, "false").equals("true")) {
         setupPanelModel.showServer(mainFrame);
+        System.clearProperty(TRIPLEA_SERVER);
       } else if (System.getProperty(TRIPLEA_CLIENT, "false").equals("true")) {
         setupPanelModel.showClient(mainFrame);
+        System.clearProperty(TRIPLEA_CLIENT);
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/engine/framework/GameRunner.java]: This is the core fix

File: game-core/src/main/java/games/strategy/engine/framework/GameRunner.java [hunk 3]
```diff
@@ -274,20 +287,6 @@ public static void hideMainFrame() {
...
-        try {
-          final String mapName = URLDecoder.decode(
-              event.getURI().toString().substring(ArgParser.TRIPLEA_PROTOCOL.length()), encoding);
-          SwingUtilities.invokeLater(() -> DownloadMapsWindow.showDownloadMapsWindowAndDownload(mapName));
-        } catch (final UnsupportedEncodingException e) {
-          throw new AssertionError(encoding + " is not a supported encoding!", e);
-        }
-      });
-    }
-
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/engine/framework/GameRunner.java]: Just moved the code one level up, so it doesn't get executed multiple times

File: game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java [hunk 4]
```diff
@@ -153,6 +153,7 @@ public ClientModel(final GameSelectorModel gameSelectorModel, final SetupPanelMo
 
   public void setRemoteModelListener(@Nonnull final IRemoteModelListener listener) {
     this.listener = Preconditions.checkNotNull(listener);
+    internalPlayerListingChanged(getServerStartup().getPlayerListing());
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java]: Core fix No.2

File: game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java [hunk 5]
```diff
@@ -379,16 +380,15 @@ public void enablePlayer(final String playerName) {
...
+    gameSelectorModel.clearDataButKeepGameInfo(listing.getGameName(), listing.getGameRound(),
+            listing.getGameVersion().toString());
     synchronized (this) {
       playersToNodes = listing.getPlayerToNodeListing();
       playersEnabledListing = listing.getPlayersEnabledListing();
       playersAllowedToBeDisabled = listing.getPlayersAllowedToBeDisabled();
       playerNamesAndAlliancesInTurnOrder = listing.getPlayerNamesAndAlliancesInTurnOrderLinkedHashMap();
     }
-    SwingUtilities.invokeLater(() -> listener.playerListChanged());
+    listener.playerListChanged();
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java]: Those events shouldn't be triggered on the EDT.
This reduces complexity by leaving this up to the listener implementation

File: game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java [hunk 6]
```diff
@@ -63,7 +63,7 @@ private void internalPlayersChanged() {
       // clients only get to change bot settings
       disableable.clear();
     }
-    playerRows = new ArrayList<>();
+    playerRows.clear();
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/engine/framework/startup/ui/ClientSetupPanel.java]: Instead of reassigning a new ArrayList each time, we can just clear the current one and populate it again

**Comment by ron-murhammer** [comment]
@RoiEXLab Alright. Code looks good. Hard to test so gonna go ahead and merge so we can get it into the pre-release for folks to try out.
