### PR TITLE
Handle trigger attachments that still use deprecated isSuicide

### LINKED ISSUE #6961: TriggerAttachments on removed options cause an exception
### How can the problem be recreated?
Any map that has a TriggerAttachment that changes an option that was removed in 2.0 will throw an exception and the game stops.

Total World War 3.0 is an example.  Its trigger `triggerAttachmentgermanRock2` changes the `isSuicide` option to false.  This trigger always runs before the German non combat move.  All you need to do is buy a rocket as Germany and the next German non combat move will kill the game.

The issue is that `isSuicide` is deprecated and is a write only value.  So it can't get the original value.  And it can't really update it either.

I think 2.x has other options that have been removed, renamed, etc.  These will all cause this same issue.

### Do you have any ideas for an expected fix?
These options need to proxy their calls to the new settings or just ignore the call.

### Attach a Save Game

[isSuicideError.zip](https://github.com/triplea-game/triplea/files/4853122/isSuicideError.zip)

There are a few battles left in the combat phase, but once they are done, the error will occur.

### If playing a prerelease, which version are you using?

Game Version: Latest on master

### If playing a prerelease, does this happen on the latest release?

- [X] yes
- [ ] no

### PR DESCRIPTION
**Pull request by trevan**
This adds `getIsSuicide` back so that the trigger attachments in TWW will still work.

I've also wrapped the exception inside a new exception that has the name of the trigger, the property, and what type of attachment it is on.  This should help in finding and fixing similar issues.

Fixes #6961

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix
[] Other:   

## Testing
Loaded a TWW save that triggered it, verified that the unit attachment had suicide turned off before non-combat and then had it turned back on after non-combat.  And then I let the UI play for several more rounds to see if anything else might happen.

## Release Note

FIX|TWW will no longer crash before Germany's non-combat phase.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/triplea/attachments/TriggerAttachment.java [hunk 1]
```diff
@@ -1508,8 +1508,17 @@ private static void placeUnits(
     final boolean clearFirst = clearFirstNewValue.getFirst();
     final String newValue = clearFirstNewValue.getSecond();
 
-    final boolean isValueTheSame =
-        newValue.equals(propertyAttachment.getRawPropertyString(propertyName));
+    final boolean isValueTheSame;
+    try {
+      isValueTheSame = newValue.equals(propertyAttachment.getRawPropertyString(propertyName));
+    } catch (final UnsupportedOperationException e) {
+      throw new UnsupportedOperationException(
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/triplea/attachments/TriggerAttachment.java:1515]: Codacy found an issue: [New exception is thrown in catch block, original stack trace may be lost](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5782710)

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5782710&bid=18932286)

File: game-core/src/main/java/games/strategy/triplea/attachments/TriggerAttachment.java [hunk 2]
```diff
@@ -1508,8 +1508,18 @@ private static void placeUnits(
...
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/triplea/attachments/TriggerAttachment.java:1515]: The extra debug information here is excellent - much better error handling  :+1:
