### PR TITLE
Fix overflow issues

### LINKED ISSUE #2376: How to handle overflow issue
I discovered an issue with @prastle earlier that day, which seems like a Java bug to me (probably worth reporting, if I knew where).
An ArithmeticException is being thrown when banning someone forever using the MenuBar Toolbox.
The change in https://github.com/triplea-game/triplea/commit/62ede44a596452aca66e9895545c6268a5d3375a#diff-8720367863d7314b908593d8073c7baeR158 introduced it, but did not really cause it.
Although both snippets technically should do the same, they do not, because long is a primitive type.
`requestTimespanSupplication()` returns `Long.MAX_VALUE` if the mod/admin bans somebody forever. when adding this value to `System.currentTimeMillis()`, the long silently overflows resulting in a negative value, which was no problem, because `new Date(long)` does treat longs as unsigned.
The Problem is, that Instant does not.
Because `Instant.toEpochMillis()` throws an ArithmeticException when overflowing we get the observed error, although Date could handle this negative value, e.g. Date could represent the given Instant to `Date.from`.
Therefore `System.out.println(Date.from(Instant.now().plusMillis(Long.MAX_VALUE)));` throws an exception instead of printing a valid date.

The question is how we should tackle this issue. We should be able to workaround this issue by copying the Math from the `Instant.toEpochMilli` method:
```
public long toEpochMilli() {
        if (seconds < 0 && nanos > 0) {
            long millis = Math.multiplyExact(seconds+1, 1000);
            long adjustment = nanos / 1000_000 - 1000;
            return Math.addExact(millis, adjustment);
        } else {
            long millis = Math.multiplyExact(seconds, 1000);
            return Math.addExact(millis, nanos / 1000_000);
        }
    }
```
,replacing Math.multiplyExact with '*' and addExact with '+', so we get
```
public long toEpochMilli() {
        if (seconds < 0 && nanos > 0) {
            long millis = (seconds+1) * 1000;
            long adjustment = nanos / 1000_000 - 1000;
            return millis + adjustment;
        } else {
            long millis = seconds * 1000;
            return millis + (nanos / 1000_000);
        }
    }
```
*BUT* this solutions actually doesn't makes use of the _real_ forever banning. In this case forever is just a point a couple thousand years in the future, not NULL like in the other cases.

TL;DR We basically have 2 options:
1. Workaround this issue
2. Rework class to be consistent with other classes

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fixes #2376
The code is pretty similar to/ heavily inspired by #2122
We should really consider reusing the code in both classes, and use JSpinners for a temporal amount selection as described [here](https://stackoverflow.com/a/10107435)

### CODE REVIEW

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 1]
```diff
@@ -423,4 +428,10 @@ private void addExitMenu(final JMenu parentMenu) {
       parentMenu.add(menuFileExit);
     }
   }
+
+  private static Date toDate(final TemporalAmount amount) {
+    return amount != null
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: The caller of this private method should always know if the parameter is null. If you call this method, you would expect for it to do something, so calling it with a null parameter is very likely to be a bug. Would you mind moving the 'null' handling upstream to the caller @RoiEXLab ?

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 2]
```diff
@@ -298,38 +303,38 @@ private long requestTimespanSupplication() {
             JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, timeUnits.toArray(),
             timeUnits.toArray()[3]);
     if (result < 0) {
-      return -1;
+      return Duration.ofMillis(-1);
     }
     final String selectedTimeUnit = (String) timeUnits.toArray()[result];
     if (selectedTimeUnit.equals("Forever")) {
-      return Long.MAX_VALUE;
+      return null;
```
Comment (DanVanAtta) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: would be excellent to avoid returning null, helps avoid NPE's and null handling. Since this is a private method, we may be able to move the return null logic to the caller. Failing that, a reasonable last resort option would be to return an `Optional<TemporalAmount>` instead of `TemporalAmount`.  In part this then helps the return value from having multiple meanings, empty meaning one specific condition was hit otherwise it is value object with a very different semantic meaning. The semantic meaning of a variable changing based only on its value adds a decent level of complexity, makes it harder to reason about the logic.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 3]
```diff
@@ -298,38 +303,38 @@ private long requestTimespanSupplication() {
             JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, timeUnits.toArray(),
             timeUnits.toArray()[3]);
     if (result < 0) {
-      return -1;
+      return Duration.ofMillis(-1);
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: I think the original author of this code intended -1 to mean "the user canceled the operation."  It was probably a mistake to treat that value as a -1 ms duration to be added to the current time.  At a minimum, the caller of this method probably should have checked for -1 and aborted the ban operation.

With today's code, specifying an instant before the current time will cause any existing ban to be removed.  So, if the admin cancels out of one of the dialogs, it will have the unintended consequence of actually removing any ban currently in place.

This goes back to what we discussed in your other PR about potentially returning an `Optional` from this method.  However, given what @DanVanAtta suggested below, that begs the question of how you represent forever.  If you continue to use `null` (which you could do), you would end up with a return type of `@Nullable Optional<TemporalAmount>`.  That just looks weird and seems very confusing.

I honestly don't know the best way you should represent these three possible value types (abort ban, ban forever, and ban for finite duration).  I'll throw out what I suggested in your other PR, but I'm still not sure it's ideal:

* Use `Optional<TemporalAmount>` as the return type.
* An empty `Optional` indicates the user aborted the ban, and no further action should be taken.
* A non-empty `Optional` indicates the user wants to proceed with the ban; the `Optional` value represents the duration of the ban.
* Use a special `TemporalAmount` value to represent forever.  For example, start by defining an appropriate magic constant (note that the actual duration could be anything because you're going to use reference equality below to test for this value):

```java
private static final TemporalAmount FOREVER = Duration.ofSeconds(Long.MAX_VALUE);
```

Obviously, you'd return this instead of `null` from `requestTimestampSupplication()`:

```java
if (selectedTimeUnit.equals("Forever")) {
  return Optional.of(FOREVER);
}
```

And then test specifically for this magic value **using reference equality** in `toDate()`:

```java
return amount != FOREVER
    ? Date.from(LocalDateTime.ofInstant(Instant.now(), ZoneOffset.UTC).plus(amount).toInstant(ZoneOffset.UTC))
    : null;
```

Note that this solution conflicts with @DanVanAtta's suggestion below:

>  The semantic meaning of a variable changing based only on its value adds a decent level of complexity, makes it harder to reason about the logic.

But I'm hoping naming the "special value" `FOREVER` instead of using `Long.MAX_VALUE` makes it easier to reason about. :smile:

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 4]
```diff
@@ -298,38 +303,38 @@ private long requestTimespanSupplication() {
...
+      case "Day":
+        return Duration.ofDays(result2);
+      case "Week":
+        return Period.ofWeeks((int) result2);
+      case "Month":
+        return Period.ofMonths((int) result2);
+      case "Year":
+        return Period.ofYears((int) result2);
+      default:
+        throw new IllegalArgumentException("Invalid time unit: " + selectedTimeUnit);
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Not sure `IllegalArgumentException` is the most appropriate exception type here.  I used it over in `LobbyFrame` because the value I was switching on was an input parameter to the method.  Here it's all internal to this method.  `AssertionError` might be more appropriate because you are defining all the possible values locally to this method in the `timeUnits` collection.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java (hunk 1 above)
Comment (ssoloff) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: I agree with @DanVanAtta that we should be avoiding `null` when possible.  Just because the database layer defines a `NULL` column value to represent forever doesn't mean the domain model has to use a `null` `TemporalAmount` to do the same.

However, I'm going to assume you're doing this because the `BanUsernameController` and `BanMacController` public APIs use a `null` `Date` to represent forever, and this method is simply acting as an adapter between your internal representation (`@Nullable TemporalAmount`) and the controller APIs (`@Nullable Date`).  Unless we undertake a larger scale refactoring, we're probably stuck with returning `@Nullable Date` from this method to conform to the controller APIs.  But, as suggested above, you might be able to avoid using `@Nullable TemporalAmount` if you use some kind of magic constant or equivalent alternative to represent forever within this class.

Regardless, if you do end up using nullable types in any of the code, would you mind annotating the types with `@Nullable` so that possibility is clear to a future maintainer?

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 5]
```diff
@@ -284,7 +289,7 @@ private void addUnbanMacAddressMenu(final JMenu parentMenu) {
     parentMenu.add(item);
   }
 
-  private long requestTimespanSupplication() {
+  private TemporalAmount requestTimespanSupplication() {
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: This method name has been driving me nuts since I first saw it a couple of months ago.  What does "supplication" even mean in this context?

Can you think of a better name?  I'll suggest `requestBanDuration` or `promptForBanDuration`, but there's probably something better.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java (hunk 3 above)
Comment (DanVanAtta) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Interesting context, in this case I would recommend creating a data object to capture the return data. It would likely have two fields, one an enum to indicate result and a second to indicate the value in case the ban value is in the future.

Comment (RoiEXLab) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: @ssoloff This reminded me of something, there is actually a chrono unit which represents the concept of "forever": https://docs.oracle.com/javase/9/docs/api/java/time/temporal/ChronoUnit.html#FOREVER

Will use that instead!

Comment (RoiEXLab) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Internally it uses Long.MAX_VALUE

**Comment by RoiEXLab** [comment]
@DanVanAtta @ssoloff Updated!

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java (hunk 3 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Actually canceling removed the mac even before I fiddled with the time-code, with the exception, that the a value in the past was inserted into the db which gets removed after the next person with this mac joins
Those old classes are full of bugs...
Is fixed now.

**Comment by RoiEXLab** [comment]
Ok, I  believe this PR is now ready-to-merge.
I plan to have a unified class for all "prompt timespan" operations (this code is duplicated in lots of places), and to improve the general UI to use a JSpinner instead of a normal JTextField, but this will be for a PR after the planned release.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java (hunk 3 above)
Comment (ssoloff) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: :+1: Thanks for the heads-up on `ChronoUnit#FOREVER`.

> Actually canceling removed the mac even before I fiddled with the time-code, with the exception

Yes, it was a legacy bug; definitely not introduced in this PR.  Sorry, if I didn't make that clear.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 6]
```diff
@@ -160,13 +167,15 @@ private void addBanUsernameMenu(final JMenu parentMenu) {
...
       }
-      final Instant expire = Instant.now().plusMillis(requestTimespanSupplication());
+      final Optional<TemporalAmount> duration = promptBanDuration();
       final IModeratorController controller = (IModeratorController) lobbyFrame.getLobbyClient().getMessengers()
           .getRemoteMessenger().getRemote(ModeratorController.getModeratorControllerName());
-      try {
-        controller.banUsername(new Node(name1, InetAddress.getByName("0.0.0.0"), 0), Date.from(expire));
-      } catch (final UnknownHostException ex) {
-        ClientLogger.logQuietly(ex);
+      if (duration.isPresent()) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Using `Optional#ifPresent()` here would be more idiomatic Java 8.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 7]
```diff
@@ -201,14 +210,16 @@ private void addBanMacAddressMenu(final JMenu parentMenu) {
...
-      final Instant expire = Instant.now().plusMillis(requestTimespanSupplication());
+      final Optional<TemporalAmount> duration = promptBanDuration();
       final IModeratorController controller = (IModeratorController) lobbyFrame.getLobbyClient().getMessengers()
           .getRemoteMessenger().getRemote(ModeratorController.getModeratorControllerName());
-      try {
-        controller.banMac(new Node("None (Admin menu originated ban)", InetAddress.getByName("0.0.0.0"), 0), mac,
-            Date.from(expire));
-      } catch (final UnknownHostException ex) {
-        ClientLogger.logQuietly(ex);
+      if (duration.isPresent()) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Using `Optional#ifPresent()` here would be more idiomatic Java 8.

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java [hunk 8]
```diff
@@ -423,4 +434,10 @@ private void addExitMenu(final JMenu parentMenu) {
       parentMenu.add(menuFileExit);
     }
   }
+
+  private static Date toDate(final TemporalAmount amount) {
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Reading through this a second time, I realized that this method is doing more than simply converting a `TemporalAmount` to a `Date`.  `TemporalAmount` represents a duration, while a `Date` is an absolute point in time, so it's really adding the given duration to "now," and then doing the conversion.  That is, this function isn't "pure" in the sense that it has a hidden dependency on global state.  Capturing that in the method name would be helpful.

Is there a better method name here?  `nowPlusDuration()`?  `nowOffsetBy()`?  Those could be a bit too generic in this context.  Maybe something more context-dependent like `getBanExpirationDate()`?  Meh, I hate naming things...

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java (hunk 6 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Good Point, allows us to save a line as well...

File: src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java (hunk 8 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/triplea/ui/menubar/LobbyMenu.java]: Did think about `getBanExpirationDate`, but as this method can not just be exclusively use by ban actions I droppen "Ban" from the name...

**Comment by RoiEXLab** [comment]
@ron-murhammer Tests will be added in a follow-up PR which refactors all of this code and moves it to a dedicated class (similar code is already in use elsewhere.)
@DanVanAtta Merging now, for the same reason: Most of this code will be (re)moved from this class in my follow-up PR, just wanted to fix this "regression" so we can release a new stable.
