### PR TITLE
TripleA protocol handler: Fix urlencoding + quotes on linux (#2286)

### LINKED ISSUE #2286: "triplea:" URLs do not work on Linux/Firefox
### My Operating System:
* Fedora 25 4.11.12-200.fc25.x86_64
* Firefox 55.0.1 (64-bit)

### TripleA version:
1.9.0.0.6358

### Map:
N/A

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
* Install TripleA on Linux with symlinks enabled.
* Use Firefox to navigate to `triplea:world_war_ii_classic`.

### Do you have the exact error text? Please copy/paste if so
TripleA starts and shows the following error after the main menu is displayed:

launch-download-map-error

### Instead of this error, what should have happened?
TripleA should have opened the Download Maps window and either started downloading the map or informed me that it was already installed.

### Any additional information that may help:
Using `ps`, I grabbed the exact command line that was used to start TripleA (I added the line breaks to make this easier to read):

```
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc25.x86_64/jre/bin/java \
  -splash:/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/.install4j/s_8of556.png \
  -Dinstall4j.jvmDir=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.fc25.x86_64/jre \
  -Dexe4j.moduleName=/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/TripleA \
  -Dinstall4j.launcherId=33 \
  -Dinstall4j.swt=false \
  -Di4jv=0 \
  -Di4jv=0 \
  -Di4jv=0 \
  -Di4jv=0 \
  -Di4jv=0 \
  -Xmx1G \
  -Xms1G \
  -Di4j.vpt=true \
  -classpath /home/ssoloff/Downloads/TripleA_1.9.0.0.6358/.install4j/i4jruntime.jar:/home/ssoloff/Downloads/TripleA_1.9.0.0.6358/bin/triplea.jar \
  com.install4j.runtime.launcher.UnixLauncher \
  launch \
  ab9dd710 \
  /home/ssoloff/Downloads/TripleA_1.9.0.0.6358/error.log+  \
  games.strategy.engine.framework.GameRunner \
  'triplea:world_war_ii_classic'
```

You can see that the sole argument to TripleA is single-quoted, and those single-quotes are getting passed to the application rather than being removed by the shell (as evidenced by the error dialog).  Presumably, the way the install4j launcher starts TripleA is using an API that doesn't go through a shell but starts the process directly (e.g. the `system()` vs. `execve()` C API calls).  That would explain why the quotes are not being stripped.

This is probably an install4j issue, but would require further research to verify.  If so, but if it can't be resolved through install4j, a possible workaround is to modify TripleA to strip leading/trailing quotes before processing command line arguments.

I verified that this problem does not occur on Windows.

### PR DESCRIPTION
**Pull request by RoiEXLab**
With some delay: This PR fixes #2286

Small thing I noticed while testing stuff: It seems TripleA is incompatible with java 9, it crashed on start, when I forgot to set the JDK back to java 8

### CODE REVIEW

File: src/main/java/games/strategy/engine/framework/ArgParser.java [hunk 1]
```diff
@@ -18,7 +21,13 @@ public static boolean handleCommandLineArgs(
     if (args.length == 1 && !args[0].contains("=")) {
       // assume a default single arg, convert the format so we can process as normally.
       if (args[0].startsWith(TRIPLEA_PROTOCOL)) {
-        args[0] = GameRunner.TRIPLEA_MAP_DOWNLOAD_PROPERTY + "=" + args[0].substring(TRIPLEA_PROTOCOL.length());
+        final String encoding = StandardCharsets.UTF_8.displayName();
+        try {
+          args[0] = GameRunner.TRIPLEA_MAP_DOWNLOAD_PROPERTY + "="
+              + URLDecoder.decode(args[0].substring(TRIPLEA_PROTOCOL.length()), encoding);
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/framework/ArgParser.java]: When I saw this line, my spider sense went off, and I realized that I misspoke before when I said "URL-encoded"; I should have said "URI-escaped" instead.  There is a subtle difference between the two (namely `application/x-www-form-urlencoded` vs. RFC 3986) that is predominantly manifested in how spaces are encoded (`+` vs. `%20`).

This shouldn't affect the use of `URLDecoder#decode()` in this code, though, as it seems to produce the correct decoded/unescaped value for both types of input (see this [SO question](https://stackoverflow.com/questions/607176/java-equivalent-to-javascripts-encodeuricomponent-that-produces-identical-outpu)).  That is, both `+` and `%20` get correctly decoded into a space.

However, this does have implications in the test case below where we use `URLEncoder` to produce a URI-escaped value.  I'll add a separate comment there describing the specific issue.

Tangentially related, but I went over to the website code to see how this value was being generated.  Here's the link element from the map template:

```html
<a href="triplea:{{ page.mapName | escape | replace: " ", "%20"  }}" class="button">Download with TripleA</a>
```

Seeing that we have to do the extra space replacement after running the map name through the `escape` filter, I'm wondering if it would be more appropriate to use the [`url_escape`](https://help.shopify.com/themes/liquid/filters/string-filters#url_escape) filter instead.  That should produce a properly-escaped URI without the extra replacement.

File: src/main/java/games/strategy/engine/framework/ArgParser.java [hunk 2]
```diff
@@ -18,7 +21,13 @@ public static boolean handleCommandLineArgs(
...
+        } catch (UnsupportedEncodingException e) {
+          throw new IllegalStateException(encoding + " is not a supported encoding!", e);
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/framework/ArgParser.java]: From our earlier discussion of different [types of failure modes](https://github.com/google/guava/wiki/ConditionalFailuresExplained), I would say this falls under the _Impossible Condition_ check.  That is, there is something fundamentally wrong with the JVM if UTF-8 is not supported.  So I would consider throwing `AssertionError` here instead.

Also, a Clean Up will mark the `catch` parameter on the previous line as `final`.

File: src/test/java/games/strategy/engine/framework/ArgParserTest.java [hunk 3]
```diff
@@ -75,6 +78,16 @@ public void singleUrlArgIsAssumedToBeMapDownloadProperty() {
   }
 
   @Test
+  public void singleUrlArgIsUrlDecoded() throws UnsupportedEncodingException {
+    final String propvalue = "Something with spaces and Special chars 🤔";
+    final String testUrl = "triplea:" + URLEncoder.encode(propvalue, StandardCharsets.UTF_8.displayName());
```
Comment (ssoloff) [inline src/test/java/games/strategy/engine/framework/ArgParserTest.java]: As I mentioned in a previous comment, `URLEncoder` encodes for the `application/x-www-form-urlencoded` media type instead of URI escaping per RFC 3986.  That means the encoded `testUrl` does not match what TripleA would actually receive from a browser.  The value of `testUrl` in the test is

```
triplea:Something+with+spaces+and+Special+chars+%F0%9F%A4%94
```

when it should be (generated by running the original string through JavaScript's `encodeURIComponent()` function)

```
triplea:Something%20with%20spaces%20and%20Special%20chars%20%F0%9F%A4%94
```

The code in `ArgParser` happens to work because `URLDecoder` still converts `+` to space.

My recommendation would be to avoid using `URLEncoder` entirely and simply URI escape the string by hand and hard-code it in the test.  That also makes it clearer to a test reader as to what's actually going on (and avoids all the noise caused by the `URLEncoder` charset requirement).  Something like:

```java
  @Test
  public void singleUrlArgIsUrlDecoded() {
    final String testUrl = "triplea:Something%20with%20spaces%20and%20Special%20chars%20%F0%9F%A4%94";
    ArgParser.handleCommandLineArgs(new String[] {testUrl}, new String[] {GameRunner.TRIPLEA_MAP_DOWNLOAD_PROPERTY});
    assertThat("if we pass only one arg prefixed with 'triplea:',"
        + " it should be properly URL-decoded as it's probably coming from a browser",
        System.getProperty(GameRunner.TRIPLEA_MAP_DOWNLOAD_PROPERTY), is("Something with spaces and Special chars 🤔"));
  }
```

File: src/main/java/games/strategy/engine/framework/ArgParser.java (hunk 1 above)
Comment (RoiEXLab) [reply src/main/java/games/strategy/engine/framework/ArgParser.java]: https://github.com/triplea-game/triplea-game.github.io/pull/251

**Comment by RoiEXLab** [comment]
@ssoloff Updated!

File: src/test/java/games/strategy/engine/framework/ArgParserTest.java [hunk 4]
```diff
@@ -75,6 +76,15 @@ public void singleUrlArgIsAssumedToBeMapDownloadProperty() {
   }
 
   @Test
+  public void singleUrlArgIsUrlDecoded() throws UnsupportedEncodingException {
+    final String testUrl = "triplea:Something%20with+spaces%20and%20Special%20chars%20%F0%9F%A4%94";
```
Comment (RoiEXLab) [inline src/test/java/games/strategy/engine/framework/ArgParserTest.java]: I added an + on purpose, because we probably also want to support URIs with + chars instead of spaces

File: src/test/java/games/strategy/engine/framework/ArgParserTest.java [hunk 5]
```diff
@@ -75,6 +76,15 @@ public void singleUrlArgIsAssumedToBeMapDownloadProperty() {
   }
 
   @Test
+  public void singleUrlArgIsUrlDecoded() throws UnsupportedEncodingException {
```
Comment (ssoloff) [inline src/test/java/games/strategy/engine/framework/ArgParserTest.java]: The exception specification is no longer necessary after your most-recent commit.

**Comment by RoiEXLab** [comment]
Removed the throws declaration, merging...
