### PR TITLE
Save the owner of the new units in case another action changes the ownership

### LINKED ISSUE #6439: 2.0.19225: PlayerOwnerChange#perform:55 - IllegalStateException
## User Description
This error happens every time units invade an enemy territory, in there, kills units that turn into another capturable units, attacker wins and everything is captured. There is no problem in regards to gameplay, it works as it should. Territory is captured and the newly spawned capturable unit also. But the error pops up every time. "Expecting another owener" - FrostionAAA

## Log Message
Wrong owner, expectingZombies but got PlayerId named:Humans

## TripleA Version
2.0.19225

## Java Version
11.0.6

## Operating System
Windows 10

## Exception 
java.lang.IllegalStateException: Wrong owner, expectingZombies but got PlayerId named:Humans

## Stack Trace
```
java.lang.IllegalStateException: Wrong owner, expectingZombies but got PlayerId named:Humans
	at games.strategy.engine.data.changefactory.PlayerOwnerChange.perform(PlayerOwnerChange.java:55)
	at games.strategy.engine.data.GameData.performChange(GameData.java:433)
	at games.strategy.engine.history.History.changeAdded(History.java:168)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:170)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:30)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### PR DESCRIPTION
**Pull request by trevan**
Fixes #6439

In Warcraft War Heroes, units are transformed into "loot" that is then captured by the winner.  When the loot is first added to the battle, it is owned by the loser.  This causes a series of change commands:

1. Remove Unit
2. Add Unit
3. Change Unit's Owner

When the AI is playing and the user is spectating, the history also sees these change commands and converts them to its local gameData.

The problem occurs when the steps happen in the following manner:

1. Game - Add Unit
2. Game - Change Unit's Owner
3. History - Add Unit
4. Game - Change Unit's Owner

When 3 runs, it is using the unit that had its owner changed in 2.  So the change owner in 4 throws an error because the owner is different from what it is expecting.

This fix stores the original owner when the unit is added.  So when 3 runs, it can ensure that the unit has the original owner and not the new one.

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix
[] Other:   

## Testing
Loaded a save that had the exception and ensured that the exception didn't happen.  Also checked that save games still loaded.

## Release Note

FIX|PlayerOwnerChange exception in Warcraft War Heroes is fixed

### CODE REVIEW

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5776823&bid=18908659)

**Comment by DanVanAtta** [comment]
Nice work digging into this @trevan  :+1: 

I'll try to review this in detail tomorrow if @RoiEXLab does not get to it sooner.

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5776823&bid=18908659)

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5776823&bid=18908659)

**Comment by trevan** [comment]
The smoke test failed but I don't think this change caused that.

**Comment by prastle** [comment]
Wow! Welcome to the team! @trevan

**Comment by DanVanAtta** [comment]
Perhaps a retry on the smoke-test would be in order (in general), it failed here due to a transient download problem:
```
Downloading https://services.gradle.org/distributions/gradle-6.5-all.zip
..
Exception in thread "main" javax.net.ssl.SSLProtocolException: Connection reset
```

File: game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java [hunk 1]
```diff
@@ -15,19 +20,26 @@
...
 
   AddUnits(final String name, final String type, final Collection<Unit> units) {
-    this.units = new ArrayList<>(units);
+    this.units = units;
+    unitPlayerMap = getUnitPlayerMap(units);
     this.type = type;
     this.name = name;
   }
 
+  private Map<UUID, String> getUnitPlayerMap(final Collection<Unit> units) {
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:39]: nit: 'get' methods usually are just 'getters'. If computation is done a different verb could be easier for future maintainers. Perhaps rewording this to `buildUnitPlayerMap` would help that. WDYT @trevan ?

File: game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java [hunk 2]
```diff
@@ -36,11 +48,36 @@ public Change invert() {
...
     final UnitHolder holder = data.getUnitHolder(name, type);
-    holder.getUnitCollection().addAll(units);
+    final Collection<Unit> unitsWithCorrectOwner = getUnitsWithOwner(data);
+    holder.getUnitCollection().addAll(unitsWithCorrectOwner);
+  }
+
+  private Collection<Unit> getUnitsWithOwner(final GameData data) {
+    final Map<UUID, Unit> uuidToUnits =
+        units.stream().collect(Collectors.toMap(Unit::getId, unit -> unit));
+    return unitPlayerMap.entrySet().stream()
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:58]: If we're iterating over the entry set of the `unitPlayerMap`, why do we need a map for this? Can we not just iterate over the set of units and avoid the map data structure altogether?

File: game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java (hunk 1 above)
Comment (DanVanAtta) [reply game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:39]: This could be a moot comment if it turns out we do not need a map.

File: game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java (hunk 2 above)
Comment (trevan) [reply game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:58]: The original code just iterated over the set of units.  That's the problem.  We need to store the map of unit -> owner outside of the units so that when the owner changes in the unit, it doesn't change the map here.

Comment (DanVanAtta) [reply game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:58]: Cool, I think that probably should be called out to make it clear & obvious. Perhaps a javadoc comment on the map property would do the trick. WDYT?

Comment (trevan) [reply game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java]: I added some documentation and changed the method names.  WDYT?

File: game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java [hunk 3]
```diff
@@ -15,19 +20,31 @@
...
 
   AddUnits(final String name, final String type, final Collection<Unit> units) {
-    this.units = new ArrayList<>(units);
+    this.units = units;
+    unitOwnerMap = buildUnitOwnerMap(units);
     this.type = type;
     this.name = name;
   }
 
+  private Map<UUID, String> buildUnitOwnerMap(final Collection<Unit> units) {
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:44]: side-note / big nit, this method could be static. I think we need to try and see if we can share a config that turns on the static analysis warning that methods can be marked as static.

For me it's really helpful as I watch for private methods being static. If they are, I know they do not interact with the class state. If they are not static, I assume they cannot be static and hence interact with class state.

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5776823&bid=18908659)

File: game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java [hunk 4]
```diff
@@ -36,11 +53,36 @@ public Change invert() {
   @Override
   protected void perform(final GameData data) {
     final UnitHolder holder = data.getUnitHolder(name, type);
-    holder.getUnitCollection().addAll(units);
+    final Collection<Unit> unitsWithCorrectOwner = buildUnitsWithOwner(data);
+    holder.getUnitCollection().addAll(unitsWithCorrectOwner);
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/engine/data/changefactory/AddUnits.java:57]: A test of some sort to verify the right functionality would be a good thing to have. If we change & break this, we'll have the extra safety net. Testing is really good for ensuring correctness, which is a further safety net that would be good to have as well.

**Comment by DanVanAtta** [comment]
Waiting for build to complete, good to merge once that finishes.

**Comment by trevan** [comment]
I kind of feel like this is more of a band-aid vs a true fix.  I bet I could cause this same type of problem by adding a new unit and then changing its hitpoints or any other edit to the unit.

I think the long term fix is to clone the unit when it is added to this change (and other changes).  That way, the original unit can be changed by later changes but the unit in this change object will stay the way it was initially.  Is it it ok to try and implement `Cloneable` on `Unit`?

**Comment by DanVanAtta** [comment]
Would an immutable copy of the unit state work instead of `clone`? AFAIK `clone` has its pit-falls, generally a bit error-prone ot use.

**Comment by DanVanAtta** [comment]
IMO changes should generally contain immutable data. If we maintained a stack of change data, it could be a really good avenue for having better save games. We could serialize the change stack and reply them on a base game data instead of serializing a game data. That kind of change I think would be a big breakthrough for compatibility.

**Comment by trevan** [comment]
That should work as well, though I'm not entirely sure how to do that in a non-clone manner.  Is there something like that in the code base already?

**Comment by DanVanAtta** [comment]
- Creating a copy-constructor would do it.
- Keeping the original data immutable is good.
- Eventually we won't be wiring a `gameData` reference to everything (which we only do for save-game), that'll make it easier for the data to be immutable.
- We can use a state tracking inner object, so you only need to copy that state (similar to serialization proxy pattern)
- 'lombok' 'toBuilder' is a decent way to get a copy-constructor for free: https://projectlombok.org/features/Builder

Overall I think the band-aid is probably fine for now until we redo how game serialization is done.
