### PR TITLE
Fix NPE in CommentPanel

### LINKED ISSUE #3880: NPE when starting new PBEM game
### Engine version

1.9.0.0.11547

### My Operating System

Linux localhost.localdomain 4.17.11-200.fc28.x86_64 <span>#</span>1 SMP Mon Jul 30 15:21:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Map name

Classic: Iron Blitz 3rd Edition 2.0

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

* Start PBEM game.
* Select dice server **Internal Dice Roller**.
* Select PBEM **Gmail** and enter appropriate configuration.
* Play.

Error dialog displayed after map window appears.

### Do you have the exact error text? Please copy/paste if so

```
Aug 24, 2018 11:37:04 AM games.strategy.engine.framework.GameRunner lambda$0
SEVERE: null
java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:240)
	at games.strategy.triplea.ui.CommentPanel.lambda$3(CommentPanel.java:100)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Instead of this error, what should have happened?

No error dialog should be displayed.

### Any additional information that may help

This only happened once.  I wasn't able to reproduce it after the fact.  I doubt it has anything to do with a PBEM game, per se, but that's the type of game I was starting when the exception was raised.

### PR DESCRIPTION
**Pull request by ssoloff**
## Overview

Fixes #3880.

The methods of `ImageFactory` are not thread safe.  All calls (other than the one in `CommentPanel`) to `getSmallFlag()` are currently made from the EDT.  Presumably, the calls from `CommentPanel` were subject to some kind of race condition or other thread safety issue that caused `getSmallFlag()` to return `null` when invoked concurrently.  The `null` return value then caused the NPE.

The fix employed here is to simply move the `getSmallFlag()` call in `CommentPanel` back to the EDT.  This should avoid whatever race condition caused the `null` return value.

A further analysis of the `ImageFactory#getImage(String, boolean)` method showed that it could return `null` even if `throwIfNotFound` is true (e.g. `ImageIO#read()` may return `null`).  Therefore, the code in `CommentPanel` was further improved to defend against this possibility.

## Functional Changes

None.

## Manual Testing Performed

The race condition is difficult to repro, so I couldn't verify that directly.  However, I did verify the small flags are displayed as expected in the comment panel.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/triplea/ui/CommentPanel.java [hunk 1]
```diff
@@ -98,10 +96,8 @@ private void createComponents() {
     save.setMargin(inset);
     save.setFocusable(false);
     for (final PlayerID playerId : data.getPlayerList().getPlayers()) {
-      final CompletableFuture<?> future = CompletableFuture
-          .supplyAsync(() -> frame.getUiContext().getFlagImageFactory().getSmallFlag(playerId))
-          .thenAccept(image -> SwingUtilities.invokeLater(() -> iconMap.put(playerId, new ImageIcon(image))));
-      CompletableFutureUtils.logExceptionWhenComplete(future, "Failed to load small flag icon for " + playerId);
+      Optional.ofNullable(frame.getUiContext().getFlagImageFactory().getSmallFlag(playerId))
+          .ifPresent(image -> iconMap.put(playerId, new ImageIcon(image)));
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/triplea/ui/CommentPanel.java]: The reason this asynchronous computation was introduced was in order to move this potential "expensive IO operation" off the EDT

Comment (RoiEXLab) [reply game-core/src/main/java/games/strategy/triplea/ui/CommentPanel.java]: Agreed, but what speaks against a simple mutex to guarantee exclusive access?
Preferably using a normal thread to not block the thread pool unnecessarily

Comment (ssoloff) [reply game-core/src/main/java/games/strategy/triplea/ui/CommentPanel.java]: Such a change would affect lots of code that uses `ImageFactory`.  That would require a lot of testing to verify no new regressions or performance issues were introduced.  I simply want to get rid of the 4-5 NPEs I'm experiencing each week due to this bug. :smile:

Also, a single mutex controlling access to `ImageFactory#getImage()` would kind of defeat the purpose of the optimization from #3383.  Why launch one thread per player all competing for the same mutex?  Might as well just load all images sequentially on a single background thread given how the code in `getImage()` is currently written (because `ImageIO#read()` would be protected by that mutex).  (I understand that the time to initially display the game window is reduced in either case; I'm just pointing out that it might actually take longer to load and display the images by using more threads than necessary.)

I would propose that a more fundamental change needs to be made to `ImageFactory` to support asynchronous loading (and caching) of images in a truly concurrent fashion.  A dedicated method or methods for such support would be a nice addition (e.g. `ImageFactory#loadImageAsync(String key, Consumer<Image>)`, possibly using `SwingWorker` internally).  That should be explored in a dedicated PR.
