### PR TITLE
Fix IllegalStateException during combat when player is neutral

### LINKED ISSUE #2594: Large Mordor Map crashing when attacking neutral territories
### My Operating System:
windows 64 bit

[large morder hard good.zip](https://github.com/triplea-game/triplea/files/1464039/large.morder.hard.good.zip)

### TripleA version:

1.9.0.0.7378
### Map:
Large Mordor
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
I saved it right at the error, initiating the battle
### Do you have the exact error text? Please copy/paste if so
```
triplea.engine.version.bin:1.9
Loading map: large_middle_earth, from: C:\Users\johnw_000\triplea\downloadedMaps\large_middle_earth-master.zip
Loading resources from the following paths: [C:\Users\johnw_000\triplea\downloadedMaps\large_middle_earth-master.zip, C:\Program Files\TripleA\assets]
Loading map: large_middle_earth, from: C:\Users\johnw_000\triplea\downloadedMaps\large_middle_earth-master.zip
Loading resources from the following paths: [C:\Users\johnw_000\triplea\downloadedMaps\large_middle_earth-master.zip, C:\Program Files\TripleA\assets]
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy13.selectCasualties(Unknown Source)
	at games.strategy.triplea.delegate.BattleCalculator.selectCasualties(BattleCalculator.java:514)
	at games.strategy.triplea.delegate.Fire.selectCasualties(Fire.java:161)
	at games.strategy.triplea.delegate.Fire.access$100(Fire.java:21)
	at games.strategy.triplea.delegate.Fire$2.execute(Fire.java:221)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:41)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:380)
	at games.strategy.triplea.delegate.BattleTracker.fightBattleIfOnlyOne(BattleTracker.java:1176)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:97)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:506)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:401)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:253)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$169(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.delegate.DelegateExecutionManager.lambda$createOutboundImplementation$113(DelegateExecutionManager.java:116)
	... 15 more
Caused by: games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.framework.ServerGame.PLAYER_REMOTE.Neutral
	at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:224)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:122)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:99)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:51)
	at com.sun.proxy.$Proxy13.selectCasualties(Unknown Source)
	... 20 more
Caused by: java.lang.IllegalStateException: remote not found
	at java.lang.Thread.getStackTrace(Unknown Source)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	... 21 more
```

### Instead of this error, what should have happened?
neutral territories select kills.

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #2594 by partially reverting #2557 (the portion that initializes the `ITripleAPlayer` reference).

#### Testing

I verified playing the save game attached to #2594 no longer throws `IllegalStateException` and combat proceeds as expected.

### CODE REVIEW

File: src/main/java/games/strategy/triplea/delegate/BattleCalculator.java [hunk 1]
```diff
@@ -461,8 +463,12 @@ public static CasualtyDetails selectCasualties(final String step, final PlayerID
...
     final GameData data = bridge.getData();
     final boolean isEditMode = BaseEditDelegate.getEditMode(data);
-    final ITripleAPlayer tripleaPlayer = (ITripleAPlayer) bridge.getRemotePlayer(player);
-
+    final ITripleAPlayer tripleaPlayer;
+    if (player.isNull()) {
+      tripleaPlayer = new WeakAI(player.getName(), TripleA.WEAK_COMPUTER_PLAYER_TYPE);
+    } else {
+      tripleaPlayer = (ITripleAPlayer) bridge.getRemotePlayer(player);
+    }
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/triplea/delegate/BattleCalculator.java]: Would a ternary operator fit within the 120 char limit?

Comment (ssoloff) [reply src/main/java/games/strategy/triplea/delegate/BattleCalculator.java]: No, but, even with wrapping, it reduces the line count by 50%. :smile:  Done in rebased eca7723.

**Comment by ron-murhammer** [comment]
Funny how I called that this originally shouldn't have been removed :)

**Comment by ssoloff** [comment]
Yes, the @ron-murhammer spider-sense prevails once again. :smile:

BTW, I believe the reason @DanVanAtta couldn't reproduce it is because it's not that you need a neutral _player_ involved in a battle to hit that code path, but that you need to battle in a neutral _territory_.

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, thanks for the quick fix on this.
