### PR TITLE
Fix #2992 + simplifications

### LINKED ISSUE #2992: Another NPE when closing a game
Can't reproduce this consistently, but I just got this NPE:
```
Error: java.lang.NullPointerException
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at games.strategy.triplea.ui.MapPanel$BackgroundDrawer.run(MapPanel.java:861)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by RoiEXLab**

### CODE REVIEW

**Comment by ron-murhammer** [comment]
@RoiEXLab Is this related to #2980?

**Comment by RoiEXLab** [comment]
@ron-murhammer I don't think so, I just hit this error when testing #2991 and the Short Stacktrace didn't make it difficult to figure out the root cause

**Comment by RoiEXLab** [comment]
This PR is now ready to be reviewed btw.
Most of this PR is refactoring though, a lot of code could be simplified.

File: src/main/java/games/strategy/triplea/ui/MapPanel.java [hunk 1]
```diff
@@ -823,42 +817,31 @@ void showMouseCursor() {
...
-        final BlockingQueue<Tile> undrawnTiles;
-        final MapPanel panel = mapPanel;
-        undrawnTiles = panel.getUndrawnTiles();
-        final Tile tile;
+      while (running) {
         try {
-          tile = undrawnTiles.poll(2000, TimeUnit.MILLISECONDS);
+          final Tile tile = undrawnTiles.poll(2, TimeUnit.SECONDS);
+          if (tile != null) {
+            final GameData data = MapPanel.this.getData();
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/ui/MapPanel.java]: There's something about this that's bugging me.  It almost seems as if the tuple `(tile, gameData)` should have been sent through the queue rather than just `tile` itself.  There's nothing stopping a tile from being added to the `undrawnTile` queue with one `gameData` in place, and then someone calling `setGameData()` before that tile is dequeued and drawn, so that the value returned on this line will be different than what existed when the tile was added to the queue.  I don't know if that mismatch would cause a problem.

Also, access to `MapPanel#gameData` is not synchronized, but it is being read/written from different threads.  That could also cause this thread to use the wrong `GameData` value until memory becomes consistent again.  (Sending it through the queue would make this issue moot.)

These problems existed before this PR, so I'm not suggesting that you fix them, as you've already addressed the root cause of the NPE, but it might be something to consider.  What's your opinion, @RoiEXLab?

Comment (RoiEXLab) [reply src/main/java/games/strategy/triplea/ui/MapPanel.java]: Well I haven't really looked into the functionality, but I agree that the access of this Thread in general needs to be more synchronised in general, also because of the issue I mentioned above, so the loop is instantly being aborted, once the game is being stopped.
In any case something for a follow-up PR.

**Comment by RoiEXLab** [comment]
@ssoloff Merging this, since you didn't seem to have any other objections here...
