### PR TITLE
Fix monotonic sequence issue

### LINKED ISSUE #7112: 2.1.20365: MapRouteDrawer#drawCurvedPath:310 - NonMonotonicSequenceException
## Log Message
points 1 and 2 are not strictly increasing (11.319 >= 11.319)

## TripleA Version
2.1.20365

## Java Version
11.0.6

## Operating System
Mac OS X

## Stack Trace
```
org.apache.commons.math3.exception.NonMonotonicSequenceException: points 1 and 2 are not strictly increasing (11.319 >= 11.319)
	at org.apache.commons.math3.util.MathArrays.checkOrder(MathArrays.java:521)
	at org.apache.commons.math3.util.MathArrays.checkOrder(MathArrays.java:538)
	at org.apache.commons.math3.util.MathArrays.checkOrder(MathArrays.java:549)
	at org.apache.commons.math3.analysis.interpolation.SplineInterpolator.interpolate(SplineInterpolator.java:81)
	at games.strategy.triplea.ui.panels.map.MapRouteDrawer.drawCurvedPath(MapRouteDrawer.java:310)
	at games.strategy.triplea.ui.panels.map.MapRouteDrawer.drawRoute(MapRouteDrawer.java:95)
	at games.strategy.triplea.ui.panels.map.MapPanel.paint(MapPanel.java:696)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fix #7112

Also added a regression test.

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix
[] Other:   

## Testing

I verified everything still seems to work.

## Release Note

FIX|Fixed an issue where rarely a NonMonotonicSequenceException  could occur when planning moves

### CODE REVIEW

File: game-core/src/test/java/games/strategy/triplea/ui/panels/map/MapRouteDrawerTest.java [hunk 1]
```diff
@@ -101,4 +107,17 @@ void testCorrectParameterHandling() {
     verify(dummyRouteDescription, times(2)).getRoute();
     verify(dummyRouteDescription.getRoute(), atLeastOnce()).getAllTerritories();
   }
+
+  /** Regression test for https://github.com/triplea-game/triplea/issues/7112 */
```
Comment (DanVanAtta) [inline game-core/src/test/java/games/strategy/triplea/ui/panels/map/MapRouteDrawerTest.java:111]: References are good, 'required references' are not. What would happen if every test case required you to go to a different issue to understand why the test case was there? I think duplicating some of the details from the issue will be enough so that you don't have to look at the issue to understand this (though the reference being there is good nonetheless so if someone wants even more details, they can get them).

File: game-core/src/test/java/games/strategy/triplea/ui/panels/map/MapRouteDrawerTest.java [hunk 2]
```diff
@@ -101,4 +107,17 @@ void testCorrectParameterHandling() {
...
+  @Test
+  void verifySequenceIsTrulyMonotonic() {
+    final MapRouteDrawer routeDrawer = new MapRouteDrawer(mock(MapPanel.class), dummyMapData);
+    final double[] index =
+        routeDrawer.newParameterizedIndex(
+            new Point2D[] {new Double(0, 0), new Double(0, 0), new Double(0, 0)});
```
Comment (DanVanAtta) [inline game-core/src/test/java/games/strategy/triplea/ui/panels/map/MapRouteDrawerTest.java:117]: I think we might want to make this test parameterized and include more inputs. In this case we can assert that the output array is always equal in length to the input array and second the index checks can be converted to a simple for loop that verifies each element is less than the next.

Some interesting test cases to consider:
- zero length array
- singleton array (with zero)
- singleton array with negative
- singleton array with positive
- duplicate values other than zero
- out of order values
- mixture of positive and then negative values and then positive values (IE: -1, 1, -1, 1, 0, 1, -1, 0, -1)

**Comment by RoiEXLab** [comment]
@DanVanAtta Updated

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- game-core/src/test/java/games/strategy/triplea/ui/panels/map/MapRouteDrawerTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5948361&bid=19498657)

**Comment by DanVanAtta** [comment]
Good stuff, thanks @RoiEXLab
