### PR TITLE
Fix (hopefully) last routedrawer bug (#1315)

### LINKED ISSUE #1315: Route Drawer Does Not Wrap For Observer (1.9.0.0.3266)
The route drawer does not wrap when observing a move made by someone else in a hosted game.
bug_20161101

I've loaded the game on local at this point, and verified that it wraps correctly when you are playing with yourself. I assume it can be reproduced with any wrapping maps.

### PR DESCRIPTION
**Pull request by RoiEXLab**
This fixes #1315
Suprisingly easy - Still sad, that my normalizePoint method only caused problems so far ^^

You were right on gitter last September @DanVanAtta.
I just didn't notice that

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Yay optimized this method to death \:D
After that being done I can go to bed now ^^

**Comment by RoiEXLab** [comment]
Also If you didn't notice, I added in some requested test cases @DanVanAtta 
While adding those I realized, that I had 2 methods which were almost doing the same thing, so I decided to reuse the first one using a matrix transpose

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 1]
```diff
@@ -75,13 +71,13 @@ public RouteOptimizer(MapData mapData, MapPanel mapPanel) {
...
    */
-  private Point getClosestPoint(Point source, List<Point2D> pool) {
+  public static Point getClosestPoint(Point source, List<Point2D> pool) {
     double closestDistance = Double.MAX_VALUE;
     Point closestPoint = null;
     for (Point2D possibleClosestPoint : pool) {
       if (closestPoint == null) {
         closestDistance = source.distance(possibleClosestPoint);
-        closestPoint = normalizePoint(getPoint(possibleClosestPoint));
+        closestPoint = getPoint(possibleClosestPoint);
```
Comment (RoiEXLab) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: This fixes the bug

File: test/games/strategy/triplea/ui/TestRouteOptimizer.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+import java.awt.Point;
+import java.awt.geom.Point2D;
+import java.util.ArrayList;
+import java.util.List;
+
+import org.junit.Before;
+import org.junit.Test;
+
+import games.strategy.triplea.ui.mapdata.MapData;
+
```
Comment (DanVanAtta) [inline test/games/strategy/triplea/ui/TestRouteOptimizer.java]: I'm surprised there is no @RunWith(MockitoJUnitTestRunner.class) needed.

File: test/games/strategy/triplea/ui/TestRouteOptimizer.java [hunk 3]
```diff
@@ -0,0 +1,87 @@
...
+public class TestRouteOptimizer {
+
+  private MapPanel mapPanel;
+  private MapData mapData;
+
+  @Before
+  public void setUp() {
+    mapPanel = mock(MapPanel.class);
```
Comment (DanVanAtta) [inline test/games/strategy/triplea/ui/TestRouteOptimizer.java]: This can be replaced with a @Mock on the variable declaration. NBD either way. I think most of our other mockito mocks are created that way though.

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 4]
```diff
@@ -145,70 +138,26 @@ public Point getLastEndPoint() {
...
-          int index = altArrayCount == maxAdditionalScreens ? 2 : 0;
-          alternativePoints.get(index)[counter] = new Point(point.x, point.y - mapHeight);
-          alternativePoints.get(index + 1)[counter] = new Point(point.x, point.y + mapHeight);
-        }
-        if (isInfiniteX && isInfiniteY) {
-          alternativePoints.get(4)[counter] = new Point(point.x - mapWidth, point.y - mapHeight);
-          alternativePoints.get(5)[counter] = new Point(point.x - mapWidth, point.y + mapHeight);
-          alternativePoints.get(6)[counter] = new Point(point.x + mapWidth, point.y - mapHeight);
-          alternativePoints.get(7)[counter] = new Point(point.x + mapWidth, point.y + mapHeight);
+  public List<Point[]> getAllPoints(Point... points) {
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: No test case for this one? Is it an omission, something that would be particularly difficult to test?

If the latter, it can be made pretty easy to test by updating the API slightly:
```
public List<Point[]> getAllPoints(Point... points) {
  this.getAllPoints(point -> getpossiblePoints(point), points);
}

@VisibleForTesting
List<Point[]> getAllPoints(Function<Point,List<Point2D>> possiblePointsFunction, Point... points) {
 List<Point[]> allPoints = new ArrayList<>();
 +    for (int i = 0; i < points.length; i++) {
 +      List<Point2D> subPoints = possiblePointFunction.apply(points[i]);
 +      for (int y = 0; y < subPoints.size(); y++) {
 +        if (i == 0) {
 +          allPoints.add(new Point[points.length]);
          }
 +        allPoints.get(y)[i] = getPoint((subPoints.get(y)));
      }
```

With the above you can then send in a mock or a stubbed function for the possible point function. Just one thought on how we can increase the test coverage... I'm curious to know your thoughts on how and if we can/should test the `getAllPoints` method.

File: test/games/strategy/triplea/ui/TestRouteOptimizer.java [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+    possiblePoints.add(p(1000, 0));
+    possiblePoints.add(p(1000, 1000));
+    checkPoints(0, possiblePoints);
+    checkPoints(6, possiblePoints);
+    checkPoints(6, possiblePoints);
+    checkPoints(8, possiblePoints);
+  }
+
+  private void checkPoints(int offset, List<Point2D> expected) {
+    List<Point2D> calculatedPoints = new RouteOptimizer(mapData, mapPanel).getPossiblePoints(new Point());
```
Comment (DanVanAtta) [inline test/games/strategy/triplea/ui/TestRouteOptimizer.java]: What are your thoughts on setting up another test case to verify that the calculated points are updated as expected if the map panel is changed in size? If relatively straight forward, would you mind adding that check?

File: src/games/strategy/triplea/ui/RouteOptimizer.java [hunk 6]
```diff
@@ -105,7 +96,9 @@ private Point normalizePoint(Point point) {
    * @return A List of all possible Points depending in map Properties
    *         size may vary
    */
-  private List<Point2D> getPossiblePoints(Point2D point) {
+  public List<Point2D> getPossiblePoints(Point2D point) {
+    mapWidth = mapPanel.getImageWidth();
```
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: A comment here that the map panel may have changed size could be good context to capture. That is my assumption about why were are updating these.

File: test/games/strategy/triplea/ui/TestRouteOptimizer.java (hunk 2 above)
Comment (RoiEXLab) [inline test/games/strategy/triplea/ui/TestRouteOptimizer.java]: This annotation is only needed when using the @Mock annotation

File: test/games/strategy/triplea/ui/TestRouteOptimizer.java (hunk 5 above)
Comment (RoiEXLab) [inline test/games/strategy/triplea/ui/TestRouteOptimizer.java]: The method getImageWidth is not returning the size of the gameframe, but instead the size of the map. since the map size isn't changing during a game I should set those values inside the constructor... I have no idea why I didn't do that earlier

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 6 above)
Comment (RoiEXLab) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: This assignment is only needed when tested, since this Method is normally called after those values are set in the getTranslatedRoute method.
I recall that this was used, when I was still calculating the route based on the camera position. I will change that

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 4 above)
Comment (RoiEXLab) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: Your solution looks good, but I think it's not needed... Although we could test the behaviour of your method on its own (matrix transposal only) we can simly adjust the expected values to match our method, which is also tested, if this one method stopped working both tests would fail

**Comment by RoiEXLab** [comment]
@DanVanAtta added an additional test case

File: src/games/strategy/triplea/ui/RouteOptimizer.java (hunk 4 above)
Comment (DanVanAtta) [inline src/games/strategy/triplea/ui/RouteOptimizer.java]: I don't think I feel strongly enough to ask for further test changes here. Multiple tests depending on one component indicates system coupling. That can get to some pretty bad places, so the rule of thumb is to try and have only one test failure for any one thing that is broken.

**Comment by DanVanAtta** [comment]
Code looks okay to me. Let's do a thorough round of manual testing, then I think this will be good to go.

**Comment by RoiEXLab** [comment]
@DanVanAtta Just out of curiosity: What kind of manual testing did you think of? I can't imagine more than playing a game until combat move and moving the mouse widly beyond map borders once a unit is selected ^^

I just hope this gets merged quickly

**Comment by DanVanAtta** [comment]
@RoiEXLab , primarily the case that was reported should be verified.

**Comment by RoiEXLab** [comment]
Well I could reproduce this issue, exactly like he told us, and after this fix I'm no longer experiencing this issue... You can try it out yourself if you aren't convinced

**Comment by DanVanAtta** [comment]
@RoiEXLab I'm a bit exhausted on testing the route drawer code. I spent a bit too long with it when we were trying to release 1.9.

If you would, please test this update out on HexGlobe, where we have both vertical and horizontal wrapping. Then we just need one more final 5-10 minutes trying as hard as you can to break this code on a more classical horizontal WWII wrapping map.

@ron-murhammer  or @simon33-2 , feel free to jump in to help test this. Otherwise @RoiEXLab  let us know when you've done a final testing pass.

**Comment by RoiEXLab** [comment]
I think it's working...
Screenshot
Screenshot
Screenshot
