### PR TITLE
Ensure ErrorMessage is always initialized on EDT

### LINKED ISSUE #2919: error message pop-up text is blank with `null` input
Ran into an initialization error, can be repro'd by mangling the name of `game_engine.properties`:

can_get_null

Notice in the above we have an error message box with no text. We would expect instead to see some text, perhaps boiler plate, but very ideally we'd see "Caused by: java.lang.IllegalArgumentException: Property file not found: /home/dan/work/triplea/game_engine.properties"

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #2919.

#### Functional changes

* Initialize `ErrorMessage` as early as possible in `GameRunner#main()` to ensure initialization runs on the EDT.  If `ClientLogger#logError()` is called before `ErrorMessage` is initialized, the initialization will occur on the calling thread (possibly not the EDT), which will trigger another exception when, for example, the Substance L&F is used.
* Initialize L&F before `ErrorConsole` is initialized.  This has the side effect of rendering the console using the user's preferred L&F rather than the system L&F.  I suspect this is the way things used to be, and the `LookAndFeel#setupLookAndFeel()` call was probably inadvertently moved sometime in the past year.
* Initialize `ClientSettings` in `MapCreator` before the L&F is set.  This has the side effect of running the map-making tools using the user's preferred L&F rather than the system L&F.  Again, I think this is the way the map-making tools behaved in the past.

#### Refactoring changes

* Require `LookAndFeel#setupLookAndFeel()` to be called on the EDT rather than delegating to the EDT internally.  This just makes the call sites cleaner as they are already delegating to the EDT.
* Added some missing Javadocs.

#### Testing

Re-ran the scenario described in #2919 and verified `ErrorMessage` is displayed as expected and its error message is not `null`.

### CODE REVIEW

**Comment by prastle** [comment]
@ssoloff  we have a new idea in bunker if ya want to have a look when ya have a sec

File: src/main/java/games/strategy/engine/framework/lookandfeel/LookAndFeel.java [hunk 1]
```diff
@@ -65,26 +74,30 @@
...
+    checkState(SwingUtilities.isEventDispatchThread());
+
+    try {
+      UIManager.setLookAndFeel(ClientSetting.LOOK_AND_FEEL_PREF.value());
+      // FYI if you are getting a null pointer exception in Substance, like this:
+      // org.pushingpixels.substance.internal.utils.SubstanceColorUtilities
+      // .getDefaultBackgroundColor(SubstanceColorUtilities.java:758)
+      // Then it is because you included the swingx substance library without including swingx.
+      // You can solve by including both swingx libraries or removing both,
+      // or by setting the look and feel twice in a row.
```
Comment (RoiEXLab) [inline src/main/java/games/strategy/engine/framework/lookandfeel/LookAndFeel.java]: This comment can very likely be removed as the "new" substance library we use is internally very different to the original one.

Comment (ssoloff) [reply src/main/java/games/strategy/engine/framework/lookandfeel/LookAndFeel.java]: I thought `swingx` may now refer to what's called `trident`.  When I remove Trident from the classpath, I get a `NoClassDefFoundError` instead of an NPE, and the `NoClassDefFoundError` makes it obvious that Trident is missing.

So, I agree that the condition this comment is describing probably no longer occurs with the current Substance library.

Comment (ssoloff) [reply src/main/java/games/strategy/engine/framework/lookandfeel/LookAndFeel.java]: ef88a4636

File: src/main/java/tools/map/making/MapCreator.java [hunk 2]
```diff
@@ -71,10 +72,15 @@
     return new String[] {TRIPLEA_MAP_FOLDER, TRIPLEA_UNIT_ZOOM, TRIPLEA_UNIT_WIDTH, TRIPLEA_UNIT_HEIGHT};
   }
 
+  /**
+   * Entry point for the map-making utilities application.
+   */
   public static void main(final String[] args) {
-    LookAndFeel.setupLookAndFeel();
+    ClientSetting.initialize();
```
Comment (ron-murhammer) [inline src/main/java/tools/map/making/MapCreator.java]: @ssoloff It appears a user is having errors with AutoPlacementFinder related to ClientSetting. I see you added initialize to the map maker main method, does this need added to other main methods like: https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/tools/image/AutoPlacementFinder.java#L54

Comment (ssoloff) [reply src/main/java/tools/map/making/MapCreator.java]: @ron-murhammer Yeah, that's probably the case.  Let me take a look if there are any other considerations.  Otherwise, I'll submit a PR with a `ClientSetting#initialize()` call in every map making tool `main()` method.

Comment (ron-murhammer) [reply src/main/java/tools/map/making/MapCreator.java]: @ssoloff Yeah, I think for any of those main methods in components of the map creator, `ClientSetting.initialize()` needs called. I can make the PR if you don't have the time. Just wanted to get your thoughts since it appeared you had done something similar for the MapCreator main.

Comment (ssoloff) [reply src/main/java/tools/map/making/MapCreator.java]: @ron-murhammer I just want to verify there's not going to be any problems when `runUtilitiesAsSeperateProcesses` is `false`.  I don't think I checked that before.

Comment (ron-murhammer) [reply src/main/java/tools/map/making/MapCreator.java]: @ssoloff I actually tried that first to see if it was a work around but setting that to false, also fails for me in the current pre-release but seemingly with a different error. Adding the initilize() call doens't seem to change that failing.

Comment (ron-murhammer) [reply src/main/java/tools/map/making/MapCreator.java]: It appears to fail before you even get there on this line if you have that set to false https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/tools/image/AutoPlacementFinder.java#L47

Due to creating components outside the EDT.

Comment (ssoloff) [reply src/main/java/tools/map/making/MapCreator.java]: @ron-murhammer Yeah, it looks like that code is totally broken.  `MapCreator` attempts to call the `main()` methods on a new thread rather than the current EDT.  Might have to fix that in a separate PR.

Comment (ron-murhammer) [reply src/main/java/tools/map/making/MapCreator.java]: @ssoloff Yeah, I'd say let's just fix having it true for now as I doubt anyone sets the flag to false or they would have reported bugs :)  Can create a separate issue to fix or remove that flag.

Comment (ron-murhammer) [reply src/main/java/tools/map/making/MapCreator.java]: @ssoloff Did you want to go ahead and submit the PR or want me to? I created an issue for setting runUtilitiesAsSeperateProcesses to false: #3259

Comment (ssoloff) [reply src/main/java/tools/map/making/MapCreator.java]: Working on the PR now.  Thanks for creating the issue. :+1:
