### PR TITLE
Ensure transportedBy cleared for allied air units on carrier

### LINKED ISSUE #2630: Not all air attacked, various other bugs
[plane bug on ukraine.zip](https://github.com/triplea-game/triplea/files/1498093/plane.bug.on.ukraine.zip)

### Any additional information that may help:

Strange behavior on this release. Here is a savegame with an attack on Ukraine with 4 air units moved and only 3 were involved in combat. Other issues during same game were a problems with blitzing not working ( tank would not move back ) on Ukraine, and again on Trans-Jordan. Also my opponent had two subs from purchase disappear after placement. The other issues I believe were after the save so don't dig deep into the savegame.

[plane bug on ukraine.zip](https://github.com/triplea-game/triplea/files/1498095/plane.bug.on.ukraine.zip)

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #2630.

Allied air units transported as cargo on an attacking carrier are not part of the `attackingUnits` collection, and thus do not have their `transportedBy` property cleared at the end of the battle if they and their transporting carrier survive.  To ensure all applicable units have their `transportedBy` property cleared, the union of attacking units and battle site units must be used instead of just attacking units alone.

#### Testing

I used the [attached save game](https://github.com/triplea-game/triplea/files/1503248/issue-2630.zip) to verify the issue has been fixed.  After loading the save (at USA combat move step), the following actions are executed:

1. USA turn (round 1)
    1. Move carrier (with UK fighter as cargo) and fighter from SZ 52 to SZ 57.
    1. Resolve combat in SZ 57.  If USA carrier doesn't survive, restart test.
1. Wait for AI player turns to complete.
1. UK turn (round 2)
    1. Move fighter from SZ 57 to SZ 56.
    1. Resolve combat in SZ 56.

The test passes if the UK fighter participates in the combat step at (3)(ii).  I verified the test fails on `master` and passes on this branch.

### CODE REVIEW

File: src/main/java/games/strategy/triplea/delegate/MustFightBattle.java [hunk 1]
```diff
@@ -2550,15 +2552,17 @@ private void checkDefendingPlanesCanLand() {
...
     final CompositeChange change = new CompositeChange();
     // Clear the transported_by for successfully won battles where there was an allied air unit held as cargo by an
     // carrier unit
     final Collection<Unit> carriers = Matches.getMatches(attackingUnits, Matches.unitIsCarrier());
     if (!carriers.isEmpty() && !Properties.getAlliedAirIndependent(data)) {
       final Predicate<Unit> alliedFighters = Match.allOf(Matches.isUnitAllied(attacker, data),
           Matches.unitIsOwnedBy(attacker).negate(), Matches.unitIsAir(), Matches.unitCanLandOnCarrier());
-      final Collection<Unit> alliedAirInTerr = Matches.getMatches(attackingUnits, alliedFighters);
+      final Collection<Unit> alliedAirInTerr = Matches.getMatches(
+          CollectionUtils.union(attackingUnits, battleSite.getUnits()),
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/delegate/MustFightBattle.java]: I could have done this with pure JDK code:

```java
Stream.concat(attackingUnits.stream(), battleSite.getUnits().stream).collect(Collectors.toSet())
```

But the requirement to use `toSet()` seemed buried in there.  So instead of adding a comment calling out the need to remove duplicate units, I just used Apache Collections' `union()`, which does this automatically (assuming the source collections themselves don't contain duplicates).

File: src/main/java/games/strategy/triplea/delegate/MustFightBattle.java [hunk 2]
```diff
@@ -2550,15 +2552,17 @@ private void checkDefendingPlanesCanLand() {
   }
 
   static CompositeChange clearTransportedByForAlliedAirOnCarrier(final Collection<Unit> attackingUnits,
-      final PlayerID attacker, final GameData data) {
+      final Territory battleSite, final PlayerID attacker, final GameData data) {
```
Comment (ron-murhammer) [inline src/main/java/games/strategy/triplea/delegate/MustFightBattle.java]: Can't you use m_battleSite here instead of passing this parameter?

File: src/main/java/games/strategy/triplea/delegate/MoveDelegate.java [hunk 3]
```diff
@@ -456,7 +456,7 @@ static void repairMultipleHitPointUnits(final IDelegateBridge bridge, final Play
     final CompositeChange clearAlliedAir = new CompositeChange();
     for (final Unit carrier : damagedCarriers) {
       final CompositeChange change = MustFightBattle.clearTransportedByForAlliedAirOnCarrier(
-          Collections.singleton(carrier), carrier.getOwner(), data);
+          Collections.singleton(carrier), fullyRepaired.get(carrier), carrier.getOwner(), data);
```
Comment (ssoloff) [inline src/main/java/games/strategy/triplea/delegate/MoveDelegate.java]: This is how this call appeared at the time #1777 was merged.

File: src/main/java/games/strategy/triplea/delegate/MustFightBattle.java [hunk 4]
```diff
@@ -2550,15 +2552,17 @@ private void checkDefendingPlanesCanLand() {
...
     // Clear the transported_by for successfully won battles where there was an allied air unit held as cargo by an
     // carrier unit
     final Collection<Unit> carriers = Matches.getMatches(attackingUnits, Matches.unitIsCarrier());
     if (!carriers.isEmpty() && !Properties.getAlliedAirIndependent(data)) {
       final Predicate<Unit> alliedFighters = Match.allOf(Matches.isUnitAllied(attacker, data),
           Matches.unitIsOwnedBy(attacker).negate(), Matches.unitIsAir(), Matches.unitCanLandOnCarrier());
-      final Collection<Unit> alliedAirInTerr = Matches.getMatches(attackingUnits, alliedFighters);
+      final Collection<Unit> alliedAirInTerr = Matches.getMatches(
+          CollectionUtils.union(attackingUnits, battleSite.getUnits()),
+          alliedFighters);
```
Comment (ron-murhammer) [inline src/main/java/games/strategy/triplea/delegate/MustFightBattle.java]: Would it be better to just use Java 8 here or is there a guava equivalent since we already include that?

**Comment by ron-murhammer** [comment]
@ssoloff Ok, looks like you commented on why you didn't go the pure java route. Gonna merge this and we can always refactor later on if we find a better way to do it.

File: src/main/java/games/strategy/triplea/delegate/MustFightBattle.java (hunk 4 above)
Comment (ssoloff) [reply src/main/java/games/strategy/triplea/delegate/MustFightBattle.java]: I considered using Guava's `Sets.union()`, but it required converting the existing `Collection`s to `Set`s, which seemed a bit noisy:

```java
final Collection<Unit> alliedAirInTerr = Matches.getMatches(
    Sets.union(Sets.newHashSet(attackingUnits), Sets.newHashSet(battleSite.getUnits())),
    alliedFighters);
```

As I said above, Java 8 streams can also be used, but the `toSet()` call could be easily overlooked, and I didn't want to add the comment `// remove duplicates`.

I can understand if the concern is the introduction of a new dependency.  I guess the Guava alternative is more in-your-face "this is removing duplicates" because the word "set" appears no less than five times. :smile:

Comment (ron-murhammer) [reply src/main/java/games/strategy/triplea/delegate/MustFightBattle.java]: Yeah, I glanced at the Guava alternative and realized the same thing. I tend to lean on limiting new dependencies as it makes it harder for new developers.
