### PR TITLE
Don't add task to queue if shut down

### LINKED ISSUE #9212: 2.5.22294: MapPanel#setGameData:607 - java.util.concurrent.RejectedExecutionException
## Map
twelve-clans

## Log Message
Task games.strategy.triplea.ui.panels.map.MapPanel$$Lambda$1656/0x00000008006c7c40@37e739e0 rejected from java.util.concurrent.ThreadPoolExecutor@60fdd445[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 201]

## TripleA Version
2.5.22294

## Java Version
11.0.6

## Operating System
Mac OS X

## Memory
Heap utilization statistics [MB]
Used Memory: 1075
Free memory: 972
Total memory: 2048
Max memory: 2048

## Stack Trace
```
Exception: java.util.concurrent.RejectedExecutionExceptionTask games.strategy.triplea.ui.panels.map.MapPanel$$Lambda$1656/0x00000008006c7c40@37e739e0 rejected from java.util.concurrent.ThreadPoolExecutor@60fdd445[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 201]
java.lang.Exception
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at games.strategy.triplea.ui.panels.map.MapPanel.setGameData(MapPanel.java:607)
	at games.strategy.triplea.ui.TripleAFrame.showHistory(TripleAFrame.java:2040)
	at games.strategy.triplea.ui.TripleAFrame.updateStepFromEdt(TripleAFrame.java:1894)
	at games.strategy.triplea.ui.TripleAFrame.updateStep(TripleAFrame.java:1836)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at games.strategy.engine.data.GameDataEventListeners.accept(GameDataEventListeners.java:20)
	at games.strategy.engine.data.GameData.fireGameDataEvent(GameData.java:265)
	at games.strategy.engine.framework.ServerGame.notifyGameStepChanged(ServerGame.java:555)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:514)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:398)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:82)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.lambda$launch$0(LocalLauncher.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

### PR DESCRIPTION
**Pull request by RoiEXLab**
## Change Summary & Additional Notes

Should fix #9212

### CODE REVIEW

File: game-app/game-core/src/main/java/games/strategy/triplea/ui/panels/map/MapPanel.java [hunk 1]
```diff
@@ -625,7 +625,12 @@ public void setGameData(final GameData data) {
     gameData.addTerritoryListener(territoryListener);
     gameData.addDataChangeListener(dataChangeListener);
     clearPendingDrawOperations();
-    executor.execute(() -> tileManager.resetTiles(gameData, uiContext.getMapData()));
+    // Try to mitigate race condition where game data is set after shutting down the executor
+    // technically there's no guarantee because the executor can be shut down after the if check
+    // and before the call to execute, but it should be good enough!
+    if (!executor.isTerminated()) {
```
Comment (DanVanAtta) [inline game-app/game-core/src/main/java/games/strategy/triplea/ui/panels/map/MapPanel.java:631]: Any idea how we get into this method with a terminated executor?

I was wondering if it was some sort of cleanup and we were passing in a `null` `GameData` object to this method. Though.. looking at it, the null check seems nonsenical, if `data` were ever null we would get a NPE just a few lines earlier.

**Review by DanVanAtta — APPROVED** [review]
