### PR TITLE
Fix Lobby Table regression

### LINKED ISSUE #2725: Cant open selected bot
### Any additional information that may help:

Not sure when exactly this broke, but it works fine in 7898 - You cannot open the selected bot in 7923. It chooses a different bot. For example if I want to open bot 41 - it will open bot 91 instead.

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fixes  #2725

### CODE REVIEW

File: src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java [hunk 1]
```diff
@@ -158,7 +160,7 @@ private void mouseOnGamesList(final MouseEvent e) {
       return;
     }
     // we sort the table, so get the correct index
-    final GameDescription description = gameTableModel.get(selectedIndex);
+    final GameDescription description = gameTableModel.get(gameTable.convertRowIndexToModel(selectedIndex));
```
Comment (ssoloff) [inline src/main/java/games/strategy/engine/lobby/client/ui/LobbyGamePanel.java]: This seems like a good candidate for an Extract Method refactoring to avoid accidentally re-introducing this problem in the future.
