### PR TITLE
Fix filter used to extract players in an alliance

### LINKED ISSUE #2961: alliance section in xml erroneously edited by game engine
### My Operating System:
windows 10

### Engine version:
.7746 still ok, .7752 to .8659 not ok

### Map name and version:
all 270BC maps, Bad-Ass 4 Nation FFA

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
In 270 BC maps opened from depot, the alliances are all screwed up. If you export the xml from game and look at alliance section. It shows 4 nations listed in both roman and anti roman alliances.

In Bad-Ass 4 Nation FFA, I only noticed a stats panel glitch and roundels listed inconsistently so far. But once the above 270 BC error was established. I also exported the Bad-Ass  xml to see if the alliance section is listed incorrectly. And it is incorrect.

Note that the xml is correct if viewing the files from their game folders. So looks like the game engine makes the changes after it loads the xml. And, or the xml export just lists those changes.

### Do you have the exact error text? Please copy/paste if so
270BC, quickest way to see there is a alliance problem is to go to Politics Panel and notice relationships are wrong.

So far these are the changes it added (and don't belong) to the 270BC xml via export (once loaded by game engine), Note, so far I have only looked in the alliance section of xml.

alliance player="Carthage" alliance="RomanAlliance"
alliance player="Numidia" alliance="RomanAlliance"
alliance player="Macedonia" alliance="RomanAlliance"
alliance player="Syria" alliance="RomanAlliance"

Link to the Bad-Ass related bug report here.
https://github.com/triplea-game/triplea/issues/2855

So far these are the changes it added (and don't belong) to the Bad-Ass 4 Nation FFA xml via export (once loaded by game engine), Note, so far I have only looked in the alliance section of xml.

alliance player="Envoy_III" alliance="Envoy_I"
alliance player="Envoy_II" alliance="Envoy_I"
alliance player="Envoy_III" alliance="Envoy_II"

### Any additional information that may help:
Hopefully it is not changing any other sections of xml as well. Might be a good idea to scan through an entire xml file for any thing else, that stands out. Via the xml export.

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #2961.

The filter used in `AllianceTracker#getPlayersInAlliance()` mistakenly matched substrings when comparing alliance names rather than the alliance name as a whole.  The call to `String#contains()` appears to be an accidental carryover due to the original `Iterator`-based code receiving map entries of type `Map.Entry<PlayerID, Collection<String>>`.  The Guava `Multimap` stream flattens the multimap so that the streamed entries are of type `Map.Entry<PlayerID, String>`, thus `Object#equals()` is the appropriate filter condition.

#### Testing

The new unit test passes with the original `Iterator` code, fails with the code prior to this PR, and passes with the code in this PR.  I also verified the 270BC politics panel appears as it did prior to #2681.

### CODE REVIEW

File: src/test/java/games/strategy/engine/data/AllianceTrackerTest.java [hunk 1]
```diff
@@ -35,5 +40,22 @@ public void testAddAlliance() {
...
   }
 
-  // TODO create test suite for Alliance/Relationships/Politics
+  @Test
+  public void getPlayersInAlliance_ShouldDifferentiateAllianceNamesThatAreSubstringsOfOtherAllianceNames() {
+    final PlayerID player1 = new PlayerID("Player1", gameData);
+    final PlayerID player2 = new PlayerID("Player2", gameData);
+    final PlayerID player3 = new PlayerID("Player3", gameData);
+    final PlayerID player4 = new PlayerID("Player4", gameData);
+    final String alliance1Name = "Alliance"; // NOTE: alliance1 name is a substring of alliance2 name
```
Comment (DanVanAtta) [inline src/test/java/games/strategy/engine/data/AllianceTrackerTest.java]: instead of a note, would it be better to form `alliance2Name` as a string concatenation? It would then be enforced, eg:
```
final String alliance2Name = "Anti" + alliance1Name;
```

**Comment by prastle** [comment]
Does this not mean that all current stable users need a new release?

**Comment by ssoloff** [comment]
@prastle This bug only affects games where one alliance name is a substring of another.  For example, in 270BC, "RomanAlliance" is a substring of "AntiRomanAlliance".  Are there any other maps that have similar alliance names?

I believe @ron-murhammer was waiting for #2764 to be closed before releasing a new stable.  As that issue should be complete soon, there will probably be a new stable around the corner that includes this fix.

**Comment by RoiEXLab** [comment]
@ssoloff Thanks for fixing that so quickly 👍

**Comment by prastle** [comment]
Cool Thanks!
