### PR TITLE
"Fix #14058: Include transported units in unit scroller

### LINKED ISSUE #14058: Unit Scroller Does not Include units on transport (and units that can be 'given' movement)
See: https://github.com/triplea-game/triplea/pull/12896 for problem screenshots

### Reproduction Steps

1. move units onto transport
2. use the unit scroller
Notice: the transported units are no longer visible on the scroller, yet they can still move to disembark
Expected: units that can be physically moved, should be available in the unit scroller (even if they technically have '0' movement, if it's possible to move them at all, they should be in the scorller)

cc: @WCSumpton who originally reported and proposed a fix to this issue.

### PR DESCRIPTION
**Pull request by Aashivdev**
## Description
Fixes #14058 

Units loaded on transports now appear in the unit scroller, even though they technically have 0 movement left, because they can still move by disembarking.

## Changes
Modified `UnitScrollerModel.getMoveableUnits()` to include units being transported:
- Changed predicate from checking only `unitHasMovementLeft()` 
- To checking `unitHasMovementLeft() OR unitIsBeingTransported()`

## Rationale
The issue reported that units on transports disappear from the unit scroller, but these units can still physically move by disembarking. This fix ensures all units that can move are visible to players in the scroller.

## Testing
- Code compiles successfully
- Change directly addresses the reported issue

---

This is my first contribution to TripleA. Happy to make any adjustments based on feedback! 😊

## Testing Note
I was unable to run the full game locally due to Java version compatibility issues, 
but I have verified the logic through code analysis. The fix ensures that 
`unitIsBeingTransported()` units are included in the predicate. 

Would appreciate if a maintainer could test this in the actual game by:
1. Loading units onto a transport
2. Verifying they appear in the unit scroller

### CODE REVIEW

**Comment by frigoref** [comment]
@Aashiv2k5 Thank you very much for your PR! It looks good to me from a technical point of view, but requires testing before we can merge it.
Also, please sign the CLA above. 

If you would need some help to run in locally yourself, I would be happy to assist you. Have you checked the documentation we have for developers to run it locally? If yes, please let me know your local java version, intellij settings and the specific problem you are facing.

File: game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java [hunk 1]
```diff
@@ -26,7 +26,20 @@ static List<Unit> getMoveableUnits(
...
+                        // Unit is already being transported
+                        || Matches.unitIsBeingTransported().test(u)
+                        // Unit can be loaded onto an available transport in this territory
+                        || (Matches.unitCanBeTransported().test(u)
+                            && t.anyUnitsMatch(
+                                Matches.unitCanTransport().and(Matches.unitIsOwnedBy(player))))
+                        // Unit can gain movement from a carrier in this territory
+                        || (Matches.unitCanLandOnCarrier().test(u)
+                            && t.anyUnitsMatch(
+                                Matches.unitIsCarrier().and(Matches.unitIsOwnedBy(player)))))
```
Comment (WCSumpton) [inline game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java]: This is unnecessary as carrier and planes are handled differently.

Cheers...

File: game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java [hunk 2]
```diff
@@ -26,7 +26,20 @@ static List<Unit> getMoveableUnits(
...
+            .and(
+                u ->
+                    // Unit has movement left
+                    Matches.unitHasMovementLeft().test(u)
+                        // Unit is already being transported
+                        || Matches.unitIsBeingTransported().test(u)
+                        // Unit can be loaded onto an available transport in this territory
+                        || (Matches.unitCanBeTransported().test(u)
+                            && t.anyUnitsMatch(
+                                Matches.unitCanTransport().and(Matches.unitIsOwnedBy(player))))
```
Comment (WCSumpton) [inline game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java]: I don't think this will work here because sea transports will not be in the same territory. This could be used with air and land transports. You might want to see if the transporting unit has any movement left.

File: game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java [hunk 3]
```diff
@@ -26,7 +26,20 @@ static List<Unit> getMoveableUnits(
...
         PredicateBuilder.of(Matches.unitIsOwnedBy(player))
-            .and(Matches.unitHasMovementLeft())
+            .and(
+                u ->
+                    // Unit has movement left
+                    Matches.unitHasMovementLeft().test(u)
+                        // Unit is already being transported
+                        || Matches.unitIsBeingTransported().test(u)
+                        // Unit can be loaded onto an available transport in this territory
+                        || (Matches.unitCanBeTransported().test(u)
```
Comment (WCSumpton) [inline game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java]: This needs to be qualified, what units are you looking for, almost all land units can be transported, so units that have already moved will bleed into this. This is why I am suggesting first select 0 movement units first with `Matches.unitCanMove().negate().test(u)` you could use `Matches.unitHasNotMoved().test(u)`

File: game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java [hunk 4]
```diff
@@ -26,7 +26,20 @@ static List<Unit> getMoveableUnits(
 
     final Predicate<Unit> moveableUnitOwnedByMe =
         PredicateBuilder.of(Matches.unitIsOwnedBy(player))
-            .and(Matches.unitHasMovementLeft())
+            .and(
+                u ->
+                    // Unit has movement left
+                    Matches.unitHasMovementLeft().test(u)
+                        // Unit is already being transported
+                        || Matches.unitIsBeingTransported().test(u)
```
Comment (WCSumpton) [inline game-app/game-core/src/main/java/games/strategy/triplea/ui/unit/scroller/UnitScrollerModel.java]: @Aashiv2k5 
This is okay.

**Comment by frigoref** [comment]
@Aashiv2k5 could you please check, run the `spotlessJavaApply` and provide the correction commit?
I understand not all cases are yet covered, but more than before. Do you want to continue in this PR until all are covered or would you prefer to split this in two steps?

**Comment by Aashiv2k5** [comment]
@frigoref Thank you so much for the guidance and patience! This was a great learning experience. Looking forward to contributing more to TripleA! 🚀

@TheDog-GH Thanks for the issue suggestions - I'll check those out for my next contribution!

**Comment by TheDog-GH** [comment]
@Aashiv2k5
Thanks for this PR !
Please could you look at this one, it will have the **most** impact on the most maps and most game players.
https://github.com/triplea-game/triplea/issues/9231
