### PR TITLE
Track the isSub/isSuicide combo properties separately from the individual props

### LINKED ISSUE #7177: Planes don't attack subs
### How can the problem be recreated?
Global 40 House Rules with Canada

Follow the prompts in the saved games. 13066 allows planes to shoot at subs but 20365 doesn't.

### Do you have any ideas for an expected fix?
See how 13066 did it.

### Attach a Save Game

[13066 planes do attack subs.zip](https://github.com/triplea-game/triplea/files/4928323/13066.planes.do.attack.subs.zip)

[20234 planes don't attack subs.zip](https://github.com/triplea-game/triplea/files/4928325/20234.planes.don.t.attack.subs.zip)

### If playing a prerelease, which version are you using?

Game Version:
2.1.20365

### If playing a prerelease, does this happen on the latest release?

- [] yes
- [] no

### Is there anything else we should know?

I turned on map option "Option Redesign" and turned off "Air Attack Sub Restricted". Scramble one ftr from Scotland. You may need to run more than once if sub is killed before ftr would shoot at it.

Trying to add the "Regression" label but haven't been able to figure it out.

### PR DESCRIPTION
**Pull request by trevan**
Fixes #7177

With the change from isSub and isSuicide to the separated properties, the engine now checks the gameProperties only once when the save is loaded or the game map is loaded.  If the user then edits the gameProperties through the UI and changes sub or suicide related properties, they will not take affect.

This adds back the isSub and the isSuicide properties.  The separate properties are no longer set during setIsSub and setIsSuicide.  Instead, each of the properties will check if isSub or isSuicide is set.  And if a gameProperty is needed, it will check it then.  This way, the edited gameProperty will be seen when the game starts.

I've verified that this is save compatible with older saves in 2.x.  Those saves will not be fixed by this change.  The user will have to restart the game to see this fix.

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix
[] Other:   

## Testing

I've played a few sub games with a few different properties.  It looks like the properties are acting correctly and that user editable properties work.

## Release Note

FIX|Disabling "Air Attack Sub Restricted" in Map Options will correctly allow airplanes to hit subs.
REGRESSION|Loading a saved games from a previous version for maps that have triggers to change isSub and isSuiced (such as Total World War 2.8 and 3.0, and HexGlobeFFA_w_TWW) may stop changing those properties during the triggers.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java [hunk 1]
```diff
@@ -629,13 +633,10 @@ private void setIsSub(final String s) {
...
   private void setIsSub(final Boolean s) {
-    setCanEvade(s);
-    setIsFirstStrike(s);
-    setCanMoveThroughEnemies(s && Properties.getSubmersibleSubs(getData()));
-    setCanBeMovedThroughByEnemies(s && Properties.getIgnoreSubInMovement(getData()));
+    isSub = true;
     if (s) {
       canNotTarget = null;
-      canNotBeTargetedBy = Properties.getAirAttackSubRestricted(getData()) ? null : new HashSet<>();
+      canNotBeTargetedBy = null;
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java:639]: Codacy found an issue: [Assigning an Object to null is a code smell.  Consider refactoring.](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5897929)

**Comment by DanVanAtta** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/triplea-game/triplea/pullRequest?prid=5897929&bid=19311411)

**Comment by Cernelius** [comment]
I believe this is the proper way to handle this, as I've already detailed in here:
https://forums.triplea-game.org/topic/328/unit-option-can-submerge-hide-for-land-units-partisan-guerrilla-spy-diplomat-munition/44?page=3

Of course, I foresaw that the issue at hand (that this PR aims to fix) would have eventually happened, likely a few weeks or months after the release of 2.0 (as it did). As I said, I don't believe that the inability of changing properties mid game is an important item, so, please, rather refer to the other matters I raised at the linked topic.

CC: @ron-murhammer 

---

@trevan I'm curious if and how this may influence adding/setting `isSub` and `isSuicide` with triggers (within any unit attachment) during the course of the game. When 2.0 was released, the situation was that it was not (any longer) possible to do such a thing. Is this PR impacting on this matter in any ways?

**Comment by Cernelius** [comment]
> This adds back the isSub and the isSuicide properties. The separate properties are no longer set during setIsSub and setIsSuicide. Instead, each of the properties will check if isSub or isSuicide is set. And if a gameProperty is needed, it will check it then. This way, the edited gameProperty will be seen when the game starts.

What I understand it will be the program behaviour after the merging of this PR is that in a game in which "isSub" is true for one or more units, each of the units will be non-targetable by air units if "Air Attack Sub Restricted" is true (no matter the setting of this property upon starting the game and at any previous point during the course of the game).

However, what will happen if, instead, the same unit has no "isSub" option defined but has "canNotBeTargetedBy" set to all air units types?

What I understand it will happen is that the "Air Attack Sub Restricted" acts as a behavioural switch for the "isSub" option only, but it is irrelevant for any of its atomized options (the "isSub" option i a shortcut of).

If my understanding is correct, I believe this would be not very good a behaviour, as it would give the "isSub" option an ability not covered by any of the options it is a shortcut of. A shortcut should be just a shortcut, not something that allows achieving anything not otherwise possibly achievable.

Meaning that I believe it is advisable that, if the "Air Attack Sub Restricted" property causes "isSub" units to be non-targetable by air units, then the same property should also be required to have the "canNotBeTargetedBy" option being effective (meaning that if the "Air Attack Sub Restricted" property is false, then all "canNotBeTargetedBy" options are ineffective (of course, this would be very confusing, since the "canNotBeTargetedBy" may not have only and all air units in list and may be assigned to a non-submersible unit, so the property should be renamed or deprecated)).

**Comment by trevan** [comment]
> @trevan I'm curious if and how this may influence adding/setting `isSub` and `isSuicide` with triggers (within any unit attachment) during the course of the game. When 2.0 was released, the situation was that it was not (any longer) possible to do such a thing. Is this PR impacting on this matter in any ways?

I forgot about testing triggers.  This will break saved games for those maps.  I don't know how to handle saves for those maps since I can't look at the gameData properties as they aren't available during the deserialization of the UnitAttachment and I can't deduce if the UnitAttachment should be isSub or not based on the saved properties since a non-isSub unit can look like an isSub.

I don't know how to fix this issue and still handle old saves.  I'm closing this since it is an invalid fix.  Someone else who knows the code better will need to figure out a solution.

**Comment by trevan** [comment]
> > This adds back the isSub and the isSuicide properties. The separate properties are no longer set during setIsSub and setIsSuicide. Instead, each of the properties will check if isSub or isSuicide is set. And if a gameProperty is needed, it will check it then. This way, the edited gameProperty will be seen when the game starts.
> 
> What I understand it will be the program behaviour after the merging of this PR is that in a game in which "isSub" is true for one or more units, each of the units will be non-targetable by air units if "Air Attack Sub Restricted" is true (no matter the setting of this property upon starting the game and at any previous point during the course of the game).
> 
> However, what will happen if, instead, the same unit has no "isSub" option defined but has "canNotBeTargetedBy" set to all air units types?
> 
> What I understand it will happen is that the "Air Attack Sub Restricted" acts as a behavioural switch for the "isSub" option only, but it is irrelevant for any of its atomized options (the "isSub" option is a shortcut of).
> 
> If my understanding is correct, I believe this would be not very good a behaviour, as it would give the "isSub" option an ability not covered by any of the options it is a shortcut of. A shortcut should be just a shortcut, not something that allows achieving anything not otherwise possibly achievable.
> 
> Meaning that I believe it is advisable that, if the "Air Attack Sub Restricted" property causes "isSub" units to be non-targetable by air units, then the same property should also be required to have the "canNotBeTargetedBy" option being effective (meaning that if the "Air Attack Sub Restricted" property is false, then all "canNotBeTargetedBy" options are ineffective (of course, this would be very confusing, since the "canNotBeTargetedBy" may not have only and all air units in list and may be assigned to a non-submersible unit, so the property should be renamed or deprecated)).

@Cernelius, That is tangentially related to this issue so it should be in its own separate issue so that it doesn't get lost.

**Comment by Cernelius** [comment]
> > @trevan I'm curious if and how this may influence adding/setting `isSub` and `isSuicide` with triggers (within any unit attachment) during the course of the game. When 2.0 was released, the situation was that it was not (any longer) possible to do such a thing. Is this PR impacting on this matter in any ways?
> 
> I forgot about testing triggers. This will break saved games for those maps. I don't know how to handle saves for those maps since I can't look at the gameData properties as they aren't available during the deserialization of the UnitAttachment and I can't deduce if the UnitAttachment should be isSub or not based on the saved properties since a non-isSub unit can look like an isSub.
> 
> I don't know how to fix this issue and still handle old saves. I'm closing this since it is an invalid fix. Someone else who knows the code better will need to figure out a solution.

Dang! I believe your reworking is itself way more important than any save-game compatibility, especially considering that this would be a problem for only a very few users (which can still play with the old engine).

My suggestion, do this anyway, and just be sure to upgrade the TripleA version to 2.2 when you make a new release, giving the list of games that will lose save-game compatibility.

On this matter, I think it would be good to use the second digit for  partial compatibility losses like this one, reserving a third digit for completely compatible new releases (first digit will break compatibility, second digit may break compatibility, third digit will not break compatibility).

**Comment by Cernelius** [comment]
> > > This adds back the isSub and the isSuicide properties. The separate properties are no longer set during setIsSub and setIsSuicide. Instead, each of the properties will check if isSub or isSuicide is set. And if a gameProperty is needed, it will check it then. This way, the edited gameProperty will be seen when the game starts.
> > 
> > 
> > What I understand it will be the program behaviour after the merging of this PR is that in a game in which "isSub" is true for one or more units, each of the units will be non-targetable by air units if "Air Attack Sub Restricted" is true (no matter the setting of this property upon starting the game and at any previous point during the course of the game).
> > However, what will happen if, instead, the same unit has no "isSub" option defined but has "canNotBeTargetedBy" set to all air units types?
> > What I understand it will happen is that the "Air Attack Sub Restricted" acts as a behavioural switch for the "isSub" option only, but it is irrelevant for any of its atomized options (the "isSub" option is a shortcut of).
> > If my understanding is correct, I believe this would be not very good a behaviour, as it would give the "isSub" option an ability not covered by any of the options it is a shortcut of. A shortcut should be just a shortcut, not something that allows achieving anything not otherwise possibly achievable.
> > Meaning that I believe it is advisable that, if the "Air Attack Sub Restricted" property causes "isSub" units to be non-targetable by air units, then the same property should also be required to have the "canNotBeTargetedBy" option being effective (meaning that if the "Air Attack Sub Restricted" property is false, then all "canNotBeTargetedBy" options are ineffective (of course, this would be very confusing, since the "canNotBeTargetedBy" may not have only and all air units in list and may be assigned to a non-submersible unit, so the property should be renamed or deprecated)).
> 
> @Cernelius, That is tangentially related to this issue so it should be in its own separate issue so that it doesn't get lost.

Can you answer me if I got everything right and, in this case, assure me I'm not misunderstanding anything?

In my opinion, such an issue (to consider the matter more comprehensively) should have been opened before making this PR.

**Comment by trevan** [comment]
> > > @trevan I'm curious if and how this may influence adding/setting `isSub` and `isSuicide` with triggers (within any unit attachment) during the course of the game. When 2.0 was released, the situation was that it was not (any longer) possible to do such a thing. Is this PR impacting on this matter in any ways?
> > 
> > 
> > I forgot about testing triggers. This will break saved games for those maps. I don't know how to handle saves for those maps since I can't look at the gameData properties as they aren't available during the deserialization of the UnitAttachment and I can't deduce if the UnitAttachment should be isSub or not based on the saved properties since a non-isSub unit can look like an isSub.
> > I don't know how to fix this issue and still handle old saves. I'm closing this since it is an invalid fix. Someone else who knows the code better will need to figure out a solution.
> 
> Dang! I believe your reworking is itself way more important than any save-game compatibility, especially considering that this would be a problem for only a very few users (which can still play with the old engine).
> 
> My suggestion, do this anyway, and just be sure to upgrade the TripleA version to 2.2 when you make a new release, giving the list of games that will lose save-game compatibility.
> 
> On this matter, I think it would be good to use the second digit for partial compatibility losses like this one, reserving a third digit for completely compatible new releases (first digit will break compatibility, second digit may break compatibility, third digit will not break compatibility).

I think only @DanVanAtta or @RoiEXLab can make the call on breaking save compatibility.  The save game would load and it would play.  But the triggers would no longer work correctly.  They would be turning on/off `isSub` but the original atomic properties (`canEvade`, etc) would not be affected unless they had been disabled previously.

**Comment by trevan** [comment]
> Can you answer me if I got everything right and, in this case, assure me I'm not misunderstanding anything?
> 
> In my opinion, such an issue (to consider the matter more comprehensively) should have been opened before making this PR.

I haven't looked that in depth in how this functionality works.  I'm just trying to ensure that when you change a map property through the UI, the changed property actually takes affect.  As to how the property works and interacts with pieces, I'm not that well versed.

Go ahead and create the issue if you feel it needs to be discussed more in depth.

**Comment by Cernelius** [comment]
> > Can you answer me if I got everything right and, in this case, assure me I'm not misunderstanding anything?
> > In my opinion, such an issue (to consider the matter more comprehensively) should have been opened before making this PR.
> 
> I haven't looked that in depth in how this functionality works. I'm just trying to ensure that when you change a map property through the UI, the changed property actually takes affect. As to how the property works and interacts with pieces, I'm not that well versed.
> 
> Go ahead and create the issue if you feel it needs to be discussed more in depth.

Not being a developer (thus being unable to read through the code), I need to be confirmed on a very least to two points, before seriously considering opening anything:

1. The "Air Attack Sub Restricted" property causes units that are "isSub" to be non-targetable by air units (what this PR would have changed is just to make this true in any case, instead of relating it to the state of the property upon starting the game only).
2. The "Air Attack Sub Restricted" property does nothing to units that are both "canNotBeTargetedBy" and non-"isSub" (now and regardless of this PR being merge).

As a side note, since "isSub" is a shortcut (possibly setting "canNotBeTargetedBy" to all air units), I also wonder what would happen to units having both of the "isSub" and "canNotBeTargetedBy" options set.

**Comment by trevan** [comment]
> > > Can you answer me if I got everything right and, in this case, assure me I'm not misunderstanding anything?
> > > In my opinion, such an issue (to consider the matter more comprehensively) should have been opened before making this PR.
> > 
> > 
> > I haven't looked that in depth in how this functionality works. I'm just trying to ensure that when you change a map property through the UI, the changed property actually takes affect. As to how the property works and interacts with pieces, I'm not that well versed.
> > Go ahead and create the issue if you feel it needs to be discussed more in depth.
> 
> Not being a developer (thus being unable to read through the code), I need to be confirmed on at least two points, before seriously considering opening anything:
> 
>     1. The "Air Attack Sub Restricted" property causes units that are "isSub" to be non-targetable by air units (what this PR would have changed is just to make this true in any case, instead of relating it to the state of the property upon starting the game only).

If a unit has `isSub` and the game has "Air Attack Sub Restricted" to true, then it gets `canNotBeTargetedBy` filled with all of the air units in the game.  If "Air Attack Sub Restricted" is false, then it has an empty `canNotBeTargetedBy`.  This PR doesn't change that functionality.  It only ensures that if "Air Attack Sub Restricted" is changed at any point (such as before the game starts through the "Map Options" UI button), then the current value is used instead of the hardcoded value in the XML.

> 
>     2. The "Air Attack Sub Restricted" property does nothing to units that are both "canNotBeTargetedBy" and non-"isSub" (now and regardless of this PR being merged).
> 
Yes.  "Air Attack Sub Restricted" is only used if the unit is `isSub`.

> 
> As a side note, since "isSub" is a shortcut (possibly setting "canNotBeTargetedBy" to all air units), I also wonder what would happen to units having both of the "isSub" and "canNotBeTargetedBy" options set.

I haven't tested this scenario, but the code looks like the setting of `canNotBeTargetedBy` will override the `isSub` value.  But it is possible that the `isSub` might override the `canNotBeTargetedBy` depending on the order of the properties in the XML.
```
<option name="isSub" value="true" />
<option name="canNotBeTargetedBy" value="something" />
```
and
```
<option name="canNotBeTargetedBy" value="something" />
<option name="isSub" value="true" />
```
might function differently just because the order is different.

**Comment by Cernelius** [comment]
> If a unit has `isSub` and the game has "Air Attack Sub Restricted" to true, then it gets `canNotBeTargetedBy` filled with all of the air units in the game. If "Air Attack Sub Restricted" is false, then it has an empty `canNotBeTargetedBy`. This PR doesn't change that functionality. It only ensures that if "Air Attack Sub Restricted" is changed at any point (such as before the game starts through the "Map Options" UI button), then the current value is used instead of the hardcoded value in the XML.

Thanks for the clarification. In this case, while somewhat an improvement from current, I'm not feeling as much positive any longer about this PR. Still setting (thus burning in the save-game) the option based on the property state at the start of the game, then possibly ignoring such a setting thereafter looks to me like a workaround that fixes a problem while keeping the roots of it in place, putting a substantially duplicate process on top of a different one, for the same matter.

**Comment by trevan** [comment]
> > If a unit has `isSub` and the game has "Air Attack Sub Restricted" to true, then it gets `canNotBeTargetedBy` filled with all of the air units in the game. If "Air Attack Sub Restricted" is false, then it has an empty `canNotBeTargetedBy`. This PR doesn't change that functionality. It only ensures that if "Air Attack Sub Restricted" is changed at any point (such as before the game starts through the "Map Options" UI button), then the current value is used instead of the hardcoded value in the XML.
> 
> Thanks for the clarification. In this case, while somewhat an improvement from current, I'm not feeling as much positive any longer about this PR. Still setting (thus burning in the save-game) the option based on the property state at the start of the game, then possibly ignoring such a setting thereafter, looks to me like a workaround that fixes a problem, while keeping the roots of it in place, putting a substantially duplicate process on top of a different one, for the same matter.

@Cernelius , I don't understand what you mean by that.  This isn't a work around to fix a problem or "burning in the save-game" or anything like that.  There are 4 properties that are affected by this: "Air Attack Sub Restricted", "Submersible Subs", "Ignore Sub In Movement", and "Defending Suicide and Munition Units Do Not Fire".  Right now, if you load a map with an `isSub` unit and has one of those options marked as editabled, then changing the value through the "Map Options" ui will not have any affect.

**Comment by DanVanAtta** [comment]
Long thread, just a quick comment, if we broke save-game compatibility it would be a `3.0` rather than a `2.2`

**Comment by trevan** [comment]
> Long thread, just a quick comment, if we broke save-game compatibility it would be a `3.0` rather than a `2.2`

Would it be considered breaking save-game compatibility if the save-game can load and be played but functionality will be incorrect?  For this PR, the game will load, the `isSub` triggers will just not work correctly.

**Comment by DanVanAtta** [comment]
It could probably be argued both ways. A discussion issue with a pro/con
list is perhaps a good way to move forward.

**Comment by trevan** [comment]
> It could probably be argued both ways. A discussion issue with a pro/con list is perhaps a good way to move forward.

I created #7237 to discuss this.

**Comment by trevan** [comment]
I've reopened it per the discussion in #7237.

**Comment by trevan** [comment]
Should I put something in the release notes about how this might break some saved games?

**Comment by DanVanAtta** [comment]
@trevan yes, and potentially list the maps that would be impacted to make it easy/clear for users.

**Comment by Cernelius** [comment]
A correction: While I still believe my understanding of the available documentation is correct, I just did some testing, and it appears that the property setting upon starting the game doesn't matter. What matters is only the setting defined in the xml, no matter if changed via "Map Options" (as far as the traditional terminology goes, wrong label, as it should say "Game Options"), before starting the game.

I tested it by giving a sea unit the option:
`<option name="isSub" value="true"/>`

And adding the property:
```
                <property name="Submersible Subs" value="false" editable="true">
                        <boolean/>
                </property>
```
No matter whether or not I set the property true (via "Map Options"), the unit was never having the "canMoveThroughEnemies" true behaviour.

---

As far as I recall, I believe this is not the behaviour wanted by the original creator of the "canMoveThroughEnemies" option (@ron-murhammer ). What I understood, during past discussions, was that the "isSub" shortcut was meant to set or not to set the option true depending on the "Submersible Subs" setting at the start of the game, not disregarding any use customization made before that point, as well (what I understood was that the user would have been unable to customize the behaviour after the start of the game, not unable to customize it at all, as it seems it is the case, instead). Again, as far as I recall.

**Comment by trevan** [comment]
@Cernelius , are you saying that is the current behavior?  Or the behavior with this fix?  Because that is what I'm fixing.  If you tested with this branch and got that behavior, then I'll need to look into it.

**Comment by Cernelius** [comment]
> @Cernelius , are you saying that is the current behavior? Or the behavior with this fix? Because that is what I'm fixing. If you tested with this branch and got that behavior, then I'll need to look into it.

I'm talking about the current behaviour (without this fix). At least from my limited testing, it appears that the current behaviour is following the setting in the game file (xml) regardless of any user customization. Meaning that, differently from what I previously said, the problem doesn't appear to be only that you cannot change the behaviour during the course of the game, but that you cannot customize it at all (also before starting the game).

**Comment by trevan** [comment]
> > @Cernelius , are you saying that is the current behavior? Or the behavior with this fix? Because that is what I'm fixing. If you tested with this branch and got that behavior, then I'll need to look into it.
> 
> I'm talking about the current behaviour (without this fix). At least from my limited testing, it appears that the current behaviour is following the setting in the game file (xml) regardless of any user customization. Meaning that, differently from what I previously said, the problem doesn't appear to be only that you cannot change the behaviour during the course of the game, but that you cannot customize it at all (also before starting the game).

Yes, that is what I've been saying.  This should fix that so that you can customize it before you start the game.

**Comment by Cernelius** [comment]
> > > @Cernelius , are you saying that is the current behavior? Or the behavior with this fix? Because that is what I'm fixing. If you tested with this branch and got that behavior, then I'll need to look into it.
> > 
> > 
> > I'm talking about the current behaviour (without this fix). At least from my limited testing, it appears that the current behaviour is following the setting in the game file (xml) regardless of any user customization. Meaning that, differently from what I previously said, the problem doesn't appear to be only that you cannot change the behaviour during the course of the game, but that you cannot customize it at all (also before starting the game).
> 
> Yes, that is what I've been saying. This should fix that so that you can customize it before you start the game.

Only before or also during the course of the game? Normally you should be able to take a save game, reload it, change settings and continue the game with the new settings.

For example, if the "Air Attack Sub Restricted" is set false and editable in the game file (xml), I should be able to enable it before starting the game, so that air won't be able to target submarines. However, then, I should be able to save the game, reload it, disable this option and continue the game with the submarines henceforth targetable by air.

**Comment by trevan** [comment]
> > > > @Cernelius , are you saying that is the current behavior? Or the behavior with this fix? Because that is what I'm fixing. If you tested with this branch and got that behavior, then I'll need to look into it.
> > > 
> > > 
> > > I'm talking about the current behaviour (without this fix). At least from my limited testing, it appears that the current behaviour is following the setting in the game file (xml) regardless of any user customization. Meaning that, differently from what I previously said, the problem doesn't appear to be only that you cannot change the behaviour during the course of the game, but that you cannot customize it at all (also before starting the game).
> > 
> > 
> > Yes, that is what I've been saying. This should fix that so that you can customize it before you start the game.
> 
> Only before or also during the course of the game? Normally you should be able to take a save game, reload it, change settings and continue the game with the new settings.
> 
> For example, if the "Air Attack Sub Restricted" is set false and editable in the game file (xml), I should be able to enable it before starting the game, so that air won't be able to target submarines. However, then, I should be able to save the game, reload it, disable this option and continue the game with the submarines henceforth targetable by air.

It should do both.  Instead of checking the property only when you load the map, it checks the property each time is needed.

**Comment by Cernelius** [comment]
Sounds good, even though I think it would make a better sense for any property to act only on the actual options, and every short-cut being no more than that. Sadly, currently the "isSub" and "isSuicide" are not really short-cuts, as you need them to use some properties for user customization (since the options they set are unable to).

I mean that rather than having "isSub" setting "canMoveThroughEnemies" true if "Submersible Subs" is true, I would advice "isSub" being a true short-cut for always setting "canMoveThroughEnemies" (and the other options) true, then having "canMoveThroughEnemies" active only as long as "Submersible Subs" is true. This way, the "isSub" would be truly a short-cut, as it would allow doing nothing more than what you can do by setting its components directly. This is what I told when the "isSub" was originally atomized (but was rejected).

Otherwise, I tend to suggest deprecating every property that is acting on short-cuts directly, if, going on, it is preferred, for example, not having the "canMoveThroughEnemies" options requiring the "Submersible Subs" property being true to be effective (which is actually not literally clear a correlation).

Opinions?

**Comment by trevan** [comment]
> Sounds good, even though I think it would make a better sense for any property to act only on the actual options, and every short-cut being no more than that. Sadly, currently the "isSub" and "isSuicide" are not really short-cuts, as you need them to use some properties for user customization (since the options they set are unable to).
> 
> I mean that rather than having "isSub" setting "canMoveThroughEnemies" true if "Submersible Subs" is true, I would advice "isSub" being a true short-cut for always setting "canMoveThroughEnemies" (and the other options) true, then having "canMoveThroughEnemies" active only as long as "Submersible Subs" is true. This way, the "isSub" would be truly a short-cut, as it would allow doing nothing more than what you can do by setting its components directly (since also when you set the "canMoveThroughEnemies" option true directly in the game file (without using "isSub"), you would need to have the "Submersible Subs" property true for the option to be effective). This is what I told when the "isSub" was originally atomized (but was rejected).
> 
> Otherwise, I tend to suggest deprecating every property that is acting on short-cuts directly if, going on, it is preferred, for example, not having the "canMoveThroughEnemies" options requiring the "Submersible Subs" property being true to be effective (which is actually not literally clear a correlation).
> 
> Opinions?

I'm not going to change the existing usage of the properties in this PR.  I think that deserves its own PR so that people can debate the type of questions you are asking.

But as for my opinion, I would be very confused if my helicopter (which has canMoveThroughEnemies) is affected by the property "Submersible Subs".

File: game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java [hunk 2]
```diff
@@ -226,6 +226,10 @@
   // Manually set TUV
   private int tuv = -1;
 
+  // combo properties
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java:229]: A 'combo' property is not well defined, what does this mean? Is this comment adding more than the questions it raises? I would suggest either explaining this more or just omitting the comment.

File: game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java [hunk 3]
```diff
@@ -647,31 +648,31 @@ private void setCanEvade(final Boolean s) {
...
+    return canEvade || isSub;
   }
 
   private void setIsFirstStrike(final Boolean s) {
     isFirstStrike = s;
   }
 
   public boolean getIsFirstStrike() {
-    return isFirstStrike;
+    return isFirstStrike || isSub || isSuicide;
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java:659]: This is sad to see of course as options become super complex. What happens when I set 'isFirstStrike = false' and 'isSub = true' (well, it is first strike even though the option is set to off). I think that examples shows we lack flexibility, you cannot have a non-first strike sub unit or non-first strike suicide unit. 

Is the other option for us instead of the 'combo' property would be to update all maps? I'm not sure if there is really a good alternative to the code update proposed, I'm more thinking out loud and wondering what other options we might have.

**Comment by DanVanAtta** [comment]
@trevan I updated the release note:
- only one release note per PR is supported
- the regression is rare enough and so nuanced I think it's going to be noise to the average player. If anyone reports a save-game having an issue, we can take up the problem then and just deal with it as it arrives. Perhaps it won't even be noticed..

File: game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java (hunk 3 above)
Comment (trevan) [reply game-core/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java:659]: Yes, the "combo" attributes are going to cause problems.  Before this code change, if you had
```
      <option name="isFirstStrike" value="false"/>
      <option name="isSub" value="true"/>
```
then your unit would have isFirstStrike == true.
But if you had
```
      <option name="isSub" value="true"/>
      <option name="isFirstStrike" value="false"/>
```
then your unit would have isFirstStrike == false.

With this change, at least the order doesn't matter anymore.  isFirstStrike will always be true.

If you want a non-first strike sub unit, you can make that.  You just can't use `isSub`.  You have to set the atomic properties yourself.  Same with a non-first strike suicide unit.

Another option, I think, is to add to the documentation that the individual atomic properties of the combo properties can't be overridden.  If they want to have custom units, then they need to use the atomic properties instead.  The combo properties are there just to simplify the creation of basic units.

If we want atomic properties to be able to override combo properties, then we'll need some sort of flag to indicate that the atomic property is actually set.  Because setting a property to false is currently the same thing as not setting the property at all.  But I think we should focus the documentation on moving towards atomic properties only and just mark all of the combo properties as deprecated.  Then, somehow, indicate to the map maker that the property shouldn't be used.

**Comment by trevan** [comment]
> @trevan sorry for delay in getting some feedback to you on this. Would our only alternative to a combo property be to update all existing maps (with any of the notably properties in this PR)?

Updating the existing maps away from the combo property won't fix this issue.  Part of this issue is being able to turn on/off the map property "Air Attack Sub Restricted" and have it affect the unit.  The atomic properties don't care about the map property.  We would have to change the atomic properties to follow the map properties (which is what @Cernelius is advocating above).

**Comment by Cernelius** [comment]
> > Sounds good, even though I think it would make a better sense for any property to act only on the actual options, and every short-cut being no more than that. Sadly, currently the "isSub" and "isSuicide" are not really short-cuts, as you need them to use some properties for user customization (since the options they set are unable to).
> > I mean that rather than having "isSub" setting "canMoveThroughEnemies" true if "Submersible Subs" is true, I would advice "isSub" being a true short-cut for always setting "canMoveThroughEnemies" (and the other options) true, then having "canMoveThroughEnemies" active only as long as "Submersible Subs" is true. This way, the "isSub" would be truly a short-cut, as it would allow doing nothing more than what you can do by setting its components directly (since also when you set the "canMoveThroughEnemies" option true directly in the game file (without using "isSub"), you would need to have the "Submersible Subs" property true for the option to be effective). This is what I told when the "isSub" was originally atomized (but was rejected).
> > Otherwise, I tend to suggest deprecating every property that is acting on short-cuts directly if, going on, it is preferred, for example, not having the "canMoveThroughEnemies" options requiring the "Submersible Subs" property being true to be effective (which is actually not literally clear a correlation).
> > Opinions?
> 
> I'm not going to change the existing usage of the properties in this PR. I think that deserves its own PR so that people can debate the type of questions you are asking.
> 
> But as for my opinion, I would be very confused if my helicopter (which has canMoveThroughEnemies) is affected by the property "Submersible Subs".

"Submersible Subs" is a badly named property anyway, to start with. What that property appears doing is turning the "submarines" behaviour from v1 (Classic) to v2 (Revised) rules (problems aside). Being able to submerge being only one item (likely the most important one).

In my opinion, the proper way to address such confusion is by renaming the property itself (deprecating the current name) or, better, making this property into what it should have been since ever: a short-cut only property for setting a number of other properties, one for every change from v1 to v2 it is causing.

In our case, one of the sub-properties that the "Submbersible Subs" short-cut property will set true may be called as "Land and Naval Units May Move Through Enemies" and, in turn, this property will be required being true for every "canMoveThroughEnemies" unit option to be effective.

This way, the "canMoveThroughEnemies" option is part of the "isSub" option (also setting other options) and the "Land and Naval Units May Move Through Enemies" property is part of the "Submersible Subs" property (also setting other properties).

In my opinion, short-cuts should be nothing else but that, and this strange process, we are going along with, of having shortcuts being necessary elements for user customization (meaning in case you want to let the user be able to opt) should never exist.

**Comment by DanVanAtta** [comment]
Shortcut properties will generally always cause an issue. If you set a shortcut property, and set one of the shortcutted properties to a contrary value, then which one wins? I do like in this update that odering does not matter as much and to fix that you just enumerate the non-shortcut properties explicitly. 

In general, having properties be 1:1 I think is just going to be the cleanest. A shortcut is saving perhaps 2 or 3 lines per unit that has the shortcut, so in a XML file that can be thousands of lines, we're talking at best a dozen lines. I think the shortcut property was probably introduced as a concept when we realized that one property was controlling many options and we wanted those options individually. Instead of removing the shortcut, we added the individual properties and then defined the shortcut property in terms of the others. If that is the evolution, then really a shortcut property is a legacy property.

**Comment by Cernelius** [comment]
> Shortcut properties will generally always cause an issue. If you set a shortcut property, and set one of the shortcutted properties to a contrary value, then which one wins?

In my opinion, having both a short-cut and one or more of anything the short-cut is setting is bad coding. The mapmaker should be informed never to do that.

In my opinion, I certainly believe this should work the same way in all cases. The way it currently works, for the record, is that priority goes to the option set after, for all options that cannot have multiple instances on the same unit.

I would personally prefer the behaviour being the game failing to parse if a same unit has multiple instances of options that cannot have multiple instances. This would, in turn, imply that any unit having both a short-cut option and one or more single-instance options that are set by it should fail to parse (thus being unavailable to every user), but adopting such a behaviour at this point will likely cause a huge number of (in my opinion, badly coded) games to fail to parse.

>I do like in this update that odering does not matter as much and to fix that you just enumerate the non-shortcut properties explicitly.

This is bad, because it is non-coherent. If the order matters for something, it should matter the same way for everything. If the order doesn't matter for something, it shouldn't matter for anything.

---

Short-cuts themselves are great. The best example of short-cuts are those that (problems aside) allow you to set true all properties making a rules set, which currently means only this, for example:
```
    <property name="WW2V2" value="true" editable="false">
      <boolean/>
    </property>
```
If the above short-cut property would not exist, any mapmaker wanting simply to have the v2 rules set would be forced to take care to set every relevant property correctly, which can only cause an increase in the likehood of setting something wrong or missing to set something or both.

**Comment by DanVanAtta** [comment]
> In my opinion, having both a short-cut and one or more of anything the short-cut is setting is bad coding. The mapmaker should be informed never to do that.

Wouldn't it be even better if the XML only allowed for good coding?

> The way it currently works, for the record, is that priority goes to the option set after, for all options that cannot have multiple instances on the same unit.

This is not guaranteed. XML is not order-dependent. You cannot guarantee that any XML parser will respect ordering of tags. While it 'happens to work', it could break in the future depending on the XML parser. It's bad XML design to require ordering, notably for this reason.

>  If the order matters for something, it should matter the same way for everything.

Perhaps, but again, XML ordering dependency is fundamentally broken. It is not reliable. Anything that does rely on ordering should be considered as potentially buggy (it could stop working at any moment as soon as the bug is exposed). Re-ordering lines would be one way to do that. What it comes down to is the XML spec is a bit naive and not the best in some places.


> Re: WW2v2

That's not actually a shortcut. There are behaviors that depend exclusively on WW2v2 being set. You cannot completely emulate that property by setting other properties, it is its own property. The fact that other properties interact with WW2v2 is more the game engine being a mess.

**Comment by Cernelius** [comment]
> I think the shortcut property was probably introduced as a concept when we realized that one property was controlling many options and we wanted those options individually. Instead of removing the shortcut, we added the individual properties and then defined the shortcut property in terms of the others. If that is the evolution, then really a shortcut property is a legacy property.

This is certainly (not just probably) the case for both the "isSub" and the "isSuicide" options. It may as well be the case for every short-cut currently in existance. Short-cuts that set only 1 option (for example, "isInfantry") are obviously old versions (the old name deemed bad enough to require a new one). Still, this doesn't mean that the short-cut is merely a legacy. Personally, if we would be adding all options the "isSub" is setting, I would suggest having a short-cut like "isSub". The legacy element is more in the wording of the short-cut itself, that goes back to the times when only sea units were allowed to have it, and they were supposed to be "submarines".

I can easily see some mapmaker setting something wrong or missing to set something, or both, while attempting to have a unit behaving like the "submarine" units of some rules set, with no "isSub" short-cut option to use.

**Comment by DanVanAtta** [comment]
I'll grant there is convenience and simplicity in a shortcut, though it makes it complicated as soon as you get out of that best-case scenario and want for example a non-first strike sub. Having subs be a standard 2 or 3 options and then copy/pasted I'm sure is very manageable.

**Comment by DanVanAtta** [comment]
>  The legacy element is more in the wording of the short-cut itself, that goes back to the times when only sea units were allowed to have it, and they were supposed to be "submarines".

Yeah, I think this is really similar to specifying multiple behaviors with the single option. Unit options I suspect are going to always be best enumerated one by one. This way you don't have the craziness of an air unit being "isSub". If we called each unit option by what the option is, then it's hard to think of when it would get out of date. 'FirstStrke' should always be, 'FirstStrike', and that helps since you can then have very sensible first strike air units.

**Comment by Cernelius** [comment]
> > Re: WW2v2
> 
> That's not actually a shortcut. There are behaviors that depend exclusively on WW2v2 being set. You cannot completely emulate that property by setting other properties, it is its own property. The fact that other properties interact with WW2v2 is more the game engine being a mess.

Yes, I'm aware of this and I disagree with this. I think `WW2v2` should be merely a short-cut (as I've said in an issue more specific to the matter). Anyway, I think it's pretty clear that `WW2v2` is mainly a short-cut. I didn't enter into details merely to try to stay focused on the matter at hand.

This is the off-topic issue, where I would rather discuss such matters (as I said, I believe those behaviours you are mentioning are not even documented anywhere at all: Good luck mapmaking that if you are not a developer!):
https://github.com/triplea-game/triplea/issues/5394

**Comment by DanVanAtta** [comment]
Ah, interesting you raised an issue @Cernelius 

Disagreeing/agreeing with WW2v2 being a short cut is not quite the point. I would agree though that it *should* be a shortcut (and at that point I'd like to see it removed!). IMO WW2v2 should be a setting only when speciyfing game rules when starting a game.  The checkbox would essentially disable all other settings and give you a default set of options. IMO it would be good to then be able to unselect it and override any options you would want. Similar for V3, so you could play with a specific rule set, or you could specify them individually. At the end of the day the engine is only then aware of the individual rules/options (so the engine would not even be aware of "V3", it would only care "do naval bombard casualties fire back?" (which could be turned on/off by however manner).

The way `WW2v2` is used in the code is a mess.. Which leads to exactly "Good luck mapmaking that if you are not a developer!", but even then "Good luck if you are a developer!"

**Comment by Cernelius** [comment]
> Ah, interesting you raised an issue @Cernelius
> 
> Disagreeing/agreeing with WW2v2 being a short cut is not quite the point. I would agree though that it _should_ be a shortcut (and at that point I'd like to see it removed!).

For the removed part, as I've already argued against that in the issue, with other two developers, I'll just summarize the main two reasons why having a rules set short-cut is highly advantageous:
1- A lot of mapmakers have scarce knowledge of the differences between rules set and just want to pick one they are familiar with (usually, v2), especially in the moment the TripleA default is mostly the rather backward and unpopular "Classic": Having to set every property manually will easily result in missing something or setting something wrong, or both (and, with custom maps (not having a full rulebook, most likely), is, then, not necessarily easy to be sure whether something was originally wanted or not).
2- Some differences between the rules set are currently not supported by TripleA, with individual properties. Therefore, if anyone would add a missing property that applies only to some rules set, having a short-cut property for setting a whole rules-set allows fixing existent maps automatically (for example, if you add a missing property to support a currently unsupported v2 behaviour (as an example amongst many, a developer implements the call-off landings rules of Revised, which are currently completely missing), all games having the `WW2v2` property true should in theory benefit from the enhancement (keeping with the previous example, you will be able to call off landings when playing World At War, from that version of TripleA onwards)).

Please, refer to this issue for a more in dept analysis:
https://github.com/triplea-game/triplea/issues/5394

---
I might agree with not having rules set wide short-cut properties if TripleA would already perfectly support all rules set (no properties missing) and would have a flawless, very good and complete map-making program, in which you would choose a rules set and the game file (XML or whatever) would be autogenerated accordingly.
