### PR TITLE
Fix dice RegEx

### LINKED ISSUE #6876: 2.0.20234: MartiDiceRoller#getDice:106 - IllegalStateException
## User Description
I tried playing TWW 3.0 by forum and some of the dice throws aren't registered by the client. Also I wasn't able to upload the error message on my client under windows. The dice problem happens on windows and linux.

## Log Message
String '
<!DOCTYPE html>
<html>
	<head>
		<title>M.A.R.T.I. Server -- "more accurate rolls than irony"</title>
	</head>
	<body>
		<p>Dice results were sent via email.</p><br><a href='https://dice.marti.triplea-game.org/MARTI_verify.php?iv=7fVnvhjzbpDx134kZmGxE3cdhzcBlGwCp1x2Dr3q2S4%3D&enc=352Q0HHUsIcH937P3WqKFG%2B00Z36%2ForsPYRXJAs2SAk%2FlfHnxFIZNkvLKhBM1Q7n4SQV1qoyPWXq3YZpkzEH5lCRbtf8KWlPQmioQGKCyPQIYURVL2Kt2LIgwNGT%2FWp8f7EJ%2BRHj1f5%2FVSDcCBiHcuGs94ul14ZWz6eQ5BcELCMJ8cxMm16BBcWd7oZakfukbHsL6IdaTETi3FQhl6J5cIqqTk8LR%2BTWyRDPQaseKQr5fjUen896nM%2Fc9DCXooXA4z6meX9F364HkvJevuDNauy2VtuJHIm8mpyeekk1LyIVRZ%2BQYHIvHqiZADPNx9s%2F4V%2BFpRO%2FdcB8rfy2reE57BMYfkD5cfY6vLxV7f1f9xjm'>Click here to verify the roll.</a><br>your dice are: 12,2<p><p>	</body>
</html>
' has an invalid format.

## TripleA Version
2.0.20234

## Java Version
11.0.7

## Operating System
Linux

## Exception 
java.lang.IllegalStateException: String '
<!DOCTYPE html>
<html>
	<head>
		<title>M.A.R.T.I. Server -- "more accurate rolls than irony"</title>
	</head>
	<body>
		<p>Dice results were sent via email.</p><br><a href='https://dice.marti.triplea-game.org/MARTI_verify.php?iv=7fVnvhjzbpDx134kZmGxE3cdhzcBlGwCp1x2Dr3q2S4%3D&enc=352Q0HHUsIcH937P3WqKFG%2B00Z36%2ForsPYRXJAs2SAk%2FlfHnxFIZNkvLKhBM1Q7n4SQV1qoyPWXq3YZpkzEH5lCRbtf8KWlPQmioQGKCyPQIYURVL2Kt2LIgwNGT%2FWp8f7EJ%2BRHj1f5%2FVSDcCBiHcuGs94ul14ZWz6eQ5BcELCMJ8cxMm16BBcWd7oZakfukbHsL6IdaTETi3FQhl6J5cIqqTk8LR%2BTWyRDPQaseKQr5fjUen896nM%2Fc9DCXooXA4z6meX9F364HkvJevuDNauy2VtuJHIm8mpyeekk1LyIVRZ%2BQYHIvHqiZADPNx9s%2F4V%2BFpRO%2FdcB8rfy2reE57BMYfkD5cfY6vLxV7f1f9xjm'>Click here to verify the roll.</a><br>your dice are: 12,2<p><p>	</body>
</html>
' has an invalid format.

## Stack Trace
```
java.lang.IllegalStateException: String '
<!DOCTYPE html>
<html>
	<head>
		<title>M.A.R.T.I. Server -- "more accurate rolls than irony"</title>
	</head>
	<body>
		<p>Dice results were sent via email.</p><br><a href='https://dice.marti.triplea-game.org/MARTI_verify.php?iv=7fVnvhjzbpDx134kZmGxE3cdhzcBlGwCp1x2Dr3q2S4%3D&enc=352Q0HHUsIcH937P3WqKFG%2B00Z36%2ForsPYRXJAs2SAk%2FlfHnxFIZNkvLKhBM1Q7n4SQV1qoyPWXq3YZpkzEH5lCRbtf8KWlPQmioQGKCyPQIYURVL2Kt2LIgwNGT%2FWp8f7EJ%2BRHj1f5%2FVSDcCBiHcuGs94ul14ZWz6eQ5BcELCMJ8cxMm16BBcWd7oZakfukbHsL6IdaTETi3FQhl6J5cIqqTk8LR%2BTWyRDPQaseKQr5fjUen896nM%2Fc9DCXooXA4z6meX9F364HkvJevuDNauy2VtuJHIm8mpyeekk1LyIVRZ%2BQYHIvHqiZADPNx9s%2F4V%2BFpRO%2FdcB8rfy2reE57BMYfkD5cfY6vLxV7f1f9xjm'>Click here to verify the roll.</a><br>your dice are: 12,2<p><p>	</body>
</html>
' has an invalid format.
	at games.strategy.engine.random.MartiDiceRoller.getDice(MartiDiceRoller.java:106)
	at games.strategy.engine.random.PbemDiceRoller$HttpDiceRollerDialog.rollInSeparateThread(PbemDiceRoller.java:212)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fixes #6876

## Functional Changes

[] New map or map update
[] New Feature
[] Feature update or enhancement
[] Feature Removal
[] Code Cleanup or refactor
[] Configuration Change
[x] Problem fix
[] Other:   

## Release Note

Fix|MARTI dice rolls where the first die has multiple digits are now parsed correctly

### CODE REVIEW

**Comment by DanVanAtta** [comment]
@RoiEXLab could you update the commit comment to explain how the regex is fixed? What was broken, why was it wrong to begin with?

File: game-core/src/main/java/games/strategy/engine/random/MartiDiceRoller.java [hunk 1]
```diff
@@ -43,7 +43,7 @@
   // Matches a comma separated list of integers like this:
   // your dice are: 1,2,3 <p>
```
Comment (DanVanAtta) [inline game-core/src/main/java/games/strategy/engine/random/MartiDiceRoller.java:44]: This comment probably could use elaboration and give a number more examples of what we are supposed to match.

File: game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java [hunk 2]
```diff
@@ -13,7 +13,7 @@
 
 public class MartiDiceRollerTest {
   private static final String successMessage =
-      "Some text before<br>your dice are: 2,5,1<p><p>\t</body>\nsome text after";
+      "Some text before<br>your dice are: 22,5,100<p><p>\t</body>\nsome text after";
```
Comment (DanVanAtta) [inline game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java:16]: Good to see test case updated, though should we perhaps still have the original test data be tested as well for more coverage? Would this be better as a new & additional test rather than updating the existing test?

**Comment by RoiEXLab** [comment]
@DanVanAtta it's a dumb error. Basically if the first die has more than one digit the regex wouldn't find it. So the change is from single digit `\d` to one or more digits `d+`.

That's why I didn't really comment on it I can't believe that we haven't noticed such a fundamental issue until now.

File: game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java (hunk 2 above)
Comment (RoiEXLab) [reply game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java:16]: See my explanation. Basically the first number can now have multiple digits as well

Comment (DanVanAtta) [reply game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java:16]: Again, would it be more comprehensive to have additional test cases rather just this one?
For example, can we have 'zero's', all ones, what if we have just one dice roll, how about more than just three?

**Comment by DanVanAtta** [comment]
@RoiEXLab I'm asking that the explanation be captured in the commit comment so that if anyone attempts to change the regex, they can see in the history the reasoning for why it is what it is. PR comments are only valuable for pointing a reviewer to more resources, maintainers should never be expected to look at PRs to understand the code (there is no end to the scorn when you have to look at all PRs in a given time window of an update to then find critical context as some side comment in a PR).

File: game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java (hunk 2 above)
Comment (DanVanAtta) [reply game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java:16]: The original tests passed, yet a 'hotfix' is still needed. By changing the existing test cases, we are losing some data variations. I would suggest that one of the root causes of this problem was insufficient test cases, we did not model in test the actual data set and there was a data set that caused a problem. Generally, bug fixes will receive brand new test cases to reveal the bug before the problem is fixed. That would mean to leave existing test cases along so you can be sure you are not regressing and that you are finding the new problem. As-is, the test coverage seems to be somewhat focused on relatively happy case testing and is lacking potentially interesting test cases.

File: game-core/src/main/java/games/strategy/engine/random/MartiDiceRoller.java (hunk 1 above)
Comment (DanVanAtta) [reply game-core/src/main/java/games/strategy/engine/random/MartiDiceRoller.java:44]: bump, this comment is out of date and/or inadequate since the regex matches far more than just the above example. Expecting single digits is part of the problem of the original regex, this comment is misleading (arguably greatly contributed to this bug)

**Comment by DanVanAtta** [comment]
@RoiEXLab if you would do a few things here for this to be a really good fix:
- please document in the code the updated regex and what it matches. 
- Ideally update the commit comment to explain why there was a discrepancy (optional, but really nice for any future maintainers to have that context; recall that PR commentary is all throw-away once it is merged)
- I'd like to see additional test cases added to be sure everything is good:
   - keep the test case you added here
   - original test case maintained
   - singleton dice roll
   - triple digit dice roll
   - two dice rolls

**Comment by RoiEXLab** [comment]
@DanVanAtta Added the test cases, I think this should cover a lot of cases

File: game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java [hunk 3]
```diff
@@ -26,15 +27,79 @@
...
+
+      assertThat(dice, is(array(equalTo(0))));
+    }
+
+    @Test
+    @SuppressWarnings("unchecked")
+    void singleDieMultipleDigit() throws Exception {
+      final Integer[] dice = boxedArray(martiDiceRoller.getDice("your dice are: 1337<p>", 0));
+
+      assertThat(dice, is(array(equalTo(1336))));
```
Comment (DanVanAtta) [inline game-core/src/test/java/games/strategy/engine/random/MartiDiceRollerTest.java:46]: Looking at this, realizing we translate dice rolls to be zero-based :facepalm:

**Comment by DanVanAtta** [comment]
Perfect, thank you for the updates  :+1:
