### PR TITLE
Refactor IDelegateBridge and fix exceptions

### LINKED ISSUE #10811: 2.6.20: ProDummyDelegateBridge#getResourceLoader:53 - java.lang.UnsupportedOperationException
## Map
global_40_house_rules

## Log Message
ProDummyDelegateBridge does not have a resource loader

## TripleA Version
2.6.20

## Java Version
11.0.9.1

## Operating System
Windows 10

## Stack Trace
```
Exception: java.lang.UnsupportedOperationException ProDummyDelegateBridge does not have a resource loader
java.lang.Exception
	at games.strategy.triplea.ai.pro.simulate.ProDummyDelegateBridge.getResourceLoader(ProDummyDelegateBridge.java:53)
	at games.strategy.triplea.delegate.PoliticsDelegate.notifySuccess(PoliticsDelegate.java:335)
	at games.strategy.triplea.delegate.PoliticsDelegate.attemptAction(PoliticsDelegate.java:136)
	at games.strategy.triplea.ai.pro.ProPoliticsAi.doActions(ProPoliticsAi.java:189)
	at games.strategy.triplea.ai.pro.ProPoliticsAi.politicalActions(ProPoliticsAi.java:180)
	at games.strategy.triplea.ai.pro.AbstractProAi.purchase(AbstractProAi.java:264)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:508)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:593)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:450)
	at games.strategy.engine.framework.ServerGame.runNextStep(ServerGame.java:345)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:312)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:92)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.lambda$launch$0(LocalLauncher.java:60)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

### PR DESCRIPTION
**Pull request by RoiEXLab**
## Change Summary & Additional Notes

This removes unused methods from the `IDelegateBridge` interface and fixes #10811

### CODE REVIEW

File: game-app/game-core/src/main/java/games/strategy/engine/delegate/IDelegateBridge.java [hunk 1]
```diff
@@ -99,7 +93,11 @@ public interface IDelegateBridge {
 
   void sendMessage(WebSocketMessage webSocketMessage);
```
Comment (RoiEXLab) [inline game-app/game-core/src/main/java/games/strategy/engine/delegate/IDelegateBridge.java:94]: @DanVanAtta This method is unused but seems to have to do with the server relay project. Should it be removed or will it serve a certain purpose in the near future?

**Comment by RoiEXLab** [comment]
@asvitkine I'm not completely happy with this solution. It works, but I wouldn't consider it clean code :/

File: game-app/game-core/src/main/java/games/strategy/triplea/delegate/UserActionDelegate.java [hunk 2]
```diff
@@ -259,13 +262,18 @@ private void notifySuccess(final UserActionAttachment userActionAttachment) {
...
-    final String text = userActionAttachment.getText();
-    sendNotification(uat.getNotificationSuccess(text));
-    notifyOtherPlayers(
-        userActionAttachment,
-        uat.getNotificationSuccessOthers(text),
-        uat.getNotificationSuccessTarget(text));
+    bridge
+        .getResourceLoader()
+        .ifPresent(
+            resourceLoader -> {
```
Comment (asvitkine) [inline game-app/game-core/src/main/java/games/strategy/triplea/delegate/UserActionDelegate.java:268]: Nit: Up to you, but this construct is a bit verbose.

This would be more concise:
```java
ResourceLoader resourceLoader = bridge.getResourceLoader().orElse(null);
if (resourceLoader != null) {
  ...
}
```

**Review by asvitkine — APPROVED** [review]
