### PR TITLE
Fix broken unloadable units comparator

### LINKED ISSUE #3014: Unloading transports
Noticed a change in behavior while playing.
This could very well be intended behavior for good reason (AI or something) just wanted to verify.

At least as far back as 8659 up to 8847:
You select all units in a grand armada (Land, naval and air) and move all to a land territory
>> Result: for the landunits the movement is impossible. Air units from the stack will still move.
You have to single out the land-units from the navy to move them to a land-territory.

Up until last stable(7621) : you can select all units in a grand armada (Land, naval and air) and move all to a land territory.
>> Result: all land-units and air-units will move to the territory.

I find the previous behavior very convenient for quick movement especially in the case of large masses of units.

### PR DESCRIPTION
**Pull request by ssoloff**
Fixes #3014.

The units passed to `getUnloadableTransportsComparator()` must be the transports themselves and not the units being transported.  The call to `TripleAUnit#getTransportedBy()` was unintentionally dropped in #2900.

I'm not really happy with the unit test I added to verify this fix.  I wish it was easier to create a custom game engine state.  Any input is appreciated.

### CODE REVIEW

File: game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java [hunk 1]
```diff
@@ -109,8 +109,10 @@
    */
   public static Comparator<Unit> getUnloadableUnitsComparator(final List<Unit> units, final Route route,
       final PlayerID player) {
-    return Comparator.comparing(TripleAUnit::get,
-        Comparator.nullsLast(getUnloadableTransportsComparator(units, route, player, false)))
+    return Comparator
+        .<Unit, TripleAUnit>comparing(
+            unit -> TripleAUnit.get(unit).getTransportedBy(),
```
Comment (ssoloff) [inline game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java]: Not sure why the compiler can't infer the type arguments here.  Even when I simply switched the mapper from the method reference `TripleAUnit::get` to the lambda `unit -> TripleAUnit.get(unit)`, it couldn't infer the types.  Strange as those should be equivalent...

Comment (ron-murhammer) [reply game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java]: Not sure why.

**Comment by ron-murhammer** [comment]
@ssoloff Yep, that should fix it. The unit test is fairly similar to what I've created for other move related tests. We could probably use some better test utility methods but its not terrible.

File: game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java (hunk 1 above)
Comment (DanVanAtta) [reply game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java]: same problem with builders, needs the type hinting to know what the first lambda is going to be.  There could be a chain of more operations, like "A -> B -> C". The compiler does know that "C" is the output, but becuase there are potentially mutiple ways to chain to get to a C, it needs to know the starting point.

File: game-core/src/test/java/games/strategy/triplea/delegate/UnitComparatorTest.java [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import games.strategy.engine.data.PlayerID;
+import games.strategy.engine.data.Route;
+import games.strategy.engine.data.Territory;
+import games.strategy.engine.data.Unit;
+import games.strategy.triplea.xml.TestMapGameData;
+
+public final class UnitComparatorTest {
+  private static void startCombatMoveFor(final PlayerID playerId, final GameData gameData) {
+    final MoveDelegate moveDelegate = moveDelegate(gameData);
+    final ITestDelegateBridge bridge = getDelegateBridge(playerId, gameData);
```
Comment (DanVanAtta) [inline game-core/src/test/java/games/strategy/triplea/delegate/UnitComparatorTest.java]: I think the problem is roughly here, this is actually not a unit test. It's a problem with most of the tripleA testing. The way to fix is likely to stop trying to create custom game states, but instead rework modules to be *told* what game state they are in (IOC principle)

File: game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java (hunk 1 above)
Comment (ssoloff) [reply game-core/src/main/java/games/strategy/triplea/delegate/UnitComparator.java]: Yeah, I would have thought there being only a single overload for `TripleAUnit#get()`, the compiler would have been able to deduce that the type of the lambda input parameter was `Unit`, but I guess not.  Maybe because `Unit` isn't `final`, it doesn't know if a subtype could be substituted instead?  Dunno...

Anyway, after looking at this again, I realize now I could have just explicitly typed the lambda input parameter, instead of both the input and output type parameters on the `Comparator#comparing()` call:

```java
return Comparator
    .comparing(
        (Unit unit) -> TripleAUnit.get(unit).getTransportedBy(),
        Comparator.nullsLast(getUnloadableTransportsComparator(units, route, player, false)))
    .thenComparing(getMovableUnitsComparator(units, route));
```

Live and learn... :smile:
