### PR TITLE
Fix non-filling scroll pane

### LINKED ISSUE #3270: Actions and Operations opens up too small (sometimes)
### Engine version
1.9.0.0.9708 but most likely also many older versions

### My Operating System
Windows 10 64-bit

### Map name
Iron War and maybe other maps.

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Sometimes the Actions and Operations window is not wide and high enough to show the window content. The window pops up too small resulting in all the content of the window hidden.
If one, with the mouse, expands the window, the content gets visible again when the window is large enough. One can also manually shrink the window and then the content gets hidden again. (see the pictures posted below)

I have no idea about what is causing this and how it could be fixed, but I think if the window always popped up large enough the problem would not show? Maybe a solution would also be to not allow the window size to ever (manually or automatically) be smaller than the content in the window?
unavngivet1
unavngivet2

### PR DESCRIPTION
**Pull request by RoiEXLab**
Fixes #3270

### CODE REVIEW

File: game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java [hunk 1]
```diff
@@ -125,16 +125,15 @@ public void actionPerformed(final ActionEvent event) {
       int row = 0;
       final JScrollPane choiceScroll = new JScrollPane(getUserActionButtonPanel(userChoiceDialog));
       choiceScroll.setBorder(BorderFactory.createEtchedBorder());
-      choiceScroll.setPreferredSize(getUserActionScrollPanePreferredSize(choiceScroll));
-      userChoicePanel.add(choiceScroll, new GridBagConstraints(0, row++, 2, 1, 0.0, 0.0, GridBagConstraints.CENTER,
+      userChoicePanel.add(choiceScroll, new GridBagConstraints(0, row++, 2, 1, 1, 1, GridBagConstraints.CENTER,
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java]: This line change alone should already fix the issue

File: game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java [hunk 2]
```diff
@@ -192,20 +191,6 @@ static boolean canPlayerAffordUserAction(final PlayerID player, final UserAction
     return userAction.getCostPu() <= player.getResources().getQuantity(Constants.PUS);
   }
 
-  private static Dimension getUserActionScrollPanePreferredSize(final JScrollPane scrollPane) {
```
Comment (RoiEXLab) [inline game-core/src/main/java/games/strategy/triplea/ui/UserActionPanel.java]: According to veqryn this code was there to account for any potential scrollbar that appears when the content is too big and causes another scroll bar to appear, so a second scrollbar doesn't appear just because the content no longer fits in the frame once the first scrollbar takes up space.
However this didn't seem to work so I dropped the code.
